/**
 * Nümunə (demo) məzmunun mənbə məlumatı.
 *
 * Mətnlər qəsdən reklam üslubundadır: məqsəd saytın kart, filtr, detal və
 * kataloq səthlərinin real elan həcmi ilə necə göründüyünü yoxlamaqdır.
 * Bütün obyektlər uydurmadır — ünvan, qiymət və şirkət adları real bazar
 * təklifi deyil, hər təsvirin sonuna nümunə bildirişi əlavə olunur.
 *
 * Fayl yalnız `build-demo-content.ts` tərəfindən oxunur və tətbiq kodundan
 * import edilmir.
 */

/** Hər təsvirin sonuna qoşulan bildiriş — nümunə qeyd real elanla qarışmasın. */
export const DEMO_NOTICE =
  "Qeyd: bu, Luxe Home Estate platformasının test rejimi üçün hazırlanmış nümunə elandır. " +
  "Obyekt, qiymət və əlaqə məlumatları uydurmadır.";

export type ListingKind = "SALE" | "RENT";

/** Bir kateqoriyanın necə elan doğuracağını təsvir edir. */
export type CategoryRecipe = {
  /** `PropertyType.slug` — bazada mövcud olmalıdır. */
  slug: string;
  /** Elan başlığında istifadə olunan qısa ad. */
  label: string;
  /** Başlıq şablonları; `{yer}` və `{ölçü}` əvəzlənir. */
  titles: string[];
  /** Reklam mətninin açılış cümlələri. */
  leads: string[];
  /** Satış arqumentləri — hər elana 3-ü seçilir. */
  selling: string[];
  /** Satış / kirayə bölgüsü: 20 elandan neçəsi kirayə olsun. */
  rentShare: number;
  /** Satış qiyməti (AZN) diapazonu. */
  salePrice: [number, number];
  /** Aylıq kirayə (AZN) diapazonu. */
  rentPrice: [number, number];
  /** Sahə (m²) diapazonu. `null` — sahə göstərilmir. */
  area: [number, number] | null;
  /** Torpaq sahəsi (sot) diapazonu — torpaq və həyət tipli obyektlərdə. */
  landArea: [number, number] | null;
  /** Otaq sayı diapazonu. `null` — otaq anlayışı tətbiq olunmur. */
  rooms: [number, number] | null;
  /** Mərtəbəli binadırsa mərtəbə diapazonu. */
  floors: [number, number] | null;
  /** Bu kateqoriyada məntiqli olan xüsusiyyət slug-ları. */
  features: string[];
  /** `Property.renovation` üçün namizədlər. */
  renovations: string[];
  /** `Property.documentStatus` üçün namizədlər. */
  documents: string[];
  /** NEW / OLD bölgüsü üçün yeni tikili payı (0–1). */
  newBuildingShare: number;
  /** Unsplash foto ID-ləri — kart və qalereya üçün. */
  photos: string[];
};

/**
 * Bakı rayonları və regionlar.
 * `city` sütunu `Location.slug`, `district` isə Bakı daxilində alt rayondur.
 */
export const PLACES: Array<{ city: string; district: string | null; name: string }> = [
  { city: "baki", district: "baki-sebail", name: "Səbail" },
  { city: "baki", district: "baki-nesimi", name: "Nəsimi" },
  { city: "baki", district: "baki-nerimanov", name: "Nərimanov" },
  { city: "baki", district: "baki-yasamal", name: "Yasamal" },
  { city: "baki", district: "baki-xetai", name: "Xətai" },
  { city: "baki", district: "baki-nizami", name: "Nizami" },
  { city: "baki", district: "baki-bineqedi", name: "Binəqədi" },
  { city: "baki", district: "baki-sabuncu", name: "Sabunçu" },
  { city: "baki", district: "baki-xezer", name: "Xəzər" },
  { city: "baki", district: "baki-suraxani", name: "Suraxanı" },
  { city: "baki", district: "baki-qaradag", name: "Qaradağ" },
  { city: "baki", district: "baki-novxani", name: "Novxanı" },
  { city: "sumqayit", district: null, name: "Sumqayıt" },
  { city: "xirdalan", district: null, name: "Xırdalan" },
  { city: "qebele", district: null, name: "Qəbələ" },
  { city: "gence", district: null, name: "Gəncə" },
];

/** Küçə adları — ünvan sətrini canlandırmaq üçün. */
export const STREETS = [
  "Nizami küçəsi",
  "Əliyar Əliyev küçəsi",
  "Zərifə Əliyeva prospekti",
  "Həsən Əliyev küçəsi",
  "Cəfər Cabbarlı küçəsi",
  "Xocalı prospekti",
  "Neftçilər prospekti",
  "Şərifzadə küçəsi",
  "Tbilisi prospekti",
  "Koroğlu Rəhimov küçəsi",
  "Bakıxanov küçəsi",
  "İnşaatçılar prospekti",
];

export const CATEGORY_RECIPES: CategoryRecipe[] = [
  {
    slug: "menziller",
    label: "Mənzil",
    titles: [
      "{yer} mərkəzində {ölçü} təmirli mənzil",
      "{yer}-də geniş {ölçü} mənzil — açıq şəhər mənzərəsi",
      "{yer} yaşayış massivində rahat {ölçü} mənzil",
      "{yer}-də metroya yaxın {ölçü} mənzil",
    ],
    leads: [
      "Şəhərin mərkəzinə on dəqiqəlik məsafədə, gündəlik həyatın hər detalı düşünülmüş mənzil.",
      "İşıqlı otaqlar, hündür tavan və səliqəli planlaşdırma — köçüb yaşamağa tam hazır.",
      "Sakit həyət, işlək infrastruktur və rahat nəqliyyat əlçatanlığı bir arada.",
      "Ailəniz üçün düşünülmüş, hər kvadratmetri işlək mənzil təklifi.",
    ],
    selling: [
      "Mətbəx və qonaq otağı vahid, işıqlı məkan kimi həll olunub.",
      "Pəncərələr həyətə baxır — küçə səsi minimuma endirilib.",
      "Binada lift, videomüşahidə və 24/7 mühafizə xidməti var.",
      "Yaxınlıqda məktəb, uşaq bağçası, market və aptek yerləşir.",
      "Sənədlər tam qaydasındadır, əməliyyat bir gün ərzində rəsmiləşdirilir.",
      "İpoteka və daxili taksit variantları üçün dəstək göstərilir.",
      "Mebel və məişət texnikası qiymətə daxildir.",
      "İstilik sistemi kombi ilə fərdi idarə olunur.",
    ],
    rentShare: 7,
    salePrice: [95000, 480000],
    rentPrice: [650, 3200],
    area: [52, 185],
    landArea: null,
    rooms: [1, 5],
    floors: [1, 18],
    features: ["lift", "kombi", "kondisioner", "mebel", "parkinq", "internet", "domofon", "esyali", "pvc-pencere", "kabel-tv"],
    renovations: ["RENOVATED", "DESIGNER", "COSMETIC", "NEW_BUILDING"],
    documents: ["TITLE_DEED", "CONTRACT"],
    newBuildingShare: 0.55,
    photos: [
      "photo-1545324418-cc1a3fa10c00",
      "photo-1502672260266-1c1ef2d93688",
      "photo-1522708323590-d24dbb6b0267",
      "photo-1493809842364-78817add7ffb",
      "photo-1560448204-e02f11c3d0e2",
      "photo-1484154218962-a197022b5858",
    ],
  },
  {
    slug: "yeni-tikili",
    label: "Yeni tikili",
    titles: [
      "{yer}-də yeni tikilidə {ölçü} mənzil — istismara verilib",
      "{yer} premium kompleksində {ölçü} mənzil",
      "{yer}-də A-klas binada {ölçü} mənzil",
      "Yeni tikili {yer}: {ölçü} mənzil, çıxarışlı",
    ],
    leads: [
      "İstismara verilmiş yeni binada, çıxarışı hazır mənzil — sənəd gözləmək lazım deyil.",
      "Müasir memarlıq, enerji səmərəli fasad və genişləndirilmiş liftlər.",
      "Qapalı həyət, uşaq meydançası və yeraltı parkinq kompleksin daxilindədir.",
      "Bakının sürətlə inkişaf edən yaşayış zonasında yeni nəsil bina.",
    ],
    selling: [
      "Binada iki sürətli lift və generator dəstəyi mövcuddur.",
      "Yeraltı parkinqdə mənzilə ayrılmış yer var.",
      "Fasad enerji səmərəli materiallarla üzlənib, istilik itkisi azdır.",
      "Mərtəbə planı sərbəstdir — dizayn layihəsini özünüz qura bilərsiniz.",
      "Çıxarış hazırdır, ipoteka üçün bank tərəfindən qəbul edilir.",
      "Qapalı ərazi, şlaqbaum və 24 saat mühafizə xidməti işləyir.",
      "Kommunal xətlər tam çəkilib və qoşulub.",
    ],
    rentShare: 5,
    salePrice: [130000, 620000],
    rentPrice: [900, 4200],
    area: [64, 210],
    landArea: null,
    rooms: [1, 5],
    floors: [2, 24],
    features: ["lift", "parkinq", "muhafize", "qapali-erazi", "kamera", "merkezi-istilik", "domofon", "internet", "hazir-ipoteka", "avtodayanacaq"],
    renovations: ["NEW_BUILDING", "DESIGNER", "RENOVATED"],
    documents: ["TITLE_DEED"],
    newBuildingShare: 1,
    photos: [
      "photo-1512917774080-9991f1c4c750",
      "photo-1486406146926-c627a92ad1ab",
      "photo-1497366754035-f200968a6e72",
      "photo-1511452885600-a3d2c9148a31",
      "photo-1460317442991-0ec209397118",
      "photo-1449844908441-8829872d2607",
    ],
  },
  {
    slug: "kohne-tikili",
    label: "Köhnə tikili",
    titles: [
      "{yer}-də köhnə fondda {ölçü} mənzil — sərfəli qiymət",
      "{yer} mərkəzi, {ölçü} mənzil, kupçalı",
      "{yer}-də «Stalin layihəsi» {ölçü} mənzil",
      "{yer}-də investisiya üçün {ölçü} mənzil",
    ],
    leads: [
      "Şəhərin köklü hissəsində, qalın divarlı və hündür tavanlı klassik mənzil.",
      "Sənədləri tam qaydasında olan, dərhal əməliyyat üçün hazır təklif.",
      "Təmirdən sonra dəyəri əhəmiyyətli artacaq investisiya obyekti.",
      "İnfrastrukturu illərlə formalaşmış rayonda sabit seçim.",
    ],
    selling: [
      "Tavan hündürlüyü 3 metrdən çoxdur — məkan çox işıqlıdır.",
      "Kupça hazırdır, notariat əməliyyatı üçün maneə yoxdur.",
      "Binanın bütün kommunikasiyaları yenilənib.",
      "Metro və avtobus dayanacağı piyada məsafədədir.",
      "Təmir potensialı yüksəkdir, planlaşdırma dəyişdirilə bilər.",
      "Həyət sakit və yaşıllıqlıdır, avtomobil üçün yer var.",
    ],
    rentShare: 8,
    salePrice: [72000, 260000],
    rentPrice: [450, 1600],
    area: [45, 140],
    landArea: null,
    rooms: [1, 4],
    floors: [1, 9],
    features: ["qaz", "su", "isiq", "telefon", "balkon", "kombi", "esyali", "kabel-tv"],
    renovations: ["COSMETIC", "UNRENOVATED", "RENOVATED"],
    documents: ["TITLE_DEED", "CONTRACT", "POWER_OF_ATTORNEY"],
    newBuildingShare: 0,
    photos: [
      "photo-1502005229762-cf1b2da7c5d6",
      "photo-1556909212-d5b604d0c90d",
      "photo-1567767292278-a4f21aa2d36e",
      "photo-1554995207-c18c203602cb",
      "photo-1505873242700-f289a29e1e0f",
      "photo-1513694203232-719a280e022f",
    ],
  },
  {
    slug: "heyet-evleri",
    label: "Həyət evi",
    titles: [
      "{yer}-də {ölçü} həyət evi — geniş sahə",
      "{yer} qəsəbəsində müstəqil {ölçü} ev",
      "{yer}-də bağçalı {ölçü} həyət evi",
      "{yer}: ailə üçün {ölçü} həyət evi",
    ],
    leads: [
      "Öz həyətiniz, öz qaydalarınız — şəhərin səsindən uzaq müstəqil yaşayış.",
      "Bağça, mangal zonası və avtomobil üçün geniş yer bir arada.",
      "İki mərtəbəli, işıqlı və hər otağı düşünülmüş ailə evi.",
      "Qonşuluqla sıxlıq yoxdur; ərazi tam hasarlanıb.",
    ],
    selling: [
      "Həyətdə meyvə ağacları və landşaft işi görülüb.",
      "Mangal zonası və yay mətbəxi hazırdır.",
      "İki avtomobil üçün örtülü dayanacaq var.",
      "Su, qaz və işıq xətləri fərdi sayğaclarla qoşulub.",
      "Ərazi hündür hasarla əhatələnib, giriş qapısı avtomatikdir.",
      "Evin sənədi çıxarışlıdır, əməliyyat rahat aparılır.",
      "İstiliksistemi kombi ilə fərdi idarə olunur.",
    ],
    rentShare: 5,
    salePrice: [140000, 850000],
    rentPrice: [900, 5500],
    area: [120, 420],
    landArea: [3, 18],
    rooms: [3, 7],
    floors: null,
    features: ["heyet", "bagca", "qaraj", "mangal", "kombi", "qapali-erazi", "kamera", "parkinq", "su", "qaz"],
    renovations: ["RENOVATED", "DESIGNER", "COSMETIC"],
    documents: ["TITLE_DEED", "MUNICIPAL", "CONTRACT"],
    newBuildingShare: 0.3,
    photos: [
      "photo-1570129477492-45c003edd2be",
      "photo-1568605114967-8130f3a36994",
      "photo-1512917774080-9991f1c4c750",
      "photo-1580587771525-78b9dba3b914",
      "photo-1449844908441-8829872d2607",
      "photo-1523217582562-09d0def993a6",
    ],
  },
  {
    slug: "villalar",
    label: "Villa",
    titles: [
      "{yer}-də hovuzlu {ölçü} villa",
      "{yer} sahil zonasında premium {ölçü} villa",
      "{yer}-də dizayner təmirli {ölçü} villa",
      "Ekskluziv təklif: {yer}-də {ölçü} villa",
    ],
    leads: [
      "Hovuz, landşaft və dənizə çıxış — istirahətin bütün elementləri bir ünvanda.",
      "Dizayner layihəsi üzrə tikilmiş, hər detalı fərdi seçilmiş villa.",
      "Qapalı villa şəhərciyində, mühafizəli ərazidə premium obyekt.",
      "Panoram pəncərələr, geniş terras və açıq mənzərə.",
    ],
    selling: [
      "Açıq hovuz və şezlonq zonası yay mövsümünə hazırdır.",
      "Sauna və hamam kompleksi evin daxilindədir.",
      "Terrasdan dəniz mənzərəsi açılır.",
      "Ərazidə mühafizə, videomüşahidə və avtomatik giriş sistemi var.",
      "Mebel və texnika İtaliya brendlərindəndir, qiymətə daxildir.",
      "Ağıllı ev sistemi işıq, istilik və təhlükəsizliyi bir mərkəzdən idarə edir.",
      "Qonaq evi və üç avtomobillik qaraj ayrıca tikilib.",
    ],
    rentShare: 4,
    salePrice: [420000, 3200000],
    rentPrice: [2500, 18000],
    area: [240, 900],
    landArea: [6, 40],
    rooms: [4, 9],
    floors: null,
    features: ["hovuz", "sauna", "bagca", "qaraj", "muhafize", "kamera", "deniz-menzeresi", "mangal", "qapali-erazi", "esyali", "kamin"],
    renovations: ["DESIGNER", "RENOVATED", "NEW_BUILDING"],
    documents: ["TITLE_DEED"],
    newBuildingShare: 0.6,
    photos: [
      "photo-1600596542815-ffad4c1539a9",
      "photo-1613490493576-7fde63acd811",
      "photo-1600585154340-be6161a56a0c",
      "photo-1600607687939-ce8a6c25118c",
      "photo-1512917774080-9991f1c4c750",
      "photo-1580587771525-78b9dba3b914",
    ],
  },
  {
    slug: "bag-evleri",
    label: "Bağ evi",
    titles: [
      "{yer}-də {ölçü} bağ evi — həftəsonu üçün ideal",
      "{yer} bağ massivində {ölçü} ev",
      "{yer}-də meyvə bağı ilə {ölçü} bağ evi",
      "{yer}: sakit zonada {ölçü} bağ evi",
    ],
    leads: [
      "Şəhər həyatından qısa fasilə üçün hazır, təmiz havada bağ evi.",
      "Meyvə ağacları, üzümlük və mangal zonası olan səliqəli sahə.",
      "Yay aylarını rahat keçirmək üçün lazım olan hər şey yerindədir.",
      "Bağ massivinin sakit hissəsində, əsas yola yaxın obyekt.",
    ],
    selling: [
      "Sahədə meyvə ağacları və üzüm talvarı var.",
      "Su quyusu və nasos sistemi quraşdırılıb.",
      "Mangal zonası və açıq istirahət terrası hazırdır.",
      "Ərazi hasarlanıb, giriş qapısı dəmirdəndir.",
      "Yay mətbəxi ayrıca tikilib.",
      "Əsas yola çıxış asfaltdır, bütün il əlçatandır.",
    ],
    rentShare: 6,
    salePrice: [38000, 240000],
    rentPrice: [300, 2200],
    area: [60, 220],
    landArea: [4, 20],
    rooms: [2, 5],
    floors: null,
    features: ["bag-sahesi", "heyet", "mangal", "su", "isiq", "bagca", "qaz", "bagli-erazi"],
    renovations: ["COSMETIC", "RENOVATED", "UNRENOVATED"],
    documents: ["MUNICIPAL", "TITLE_DEED", "DECREE"],
    newBuildingShare: 0.2,
    photos: [
      "photo-1512917774080-9991f1c4c750",
      "photo-1449844908441-8829872d2607",
      "photo-1470770841072-f978cf4d019e",
      "photo-1441974231531-c6227db76b6e",
      "photo-1500382017468-9049fed747ef",
      "photo-1523217582562-09d0def993a6",
    ],
  },
  {
    slug: "torpaq",
    label: "Torpaq sahəsi",
    titles: [
      "{yer}-də {ölçü} torpaq sahəsi — tikintiyə uyğun",
      "{yer} ərazisində {ölçü} sahə, yola yaxın",
      "{yer}-də investisiya üçün {ölçü} torpaq",
      "{yer}: kommunikasiyalı {ölçü} torpaq sahəsi",
    ],
    leads: [
      "Tikinti üçün hazır, sənədləri qaydasında olan torpaq sahəsi.",
      "Əsas yola çıxışı olan, kommunikasiya xətləri yaxınlıqdan keçən sahə.",
      "Sürətlə inkişaf edən zonada uzunmüddətli investisiya imkanı.",
      "Sahənin relyefi düzdür, əlavə hamarlama işi tələb etmir.",
    ],
    selling: [
      "Sahənin sənədi qaydasındadır, ölçü planı hazırdır.",
      "Su, işıq və qaz xətləri sərhəddən keçir.",
      "Əsas magistrala çıxış beş dəqiqədən azdır.",
      "Ərazidə fəal tikinti gedir — dəyər artımı gözlənilir.",
      "Sahə düzənlikdir, tikintiyə dərhal başlamaq mümkündür.",
      "Bölünmə imkanı var, hissə-hissə də satıla bilər.",
    ],
    rentShare: 3,
    salePrice: [18000, 420000],
    rentPrice: [200, 2600],
    area: null,
    landArea: [3, 120],
    rooms: null,
    floors: null,
    features: ["su", "isiq", "qaz", "kanalizasiya", "bagli-erazi"],
    renovations: [],
    documents: ["MUNICIPAL", "TITLE_DEED", "DECREE"],
    newBuildingShare: 0,
    photos: [
      "photo-1500382017468-9049fed747ef",
      "photo-1416879595882-3373a0480b5b",
      "photo-1500534314209-a25ddb2bd429",
      "photo-1470770841072-f978cf4d019e",
      "photo-1441974231531-c6227db76b6e",
      "photo-1464822759023-fed622ff2c3b",
    ],
  },
  {
    slug: "obyektler",
    label: "Obyekt",
    titles: [
      "{yer}-də {ölçü} kommersiya obyekti — işlək küçə",
      "{yer} mərkəzində {ölçü} ticarət sahəsi",
      "{yer}-də birinci xətdə {ölçü} obyekt",
      "{yer}: hazır biznes üçün {ölçü} obyekt",
    ],
    leads: [
      "Piyada axını yüksək olan küçədə, vitrini geniş kommersiya sahəsi.",
      "Market, aptek, kafe və ya salon üçün uyğun planlaşdırma.",
      "Birinci xətt, ayrıca giriş və yükləmə imkanı.",
      "İşlək ticarət zonasında hazır obyekt təklifi.",
    ],
    selling: [
      "Vitrin küçəyə baxır, reklam üçün geniş səth var.",
      "Ayrıca giriş və müstəqil kommunal sayğaclar mövcuddur.",
      "Elektrik gücü artırılıb, ağır avadanlıq üçün uyğundur.",
      "Yükləmə-boşaltma üçün arxa giriş var.",
      "Ventilyasiya və kondisioner sistemi quraşdırılıb.",
      "Sənəd qeyri-yaşayış çıxarışıdır, icarəyə vermək üçün maneə yoxdur.",
    ],
    rentShare: 11,
    salePrice: [95000, 1400000],
    rentPrice: [800, 12000],
    area: [40, 620],
    landArea: null,
    rooms: null,
    floors: [1, 4],
    features: ["kondisioner", "kamera", "siqnalizasiya", "internet", "su", "isiq", "kanalizasiya", "avtodayanacaq"],
    renovations: ["RENOVATED", "COSMETIC", "UNRENOVATED"],
    documents: ["EXTRACT_COMMERCIAL", "CONTRACT", "TITLE_DEED"],
    newBuildingShare: 0.4,
    photos: [
      "photo-1441986300917-64674bd600d8",
      "photo-1567521464027-f127ff144326",
      "photo-1604719312566-8912e9227c6a",
      "photo-1582037928769-181f2644ecb7",
      "photo-1555529669-e69e7aa0ba9a",
      "photo-1560472354-b33ff0c44a43",
    ],
  },
  {
    slug: "ofisler",
    label: "Ofis",
    titles: [
      "{yer}-də biznes mərkəzində {ölçü} ofis",
      "{yer} mərkəzi: {ölçü} ofis sahəsi",
      "{yer}-də açıq planlı {ölçü} ofis",
      "{yer}: komanda üçün {ölçü} ofis",
    ],
    leads: [
      "Biznes mərkəzində, resepşn və konfrans zalı dəstəyi ilə ofis sahəsi.",
      "Açıq plan, işıqlı pəncərələr və hazır şəbəkə infrastrukturu.",
      "Şəhərin işgüzar zonasında, nəqliyyat qovşağına yaxın.",
      "Komandanızın böyüməsinə uyğunlaşan çevik planlaşdırma.",
    ],
    selling: [
      "Sahə açıq plandır, arakəsmələrlə istənilən formada bölünə bilər.",
      "Binada resepşn, lift və 24 saat mühafizə var.",
      "Fiber internet və server otağı üçün hazırlıq mövcuddur.",
      "Ziyarətçilər üçün ayrılmış parkinq yerləri var.",
      "Konfrans zalı və görüş otaqları binanın ümumi istifadəsindədir.",
      "Kondisioner və ventilyasiya mərkəzi sistemlə idarə olunur.",
    ],
    rentShare: 12,
    salePrice: [110000, 1800000],
    rentPrice: [700, 15000],
    area: [35, 780],
    landArea: null,
    rooms: null,
    floors: [1, 22],
    features: ["lift", "internet", "kondisioner", "muhafize", "parkinq", "kamera", "merkezi-istilik", "avtodayanacaq"],
    renovations: ["RENOVATED", "DESIGNER", "NEW_BUILDING"],
    documents: ["EXTRACT_COMMERCIAL", "CONTRACT"],
    newBuildingShare: 0.65,
    photos: [
      "photo-1497366216548-37526070297c",
      "photo-1497366811353-6870744d04b2",
      "photo-1504384308090-c894fdcc538d",
      "photo-1524758631624-e2822e304c36",
      "photo-1552664730-d307ca884978",
      "photo-1517502884422-41eaead166d4",
    ],
  },
  {
    slug: "qarajlar",
    label: "Qaraj",
    titles: [
      "{yer}-də {ölçü} qaraj — kupçalı",
      "{yer} yaşayış massivində {ölçü} qaraj",
      "{yer}-də anbar kimi də uyğun {ölçü} qaraj",
      "{yer}: mühafizəli ərazidə {ölçü} qaraj",
    ],
    leads: [
      "Avtomobiliniz üçün təhlükəsiz, quru və işıqlı qaraj sahəsi.",
      "Anbar və ya kiçik emalatxana kimi də istifadəyə uyğundur.",
      "Mühafizəli qaraj kooperativində, giriş nəzarətli ərazi.",
      "Yaşayış binasına yaxın, gündəlik istifadə üçün rahat.",
    ],
    selling: [
      "Qaraj quru və nəmsizdir, döşəmə betonlanıb.",
      "İşıq xətti çəkilib, ayrıca sayğac var.",
      "Qapı metaldır, əlavə kilid sistemi quraşdırılıb.",
      "Kooperativ ərazisi mühafizə olunur.",
      "Yeraltı çuxur texniki baxış üçün hazırdır.",
      "Sənədi qaydasındadır, satış rahat rəsmiləşir.",
    ],
    rentShare: 9,
    salePrice: [9000, 68000],
    rentPrice: [90, 550],
    area: [16, 60],
    landArea: null,
    rooms: null,
    floors: null,
    features: ["isiq", "muhafize", "kamera", "su"],
    renovations: ["COSMETIC", "UNRENOVATED"],
    documents: ["TITLE_DEED", "MUNICIPAL", "CONTRACT"],
    newBuildingShare: 0.15,
    photos: [
      "photo-1486006920555-c77dcf18193c",
      "photo-1558618666-fcd25c85cd64",
      "photo-1517672651691-24622a91b550",
      "photo-1520340356584-f9917d1eea6f",
      "photo-1449965408869-eaa3f722e40d",
      "photo-1471479917193-f00955256257",
    ],
  },
  {
    slug: "mini-otel",
    label: "Mini otel",
    titles: [
      "{yer}-də {ölçü} mini otel — hazır biznes",
      "{yer} turizm zonasında {ölçü} xostel",
      "{yer}-də işləyən {ölçü} mini otel",
      "{yer}: gəlirli {ölçü} qonaq evi",
    ],
    leads: [
      "Müştəri bazası formalaşmış, işləyən vəziyyətdə hazır otel biznesi.",
      "Turist axını yüksək olan zonada, bütün otaqları təmirli obyekt.",
      "Onlayn rezervasiya platformalarında profil və reytinq mövcuddur.",
      "Mebel, texnika və işçi heyəti ilə birlikdə təhvil verilir.",
    ],
    selling: [
      "Bütün otaqlar müstəqil sanitar qovşaqla təchiz olunub.",
      "Resepşn, ümumi mətbəx və istirahət zonası hazırdır.",
      "Rezervasiya platformalarında yüksək reytinq və rəylər var.",
      "Kondisioner, Wi-Fi və televiziya bütün otaqlarda mövcuddur.",
      "Mebel və texnika qiymətə daxildir.",
      "İllik doldurulma göstəricisi sabitdir.",
    ],
    rentShare: 7,
    salePrice: [280000, 2400000],
    rentPrice: [2200, 16000],
    area: [180, 1200],
    landArea: null,
    rooms: [6, 24],
    floors: [1, 6],
    features: ["internet", "kondisioner", "esyali", "mebel", "kamera", "muhafize", "parkinq", "lift"],
    renovations: ["RENOVATED", "DESIGNER"],
    documents: ["EXTRACT_COMMERCIAL", "TITLE_DEED"],
    newBuildingShare: 0.45,
    photos: [
      "photo-1566073771259-6a8506099945",
      "photo-1551882547-ff40c63fe5fa",
      "photo-1520250497591-112f2f40a3f4",
      "photo-1611892440504-42a792e24d32",
      "photo-1445019980597-93fa8acb246c",
      "photo-1590490360182-c33d57733427",
    ],
  },
  {
    slug: "istirahet-merkezleri",
    label: "İstirahət mərkəzi",
    titles: [
      "{yer}-də {ölçü} istirahət mərkəzi — hovuzlu",
      "{yer} təbiət qoynunda {ölçü} istirahət kompleksi",
      "{yer}-də tədbirlər üçün {ölçü} istirahət mərkəzi",
      "{yer}: hazır biznes — {ölçü} istirahət zonası",
    ],
    leads: [
      "Hovuz, kotteclər və tədbir sahəsi ilə tam işlək istirahət kompleksi.",
      "Təbiətin içində, şəhərdən qısa məsafədə hazır turizm obyekti.",
      "Toy, korporativ tədbir və ailə istirahəti üçün uyğunlaşdırılıb.",
      "Bütün infrastruktur qurulub — açılışa hazır vəziyyətdə.",
    ],
    selling: [
      "Açıq hovuz və uşaq hovuzu ayrıca tikilib.",
      "Ərazidə kotteclər, mangal zonaları və talvarlar var.",
      "Tədbir zalı və açıq səhnə mövcuddur.",
      "Avtomobil dayanacağı 40-dan çox yer üçün nəzərdə tutulub.",
      "Su quyusu, generator və müstəqil kommunikasiyalar quraşdırılıb.",
      "Ərazi tam hasarlanıb, mühafizə xidməti işləyir.",
    ],
    rentShare: 5,
    salePrice: [350000, 4200000],
    rentPrice: [2800, 24000],
    area: [400, 2600],
    landArea: [10, 150],
    rooms: [5, 30],
    floors: null,
    features: ["hovuz", "mangal", "bagca", "muhafize", "kamera", "parkinq", "qapali-erazi", "su", "sauna"],
    renovations: ["RENOVATED", "DESIGNER"],
    documents: ["EXTRACT_COMMERCIAL", "TITLE_DEED", "MUNICIPAL"],
    newBuildingShare: 0.35,
    photos: [
      "photo-1571003123894-1f0594d2b5d9",
      "photo-1540541338287-41700207dee6",
      "photo-1596178065887-1198b6148b2b",
      "photo-1587061949409-02df41d5e562",
      "photo-1470770841072-f978cf4d019e",
      "photo-1600585154340-be6161a56a0c",
    ],
  },
  {
    slug: "konteyner-evler",
    label: "Konteyner ev",
    titles: [
      "{yer}-də {ölçü} konteyner ev — hazır quraşdırma",
      "{yer} üçün {ölçü} modul konteyner ev",
      "{yer}-də ofis kimi də uyğun {ölçü} konteyner",
      "{yer}: sürətli həll — {ölçü} konteyner ev",
    ],
    leads: [
      "Bir gündə quraşdırılan, tam təmirli və istifadəyə hazır modul ev.",
      "Bağ sahəsi, tikinti meydançası və ya ofis üçün çevik həll.",
      "İstilik izolyasiyası gücləndirilib, il boyu yaşamağa uyğundur.",
      "Nəqliyyatla istənilən əraziyə daşına bilər.",
    ],
    selling: [
      "İstilik və səs izolyasiyası sənaye standartındadır.",
      "Sanitar qovşaq və mətbəx guşəsi daxildir.",
      "Elektrik və su qoşulması üçün hazır çıxışlar var.",
      "Quraşdırma bir iş günü ərzində tamamlanır.",
      "Konstruksiya daşına bilər — ərazi dəyişikliyi problem deyil.",
      "Zəmanət və texniki dəstək təmin olunur.",
    ],
    rentShare: 8,
    salePrice: [12000, 78000],
    rentPrice: [180, 1100],
    area: [18, 96],
    landArea: null,
    rooms: [1, 4],
    floors: null,
    features: ["isiq", "su", "kondisioner", "internet", "mebel", "esyali"],
    renovations: ["NEW_BUILDING", "RENOVATED"],
    documents: ["CONTRACT", "NONE"],
    newBuildingShare: 0.9,
    photos: [
      "photo-1523217582562-09d0def993a6",
      "photo-1520637836862-4d197d17c50a",
      "photo-1416331108676-a22ccb276e35",
      "photo-1502005097973-6a7082348e28",
      "photo-1449844908441-8829872d2607",
      "photo-1512917774080-9991f1c4c750",
    ],
  },
  {
    slug: "a-frame-evler",
    label: "A-frame ev",
    titles: [
      "{yer}-də {ölçü} A-frame ev — mənzərəli ərazi",
      "{yer} dağ zonasında {ölçü} A-frame",
      "{yer}-də turizm üçün {ölçü} A-frame ev",
      "{yer}: dizayn həlli — {ölçü} A-frame ev",
    ],
    leads: [
      "Panoram pəncərələri təbiətə açılan, müasir A-frame memarlığı.",
      "Qısamüddətli icarə biznesi üçün yüksək tələbatlı format.",
      "Ağac konstruksiya, isti interyer və geniş terras.",
      "Dağ və meşə mənzərəsi ilə üzbəüz istirahət evi.",
    ],
    selling: [
      "Panoram pəncərələr döşəmədən tavana qədərdir.",
      "Terras və açıq mangal zonası hazırdır.",
      "Kamin qonaq otağının mərkəzindədir.",
      "İnteryer tam mebellidir, açar təhvil verilir.",
      "Qısamüddətli icarə platformalarında yüksək tələbat var.",
      "İstilik izolyasiyası qışda da rahat yaşamağa imkan verir.",
    ],
    rentShare: 8,
    salePrice: [45000, 320000],
    rentPrice: [400, 2800],
    area: [45, 180],
    landArea: [3, 25],
    rooms: [2, 5],
    floors: null,
    features: ["kamin", "mangal", "heyet", "esyali", "internet", "bagca", "su", "isiq"],
    renovations: ["NEW_BUILDING", "DESIGNER"],
    documents: ["MUNICIPAL", "TITLE_DEED", "CONTRACT"],
    newBuildingShare: 0.85,
    photos: [
      "photo-1449158743715-0a90ebb6d2d8",
      "photo-1470770841072-f978cf4d019e",
      "photo-1502786129293-79981df4e689",
      "photo-1520637736862-4d197d17c50a",
      "photo-1441974231531-c6227db76b6e",
      "photo-1523217582562-09d0def993a6",
    ],
  },
  {
    slug: "xarici-emlak",
    label: "Xarici əmlak",
    titles: [
      "{yer} üzrə {ölçü} xarici əmlak təklifi",
      "Xaricdə investisiya: {ölçü} mənzil",
      "{yer} bazarında {ölçü} əmlak — sənəd dəstəyi ilə",
      "Xarici əmlak: {ölçü} obyekt, tam müşayiət",
    ],
    leads: [
      "Xarici bazarda investisiya və yaşayış icazəsi imkanı verən əmlak təklifi.",
      "Alqı-satqı prosesi hüquqi müşayiətlə, uzaqdan da aparıla bilər.",
      "İcarə gəliri potensialı hesablanmış, sənədləri yoxlanılmış obyekt.",
      "Bütün mərhələlərdə tərcümə və notariat dəstəyi göstərilir.",
    ],
    selling: [
      "Alqı-satqı prosesi tam hüquqi müşayiətlə aparılır.",
      "İcarə gəliri potensialı əvvəlcədən hesablanıb.",
      "Sənədlərin tərcüməsi və notariat təsdiqi xidmətə daxildir.",
      "Obyektin idarəçiliyi yerli tərəfdaş şirkət tərəfindən aparıla bilər.",
      "Uzaqdan əməliyyat üçün etibarnamə sxemi hazırdır.",
      "Kompleksdə hovuz, fitnes və mühafizə xidməti var.",
    ],
    rentShare: 6,
    salePrice: [60000, 1200000],
    rentPrice: [500, 6500],
    area: [45, 320],
    landArea: null,
    rooms: [1, 6],
    floors: [1, 20],
    features: ["hovuz", "lift", "muhafize", "parkinq", "kondisioner", "esyali", "deniz-menzeresi", "internet"],
    renovations: ["NEW_BUILDING", "DESIGNER", "RENOVATED"],
    documents: ["CONTRACT", "TITLE_DEED"],
    newBuildingShare: 0.7,
    photos: [
      "photo-1512453979798-5ea266f8880c",
      "photo-1524231757912-21f4fe3a7200",
      "photo-1493246507139-91e8fad9978e",
      "photo-1502602898657-3e91760cbb34",
      "photo-1499856871958-5b9627545d1a",
      "photo-1526772662000-3f88f10405ff",
    ],
  },
];

/** Xarici əmlak kateqoriyası üçün yer adları — Bakı rayonları uyğun gəlmir. */
export const FOREIGN_PLACES = [
  "Dubay",
  "İstanbul",
  "Antalya",
  "Tbilisi",
  "Batumi",
  "Alanya",
  "Şarja",
  "Bodrum",
];

// ---------------------------------------------------------------------------
// YAŞAYIŞ KOMPLEKSLƏRİ
// ---------------------------------------------------------------------------

export const DEMO_PROJECTS = [
  {
    slug: "luxe-park-residence",
    name: "Luxe Park Residence",
    city: "baki",
    district: "Səbail",
    type: "RESIDENTIAL",
    status: "ONGOING",
    summary: "Dənizkənarı bulvara on dəqiqəlik məsafədə, qapalı həyətli premium yaşayış kompleksi.",
    floors: 22,
    units: 248,
    area: 34000,
    year: 2027,
    highlights: ["Qapalı həyət və landşaft", "Yeraltı parkinq", "24/7 mühafizə", "Fitnes və SPA zonası"],
    photo: "photo-1545324418-cc1a3fa10c00",
  },
  {
    slug: "white-city-towers",
    name: "White City Towers",
    city: "baki",
    district: "Xətai",
    type: "MIXED",
    status: "ONGOING",
    summary: "Yaşayış, ofis və ticarət funksiyalarını birləşdirən üç qüllədən ibarət kompleks.",
    floors: 28,
    units: 410,
    area: 62000,
    year: 2028,
    highlights: ["Üç qüllə", "Ticarət qalereyası", "Ofis mərtəbələri", "Panoram liftlər"],
    photo: "photo-1486406146926-c627a92ad1ab",
  },
  {
    slug: "yasamal-green-park",
    name: "Yasamal Green Park",
    city: "baki",
    district: "Yasamal",
    type: "RESIDENTIAL",
    status: "COMPLETED",
    summary: "Yaşıllıq sahəsi geniş saxlanılmış, ailəyönümlü yaşayış kompleksi.",
    floors: 16,
    units: 186,
    area: 21000,
    year: 2025,
    highlights: ["Uşaq meydançaları", "Yaşıl park zonası", "Məktəb və bağça yaxınlığı", "Velosiped yolları"],
    photo: "photo-1512917774080-9991f1c4c750",
  },
  {
    slug: "caspian-sea-villas",
    name: "Caspian Sea Villas",
    city: "baki",
    district: "Xəzər",
    type: "VILLA",
    status: "ONGOING",
    summary: "Dənizə birbaşa çıxışı olan, fərdi hovuzlu villa şəhərciyi.",
    floors: 3,
    units: 42,
    area: 48000,
    year: 2027,
    highlights: ["Şəxsi çimərlik", "Fərdi hovuzlar", "Qapalı şəhərcik", "Klub evi"],
    photo: "photo-1600596542815-ffad4c1539a9",
  },
  {
    slug: "narimanov-business-center",
    name: "Nərimanov Business Center",
    city: "baki",
    district: "Nərimanov",
    type: "COMMERCIAL",
    status: "COMPLETED",
    summary: "A-klas ofis mərtəbələri və konfrans infrastrukturu olan biznes mərkəzi.",
    floors: 19,
    units: 96,
    area: 28000,
    year: 2024,
    highlights: ["A-klas ofislər", "Konfrans mərkəzi", "Yeraltı parkinq", "Fiber internet"],
    photo: "photo-1497366216548-37526070297c",
  },
  {
    slug: "khirdalan-comfort-city",
    name: "Xırdalan Comfort City",
    city: "xirdalan",
    district: null,
    type: "RESIDENTIAL",
    status: "ONGOING",
    summary: "Münasib qiymətli, taksit imkanı geniş olan yaşayış massivi.",
    floors: 12,
    units: 320,
    area: 39000,
    year: 2027,
    highlights: ["Faizsiz daxili taksit", "Market və aptek", "Qapalı həyət", "Avtobus marşrutu"],
    photo: "photo-1460317442991-0ec209397118",
  },
  {
    slug: "sumqayit-marine-residence",
    name: "Sumqayıt Marine Residence",
    city: "sumqayit",
    district: null,
    type: "RESIDENTIAL",
    status: "PLANNED",
    summary: "Sahil xəttinə yaxın, dəniz mənzərəli mənzillərdən ibarət yeni layihə.",
    floors: 14,
    units: 168,
    area: 23000,
    year: 2029,
    highlights: ["Dəniz mənzərəsi", "Sahil promenadı", "Uşaq zonası", "Yeraltı parkinq"],
    photo: "photo-1502672260266-1c1ef2d93688",
  },
  {
    slug: "gabala-mountain-resort",
    name: "Qəbələ Mountain Resort",
    city: "qebele",
    district: null,
    type: "MIXED",
    status: "ONGOING",
    summary: "Dağ mənzərəli kotteclər və otel bloklarından ibarət turizm kompleksi.",
    floors: 5,
    units: 88,
    area: 56000,
    year: 2028,
    highlights: ["Dağ mənzərəsi", "Kotteclər", "SPA mərkəzi", "Xizək zonasına yaxınlıq"],
    photo: "photo-1449158743715-0a90ebb6d2d8",
  },
  {
    slug: "nasimi-central-plaza",
    name: "Nəsimi Central Plaza",
    city: "baki",
    district: "Nəsimi",
    type: "MIXED",
    status: "COMPLETED",
    summary: "Şəhərin işgüzar mərkəzində yaşayış və ticarət funksiyalı kompleks.",
    floors: 24,
    units: 214,
    area: 31000,
    year: 2023,
    highlights: ["Metro yaxınlığı", "Ticarət mərtəbələri", "Konsyerj xidməti", "Panoram terras"],
    photo: "photo-1522708323590-d24dbb6b0267",
  },
  {
    slug: "binagadi-family-quarter",
    name: "Binəqədi Family Quarter",
    city: "baki",
    district: "Binəqədi",
    type: "RESIDENTIAL",
    status: "ONGOING",
    summary: "Uşaqlı ailələr üçün planlaşdırılmış, geniş həyətli yaşayış kvartalı.",
    floors: 10,
    units: 260,
    area: 33000,
    year: 2027,
    highlights: ["Böyük daxili həyət", "İki uşaq meydançası", "Bağça binası", "İdman sahəsi"],
    photo: "photo-1493809842364-78817add7ffb",
  },
  {
    slug: "novkhani-beach-club",
    name: "Novxanı Beach Club Residence",
    city: "baki",
    district: "Novxanı",
    type: "VILLA",
    status: "PLANNED",
    summary: "Çimərlik klubu ilə birləşən mövsümi və daimi yaşayış üçün villa layihəsi.",
    floors: 2,
    units: 64,
    area: 41000,
    year: 2029,
    highlights: ["Çimərlik klubu", "Açıq hovuzlar", "Restoran zonası", "Qapalı ərazi"],
    photo: "photo-1613490493576-7fde63acd811",
  },
  {
    slug: "ganja-new-city",
    name: "Gəncə New City",
    city: "gence",
    district: null,
    type: "RESIDENTIAL",
    status: "ONGOING",
    summary: "Regionun ən iri yaşayış layihələrindən biri — mərhələli təhvil sxemi ilə.",
    floors: 12,
    units: 380,
    area: 52000,
    year: 2028,
    highlights: ["Mərhələli təhvil", "Məktəb və poliklinika", "Ticarət mərkəzi", "Park zonası"],
    photo: "photo-1497366754035-f200968a6e72",
  },
];

// ---------------------------------------------------------------------------
// AGENTLİKLƏR VƏ AGENTLƏR
// ---------------------------------------------------------------------------

export const DEMO_AGENCIES = [
  {
    slug: "demo-alfa-estate",
    name: "Alfa Estate (nümunə)",
    description: "Bakı üzrə yaşayış və kommersiya əmlakı ilə çalışan nümunə agentlik qeydi.",
    phone: "+994 12 000 00 11",
    address: "Bakı, Nəsimi rayonu",
    logo: "photo-1497366216548-37526070297c",
  },
  {
    slug: "demo-baku-premium",
    name: "Baku Premium Realty (nümunə)",
    description: "Premium seqment, villa və dənizkənarı obyektlər üzrə nümunə agentlik qeydi.",
    phone: "+994 12 000 00 22",
    address: "Bakı, Səbail rayonu",
    logo: "photo-1600596542815-ffad4c1539a9",
  },
  {
    slug: "demo-metro-invest",
    name: "Metro Invest (nümunə)",
    description: "Yeni tikili və investisiya obyektləri üzrə ixtisaslaşmış nümunə agentlik.",
    phone: "+994 12 000 00 33",
    address: "Bakı, Nərimanov rayonu",
    logo: "photo-1486406146926-c627a92ad1ab",
  },
  {
    slug: "demo-region-emlak",
    name: "Region Əmlak (nümunə)",
    description: "Sumqayıt, Xırdalan və Abşeron istiqaməti üzrə nümunə agentlik qeydi.",
    phone: "+994 12 000 00 44",
    address: "Sumqayıt, Mərkəz",
    logo: "photo-1460317442991-0ec209397118",
  },
  {
    slug: "demo-kaspi-house",
    name: "Kaspi House (nümunə)",
    description: "Kirayə və qısamüddətli icarə portfeli üzrə nümunə agentlik qeydi.",
    phone: "+994 12 000 00 55",
    address: "Bakı, Xətai rayonu",
    logo: "photo-1522708323590-d24dbb6b0267",
  },
  {
    slug: "demo-global-property",
    name: "Global Property AZ (nümunə)",
    description: "Xarici əmlak və investisiya proqramları üzrə nümunə agentlik qeydi.",
    phone: "+994 12 000 00 66",
    address: "Bakı, Yasamal rayonu",
    logo: "photo-1512453979798-5ea266f8880c",
  },
];

export const DEMO_AGENTS = [
  { slug: "demo-agent-aysel-memmedova", name: "Aysel Məmmədova", role: "Baş məsləhətçi", spec: "Yaşayış əmlakı", years: 9, agency: 0 },
  { slug: "demo-agent-rovshen-quliyev", name: "Rövşən Quliyev", role: "Satış meneceri", spec: "Yeni tikili", years: 6, agency: 2 },
  { slug: "demo-agent-nigar-hesenli", name: "Nigar Həsənli", role: "Kirayə üzrə mütəxəssis", spec: "Kirayə portfeli", years: 5, agency: 4 },
  { slug: "demo-agent-elvin-abbasov", name: "Elvin Abbasov", role: "Kommersiya üzrə broker", spec: "Ofis və obyekt", years: 11, agency: 0 },
  { slug: "demo-agent-leyla-kerimova", name: "Leyla Kərimova", role: "Premium seqment", spec: "Villa və malikanə", years: 8, agency: 1 },
  { slug: "demo-agent-tural-esgerov", name: "Tural Əsgərov", role: "İnvestisiya məsləhətçisi", spec: "İnvestisiya obyektləri", years: 7, agency: 2 },
  { slug: "demo-agent-gunel-sultanova", name: "Günel Sultanova", role: "Regional koordinator", spec: "Abşeron və regionlar", years: 4, agency: 3 },
  { slug: "demo-agent-kamran-ibrahimov", name: "Kamran İbrahimov", role: "Torpaq üzrə mütəxəssis", spec: "Torpaq sahələri", years: 12, agency: 3 },
  { slug: "demo-agent-sevinc-alieva", name: "Sevinc Əliyeva", role: "Müştəri münasibətləri", spec: "Ailə mənzilləri", years: 3, agency: 4 },
  { slug: "demo-agent-orxan-nesirov", name: "Orxan Nəsirov", role: "Xarici bazar üzrə broker", spec: "Xarici əmlak", years: 10, agency: 5 },
  { slug: "demo-agent-aygun-veliyeva", name: "Aygün Vəliyeva", role: "Hüquqi müşayiət", spec: "Sənəd və notariat", years: 6, agency: 5 },
  { slug: "demo-agent-samir-huseynov", name: "Samir Hüseynov", role: "Baş broker", spec: "Kommersiya obyektləri", years: 14, agency: 1 },
];

// ---------------------------------------------------------------------------
// TƏRƏFDAŞLAR
// ---------------------------------------------------------------------------

export const DEMO_PARTNERS = [
  { slug: "demo-partner-kaspian-development", name: "Kaspian Development (nümunə)", type: "DEVELOPER", desc: "Bakıda çoxmərtəbəli yaşayış kompleksləri tikən nümunə developer şirkəti.", city: "Bakı", photo: "photo-1486406146926-c627a92ad1ab", official: true, home: true },
  { slug: "demo-partner-atlas-insaat", name: "Atlas İnşaat (nümunə)", type: "CONSTRUCTION_COMPANY", desc: "Yaşayış və kommersiya obyektlərinin tikintisi üzrə nümunə podratçı.", city: "Bakı", photo: "photo-1541888946425-d81bb19240f5", official: true, home: true },
  { slug: "demo-partner-unibank-mortgage", name: "Nümunə Bank — İpoteka", type: "MORTGAGE", desc: "İpoteka kreditləri üzrə əməkdaşlıq edilən nümunə bank qeydi.", city: "Bakı", photo: "photo-1541354329998-f4d9a9f9297f", official: true, home: true },
  { slug: "demo-partner-sigorta-plus", name: "Sığorta Plus (nümunə)", type: "INSURANCE", desc: "Daşınmaz əmlakın icbari və könüllü sığortası üzrə nümunə tərəfdaş.", city: "Bakı", photo: "photo-1450101499163-c8848c66ca85", official: false, home: true },
  { slug: "demo-partner-notariat-hub", name: "Notariat Hub (nümunə)", type: "SERVICE_PROVIDER", desc: "Notariat və sənəd rəsmiləşdirilməsi üzrə nümunə xidmət tərəfdaşı.", city: "Bakı", photo: "photo-1450101499163-c8848c66ca85", official: false, home: false },
  { slug: "demo-partner-interyer-studio", name: "İnteryer Studio (nümunə)", type: "SERVICE_PROVIDER", desc: "Dizayn və təmir layihələri üzrə nümunə tərəfdaş studiya.", city: "Bakı", photo: "photo-1618221195710-dd6b41faaea6", official: false, home: true },
  { slug: "demo-partner-capital-invest", name: "Capital Invest (nümunə)", type: "INVESTMENT", desc: "Daşınmaz əmlak fondları və investisiya layihələri üzrə nümunə tərəfdaş.", city: "Bakı", photo: "photo-1554224155-6726b3ff858f", official: true, home: false },
  { slug: "demo-partner-proptech-az", name: "PropTech AZ (nümunə)", type: "TECHNOLOGY", desc: "Daşınmaz əmlak texnologiyaları üzrə nümunə texnoloji tərəfdaş.", city: "Bakı", photo: "photo-1517245386807-bb43f82c33c4", official: false, home: false },
  { slug: "demo-partner-emlak-media", name: "Əmlak Media (nümunə)", type: "MEDIA", desc: "Bazar analitikası və məzmun əməkdaşlığı üzrə nümunə media tərəfdaşı.", city: "Bakı", photo: "photo-1504711434969-e33886168f5c", official: false, home: false },
  { slug: "demo-partner-region-broker", name: "Region Broker (nümunə)", type: "BROKER", desc: "Regionlar üzrə brokerlik əməkdaşlığı edən nümunə tərəfdaş.", city: "Gəncə", photo: "photo-1560518883-ce09059eeffa", official: false, home: false },
  { slug: "demo-partner-koc-logistika", name: "Köç Logistika (nümunə)", type: "SERVICE_PROVIDER", desc: "Köçürülmə və daşınma xidmətləri üzrə nümunə tərəfdaş.", city: "Bakı", photo: "photo-1600585154340-be6161a56a0c", official: false, home: false },
  { slug: "demo-partner-strateji-tesekkul", name: "Strateji Təşəkkül (nümunə)", type: "STRATEGIC_PARTNER", desc: "Uzunmüddətli strateji əməkdaşlıq üzrə nümunə tərəfdaş qeydi.", city: "Bakı", photo: "photo-1552664730-d307ca884978", official: true, home: true },
];

// ---------------------------------------------------------------------------
// BLOQ
// ---------------------------------------------------------------------------

export const DEMO_POSTS = [
  { slug: "demo-baki-mensil-bazari-hesabat", title: "Bakı mənzil bazarı: rüblük nümunə hesabat", cat: "bazar-xeberleri", photo: "photo-1486406146926-c627a92ad1ab", lead: "Nümunə məlumatlarla hazırlanmış rüblük bazar icmalı — qiymət dinamikası, tələb və təklif balansı." },
  { slug: "demo-ilk-mensili-almaq", title: "İlk mənzili almaq: addım-addım nümunə bələdçi", cat: "meslehetler", photo: "photo-1560448204-e02f11c3d0e2", lead: "Büdcə planlaşdırmasından açar təhvilinə qədər prosesin nümunə izahı." },
  { slug: "demo-ipoteka-hesablamasi", title: "İpoteka hesablaması: nəyi əvvəlcədən bilmək lazımdır", cat: "meslehetler", photo: "photo-1554224155-6726b3ff858f", lead: "İlkin ödəniş, faiz dərəcəsi və aylıq yükün nümunə hesablaması." },
  { slug: "demo-yeni-tikili-vs-kohne-fond", title: "Yeni tikili və köhnə fond: hansını seçmək?", cat: "dasinmaz-emlak", photo: "photo-1512917774080-9991f1c4c750", lead: "İki seqmentin qiymət, sənəd və istismar baxımından nümunə müqayisəsi." },
  { slug: "demo-kiraye-muqavilesi-diqqet", title: "Kirayə müqaviləsində diqqət ediləcək 10 məqam", cat: "meslehetler", photo: "photo-1493809842364-78817add7ffb", lead: "Kirayəçi və ev sahibi üçün nümunə yoxlama siyahısı." },
  { slug: "demo-interyer-trendleri", title: "Bu mövsümün interyer trendləri", cat: "interyer", photo: "photo-1618221195710-dd6b41faaea6", lead: "Rəng palitrası, material seçimi və işıqlandırma üzrə nümunə icmal." },
  { slug: "demo-kicik-mensilde-mekan", title: "Kiçik mənzildə məkanı genişləndirmək üsulları", cat: "interyer", photo: "photo-1502005229762-cf1b2da7c5d6", lead: "Planlaşdırma, güzgü və saxlama həlləri üzrə nümunə məsləhətlər." },
  { slug: "demo-villa-almaqda-yoxlama", title: "Villa alarkən yoxlanmalı sənədlər", cat: "dasinmaz-emlak", photo: "photo-1600596542815-ffad4c1539a9", lead: "Torpaq, tikinti və istismar sənədləri üzrə nümunə yoxlama siyahısı." },
  { slug: "demo-torpaq-investisiyasi", title: "Torpaq investisiyası: risk və imkanlar", cat: "dasinmaz-emlak", photo: "photo-1500382017468-9049fed747ef", lead: "Təyinat, kommunikasiya və likvidlik üzrə nümunə təhlil." },
  { slug: "demo-ofis-secimi-biznes", title: "Biznes üçün ofis seçimi: praktik meyarlar", cat: "dasinmaz-emlak", photo: "photo-1497366216548-37526070297c", lead: "Yerləşmə, sahə və xərc strukturu üzrə nümunə meyarlar." },
  { slug: "demo-temir-butcesi", title: "Təmir büdcəsini necə planlaşdırmalı", cat: "tikinti", photo: "photo-1581094794329-c8112a89af12", lead: "Material, işçi qüvvəsi və ehtiyat fondu üzrə nümunə bölgü." },
  { slug: "demo-enerji-semereliliyi", title: "Enerji səmərəliliyi: kommunal xərcləri azaltmaq", cat: "tikinti", photo: "photo-1497366811353-6870744d04b2", lead: "İzolyasiya, pəncərə və istilik sistemi üzrə nümunə tövsiyələr." },
  { slug: "demo-emlak-vergileri", title: "Əmlak vergiləri və rüsumlar barədə nümunə icmal", cat: "meslehetler", photo: "photo-1450101499163-c8848c66ca85", lead: "Alqı-satqı və sahiblik mərhələsindəki ödənişlərin nümunə siyahısı." },
  { slug: "demo-qisamuddetli-icare", title: "Qısamüddətli icarə biznesi: nədən başlamalı", cat: "dasinmaz-emlak", photo: "photo-1566073771259-6a8506099945", lead: "Obyekt seçimi, təchizat və idarəetmə üzrə nümunə plan." },
  { slug: "demo-rayon-secimi", title: "Rayon seçimi: gündəlik həyat üçün nə vacibdir", cat: "meslehetler", photo: "photo-1522708323590-d24dbb6b0267", lead: "Nəqliyyat, məktəb və infrastruktur üzrə nümunə qiymətləndirmə." },
  { slug: "demo-emlak-satisa-hazirlamaq", title: "Əmlakı satışa hazırlamağın nümunə qaydaları", cat: "meslehetler", photo: "photo-1484154218962-a197022b5858", lead: "Foto, qiymət və təqdimat üzrə nümunə tövsiyələr." },
  { slug: "demo-abseron-inkisaf", title: "Abşeron istiqamətində inkişaf: nümunə baxış", cat: "bazar-xeberleri", photo: "photo-1470770841072-f978cf4d019e", lead: "Yeni layihələr və infrastruktur üzrə nümunə icmal." },
  { slug: "demo-modul-evler", title: "Modul və konteyner evlər: kimə uyğundur?", cat: "tikinti", photo: "photo-1523217582562-09d0def993a6", lead: "Qiymət, quraşdırma müddəti və istismar üzrə nümunə müqayisə." },
  { slug: "demo-xarici-emlak-investisiya", title: "Xarici əmlaka investisiya: nümunə yol xəritəsi", cat: "dasinmaz-emlak", photo: "photo-1512453979798-5ea266f8880c", lead: "Bazar seçimi, hüquqi müşayiət və gəlirlilik üzrə nümunə addımlar." },
  { slug: "demo-luxe-home-estate-xeberler", title: "Luxe Home Estate: platforma yenilikləri (nümunə)", cat: "luxehomeestate-xeberleri", photo: "photo-1497366754035-f200968a6e72", lead: "Nümunə məzmun rejimi üçün hazırlanmış şirkət xəbəri." },
];
