/**
 * Azərbaycanın rəsmi inzibati-ərazi bölgüsü və bazar massivləri.
 *
 * **Bu fayl generasiya olunur — əl ilə redaktə etmə.**
 * Generator: `python scripts/build-locations-data.py`. Girişlər:
 * - `prisma/az-admin-divisions.json` — «İnzibati Ərazi Bölgüsü Təsnifatı, 2024»,
 *   Dövlət Statistika Komitəsi kollegiyasının 16.02.2024 tarixli 2/2 nömrəli
 *   qərarı (https://e-qanun.az/framework/57325). 11 respublika tabeli şəhər,
 *   64 rayon, 12 şəhər rayonu, 262 qəsəbə və 4 244 kənd.
 * - `prisma/unvanportali-admin-units.json` — Ünvan Reyestri (unvanportali.az):
 *   Bakı və Abşeronun rəsmi rayon/qəsəbə kodları. Bakının 12 rayonu və 59
 *   qəsəbəsi DSK siyahısı ilə çarpaz yoxlanılır.
 * - `prisma/baku-market-locations.json` — elanlarda işlənən massivlər, metro,
 *   nişangahlar və alternativ yazılışlar (bina.az, kub.az, arenda.az,
 *   yeniemlak.az, lalafo.az; bax `docs/erazi/baki-erazi-bolgusu.md`).
 *
 * Səviyyələr `Location.kind` ilə verilir:
 * - `CITY` — istifadəçinin birinci seçimi: respublika tabeli şəhərlər və
 *   rayonlar. Rayon burada `DISTRICT` deyil, çünki axtarışda şəhərlərlə eyni
 *   pillədə seçilir (Quba, Qusar, Şəki…). `DISTRICT` yalnız şəhərin
 *   daxilindəki inzibati rayon deməkdir.
 * - `DISTRICT` — şəhərdaxili inzibati rayonlar: Bakının 12, Gəncənin 2 rayonu.
 * - `SETTLEMENT` — rəsmi qəsəbələr və rayon tabeli şəhərlər (Xırdalan, Xudat,
 *   Horadiz, Liman, Göytəpə, Qovlar, Dəliməmmədli).
 * - `VILLAGE` — kəndlər. Rəsmi siyahı 4 244 kənd sayır; burada yalnız əmlak
 *   bazarında elan verilənlər var — Bakıya yaxın rayonlarda tam, turizm və
 *   bağ bölgələrində seçmə. Tam siyahı seçim menyusunu yararsız edərdi.
 * - `NEIGHBORHOOD` — yaşayış massivləri və mikrorayonlar. **Rəsmi inzibati
 *   vahid deyil**, amma elanlarda gündəlik işlənir (Yeni Günəşli, Yeni Yasamal,
 *   8-ci km). Rəsmi qəsəbə siyahısının təmiz qalması üçün ayrıca səviyyədədir.
 * - `METRO` — Bakı metrosunun stansiyaları; valideyni Bakıdır.
 * - `LANDMARK` — nişangahlar (ticarət mərkəzi, park, universitet, meydan);
 *   valideyni Bakıdır, elanda `landmarkId` ilə saxlanılır.
 *
 * Slug-lar adlardan qurulur (`build-taxonomy-sql.ts`) və valideynin slug-ı ilə
 * prefikslənir, ona görə eyni adlı yerlər toqquşmur — «İstisu» həm Kəlbəcərdə,
 * həm Lənkəranda, həm Xaçmazda var.
 */

export const BAKU = "Bakı";

/** Şəhər/rayonun altındakı yaşayış məntəqəsi. */
export type ChildPlace = {
  name: string;
  kind: "SETTLEMENT" | "VILLAGE" | "NEIGHBORHOOD";
  /** Rəsmi kod (DSK / Ünvan Reyestri) — yalnız rəsmi məntəqədə. */
  code?: string;
};

/** Şəhərdaxili inzibati rayon — yalnız Bakı və Gəncədə var. */
export type UrbanDistrict = {
  name: string;
  code?: string;
  places: ChildPlace[];
};

/**
 * Birinci pillə: respublika tabeli şəhər və ya rayon.
 *
 * `tier` yalnız sıralama üçündür — bazada hər ikisi `kind="CITY"` olur, çünki
 * istifadəçi axtarışda onları eyni açılan siyahıdan seçir. Lənkəran, Şəki və
 * Yevlax rəsmi təsnifatda həm şəhər, həm eyniadlı rayondur; saytda tək qeyddir.
 */
export type TopLevelPlace = {
  name: string;
  tier: "CITY" | "REGION";
  code?: string;
  /** Şəhərdaxili inzibati rayonlar. */
  districts?: UrbanDistrict[];
  /** Birbaşa alt yaşayış məntəqələri. */
  places?: ChildPlace[];
};

const s = (name: string, code?: string): ChildPlace =>
  code ? { name, kind: "SETTLEMENT", code } : { name, kind: "SETTLEMENT" };
const v = (name: string, code?: string): ChildPlace =>
  code ? { name, kind: "VILLAGE", code } : { name, kind: "VILLAGE" };
const n = (name: string): ChildPlace => ({ name, kind: "NEIGHBORHOOD" });

/**
 * Bakının 12 inzibati rayonu, 59 rəsmi qəsəbəsi (rəsmi kodları ilə) və bazar
 * massivləri. Bakıda rəsmi kənd yoxdur.
 *
 * Rəsmi təsnifatda Nərimanov, Nəsimi və Yasamal rayonlarında **qəsəbə yoxdur**
 * — orada yalnız massiv adları işlənir, ona görə onlar `NEIGHBORHOOD`-dur.
 */
export const BAKU_DISTRICTS: UrbanDistrict[] = [
  {
    name: "Binəqədi",
    code: "00100003",
    places: [
      s("28 May", "00104016"),
      s("Biləcəri", "00102016"),
      s("M.Ə.Rəsulzadə", "00105016"),
      s("Sulutəpə", "00101026"),
      s("Xocəsən", "00101016"),
      n("6-cı mikrorayon"),
      n("7-ci mikrorayon"),
      n("8-ci mikrorayon"),
      n("9-cu mikrorayon"),
      n("Dərnəgül"),
      n("Xutor"),
      n("Çiçək"),
      n("Motodrom"),
    ],
  },
  {
    name: "Nərimanov",
    code: "00700003",
    places: [n("Montin"), n("Böyükşor"), n("Baksol"), n("Çermet"), n("6-cı parallel")],
  },
  {
    name: "Nəsimi",
    code: "00800003",
    places: [
      n("1-ci mikrorayon"),
      n("2-ci mikrorayon"),
      n("3-cü mikrorayon"),
      n("4-cü mikrorayon"),
      n("5-ci mikrorayon"),
      n("Kubinka"),
      n("Papanin"),
      n("1-ci Alatava"),
    ],
  },
  {
    name: "Nizami",
    code: "00900003",
    places: [s("Keşlə", "00901016"), n("8-ci kilometr")],
  },
  {
    name: "Qaradağ",
    code: "00200003",
    places: [
      s("Baş Ələt", "00201026"),
      s("Heybət", "00204026"),
      s("Korgöz", "00206016"),
      s("Kotal", "00201036"),
      s("Lökbatan", "00204016"),
      s("Müşviqabad", "00208016"),
      s("Pirsaat", "00201056"),
      s("Puta", "00209016"),
      s("Qarakosa", "00201076"),
      s("Qobustan", "00207016"),
      s("Qızıldaş", "00202016"),
      s("Sahil", "00203016"),
      s("Sanqaçal", "00210016"),
      s("Yeni Ələt", "00201066"),
      s("Çeyildağ", "00205016"),
      s("Ümid", "00211016"),
      s("Şonqar", "00202026"),
      s("Şubanı", "00204036"),
      s("Şıxlar", "00201046"),
      s("Ələt", "00201016"),
    ],
  },
  {
    name: "Sabunçu",
    code: "00500003",
    places: [
      s("Bakıxanov", "00501016"),
      s("Balaxanı", "00502016"),
      s("Bilgəh", "00503016"),
      s("Kürdəxanı", "00504016"),
      s("Maştağa", "00505016"),
      s("Nardaran", "00506016"),
      s("Pirşağı", "00507016"),
      s("Ramana", "00508016"),
      s("Zabrat", "00510016"),
      n("Yeni Ramana"),
      n("Yeni Balaxanı"),
      n("Savalan"),
      n("Albalı"),
      n("Zabrat 1"),
      n("Zabrat 2"),
      n("Sea Breeze"),
      n("Ləhic bağları"),
    ],
  },
  {
    name: "Səbail",
    code: "00400003",
    places: [
      s("Badamdar", "00401016"),
      s("Bibiheybət", "00402016"),
      n("Bayıl"),
      n("20-ci sahə"),
      n("İçərişəhər"),
      n("Şıxov"),
    ],
  },
  {
    name: "Suraxanı",
    code: "00600003",
    places: [
      s("Bülbülə", "00601016"),
      s("Hövsan", "00603016"),
      s("Qaraçuxur", "00604016"),
      s("Yeni Suraxanı", "00605016"),
      s("Zığ", "00606016"),
      s("Əmircan", "00602016"),
      n("Yeni Günəşli"),
      n("Günəşli"),
      n("Yeni Günəşli A massivi"),
      n("Yeni Günəşli B massivi"),
      n("Yeni Günəşli D massivi"),
      n("Yeni Günəşli Q massivi"),
      n("Yeni Günəşli V massivi"),
      n("Bahar"),
      n("Dədə Qorqud"),
      n("Şərq"),
      n("Qum adası"),
    ],
  },
  {
    name: "Xəzər",
    code: "00300003",
    places: [
      s("Binə", "00313016"),
      s("Buzovna", "00314016"),
      s("Mərdəkan", "00318016"),
      s("Qala", "00317016"),
      s("Türkan", "00323016"),
      s("Zirə", "00324016"),
      s("Şağan", "00321016"),
      s("Şüvəlan", "00322016"),
      n("Dübəndi"),
      n("Şimal DRES"),
      n("Zağulba"),
      n("Albalılıq"),
      n("Xaşaxuna"),
      n("Binə Atçılıq"),
    ],
  },
  {
    name: "Xətai",
    code: "01000003",
    places: [
      s("Əhmədli", "01001016"),
      n("Ağ şəhər"),
      n("Həzi Aslanov"),
      n("Köhnə Günəşli"),
      n("NZS"),
      n("Qara şəhər"),
      n("UPD"),
    ],
  },
  {
    name: "Yasamal",
    code: "01100003",
    places: [n("Yeni Yasamal"), n("2-ci Alatava"), n("Sovetski"), n("Şamaxinka")],
  },
  {
    name: "Pirallahı",
    code: "01200003",
    places: [s("Gürgən", "01204016"), s("Neft Daşları", "01203016"), s("Çilov", "01202016")],
  },
];

/** Bakı metrosunun 27 stansiyası — xətt sırası ilə. */
export const METRO_STATIONS: string[] = [
  "İçərişəhər",
  "Sahil",
  "28 May",
  "Cəfər Cabbarlı",
  "Gənclik",
  "Nəriman Nərimanov",
  "Bakmil",
  "Ulduz",
  "Koroğlu",
  "Qara Qarayev",
  "Neftçilər",
  "Xalqlar Dostluğu",
  "Əhmədli",
  "Həzi Aslanov",
  "Şah İsmayıl Xətai",
  "Nizami",
  "Elmlər Akademiyası",
  "İnşaatçılar",
  "20 Yanvar",
  "Memar Əcəmi",
  "Nəsimi",
  "Azadlıq prospekti",
  "Dərnəgül",
  "Xocəsən",
  "Memar Əcəmi-2",
  "Avtovağzal",
  "8 Noyabr",
];

/**
 * Nişangahlar — bina.az, kub.az və yeniemlak.az siyahılarının birləşməsi,
 * dublikatlar və massiv/metro ilə təkrarlananlar çıxarılıb.
 */
export const LANDMARKS: string[] = [
  "28 Mall",
  "Gənclik Mall",
  "Baku Mall",
  "Metropark",
  "Park Bulvar",
  "Aygun City",
  "Megafun",
  "Olimpik Star",
  "Mərkəzi Univermaq",
  "Moskva univermağı",
  "Bakı univermağı",
  "Abşeron Ticarət Mərkəzi",
  "Binə ticarət mərkəzi",
  "Elit ticarət mərkəzi",
  "Eurohome Biləcəri Ticarət Mərkəzi",
  "Laçın Ticarət Mərkəzi",
  "Meyvəli Ticarət Mərkəzi",
  "Nargiz ticarət mərkəzi",
  "Riyad Ticarət Mərkəzi",
  "Sədərək ticarət mərkəzi",
  "Sədərək «Elit»",
  "Sədərək xalça bazarı",
  "Sədərək şirniyyat bazarı",
  "Sədərək tekstil bazarı",
  "Sədərək təsərrüfat bazarı",
  "Şüvəlan Park ticarət mərkəzi",
  "Xaqani ticarət mərkəzi",
  "Caspian Shopping Center",
  "Keşlə bazarı",
  "Montin bazarı",
  "Nəsimi bazarı",
  "Şərq bazarı",
  "Təzə bazar",
  "Yasamal bazarı",
  "Yaşıl bazar",
  "Neftçi bazası",
  "AF Business House",
  "AGA Business Center",
  "Altes Plaza",
  "ASK Plaza",
  "Babək Plaza",
  "Bridge Plaza",
  "Caspian Plaza",
  "Crystal Plaza",
  "Çıraq Plaza",
  "Dalğa Plaza",
  "Dəmirçi Plaza",
  "ISR Plaza",
  "Landmark",
  "Port Baku",
  "World Business Center",
  "Flame Towers",
  "Crescent Bay",
  "Grand Hayat Residence",
  "İnqilab Residence",
  "Javahir Residence",
  "Kristal Abşeron Bayıl",
  "Kristal Abşeron Əcəmi",
  "Kristal Abşeron Qara Qarayev",
  "Kristal Abşeron Yasamal",
  "Melissa Azadlıq",
  "Melissa Park",
  "Merida Premium",
  "MIDA Hövsan",
  "MIDA Hövsan 2",
  "MIDA Yasamal",
  "Park Azure",
  "Park Yasamal 2",
  "Royal Residence",
  "Absheron Marriott otel",
  "Ambassador otel",
  "Avropa otel",
  "Fairmont otel",
  "Four Seasons otel",
  "Hilton otel",
  "Hyatt Regency",
  "Park Inn",
  "Pullman Hotel",
  "Qafqaz Resort otel",
  "Oskar şadlıq sarayı",
  "A.S.Puşkin parkı",
  "AAF Park",
  "Aqua Park",
  "Atatürk parkı",
  "Axundov bağı",
  "Bayıl parkı",
  "Dağüstü parkı",
  "Dədə Qorqud parkı",
  "Dənizkənarı Milli park",
  "Hüseyn Cavid parkı",
  "İzmir parkı",
  "Koala parkı",
  "Koroğlu parkı",
  "M.Ə.Sabir parkı",
  "M.Hüseynzadə parkı",
  "Mərkəzi Nəbatat bağı",
  "Mərkəzi Park",
  "Molokan bağı",
  "Montin adına park",
  "Musabəyov parkı",
  "Nəriman Nərimanov parkı",
  "Park Zorge",
  "Prezident parkı",
  "Qış parkı",
  "Qubernator parkı",
  "Sahil bağı",
  "Səməd Vurğun parkı",
  "Sevgi parkı",
  "Sevil Qazıyeva parkı",
  "Şəlalə parkı",
  "Xaqani bağı",
  "Yasamal parkı",
  "Zabitlər parkı",
  "Zərifə Əliyeva adına park",
  "Zoopark",
  "Azadlıq meydanı",
  "Azneft meydanı",
  "Fəvvarələr meydanı",
  "Neapol dairəsi",
  "Qələbə dairəsi",
  "Ukrayna dairəsi",
  "Cavanşir körpüsü",
  "Tarqovu",
  "Beşmərtəbə",
  "Şəhidlər xiyabanı",
  "Qız Qalası",
  "Heydər Əliyev Mərkəzi",
  "Heydər Əliyev sarayı",
  "Heydər məscidi",
  "Xalça Muzeyi",
  "Ayna Sultanova heykəli",
  "C.Cabbarlı heykəli",
  "Nərimanov heykəli",
  "Nəsimi heykəli",
  "Sirk",
  "Araz kinoteatrı",
  "Azərbaycan kinoteatrı",
  "Dostluq kinoteatrı",
  "Nizami kinoteatrı",
  "Sevinc kinoteatrı",
  "Vətən kinoteatrı",
  "Respublika stadionu",
  "Olimpia stadionu",
  "Tofiq Bəhramov stadionu",
  "Şəfa stadionu",
  "Heydər Əliyev adına İdman Kompleksi",
  "Sərhədçi İdman Kompleksi",
  "Abu Arena",
  "ADA Universiteti",
  "Azərbaycan Dillər Universiteti",
  "Azərbaycan Dövlət Neft və Sənaye Universiteti",
  "Azərbaycan Turizm İnstitutu",
  "Bakı Asiya Universiteti",
  "Bakı Dövlət Universiteti",
  "Bakı Musiqi Akademiyası",
  "Bakı Slavyan Universiteti",
  "C.Naxçıvanski adına Hərbi Akademiya",
  "Dövlət İdarəçilik Akademiyası",
  "Fövqəladə Hallar Nazirliyinin Akademiyası",
  "İncəsənət və Mədəniyyət Universiteti",
  "İqtisadiyyat Universiteti",
  "Kooperasiya Universiteti",
  "Memarlıq və İnşaat Universiteti",
  "Milli Aviasiya Akademiyası",
  "Milli Konservatoriya",
  "Odlar Yurdu Universiteti",
  "Pedaqoji Universiteti",
  "Qafqaz Universiteti",
  "Qərb Universiteti",
  "Rəssamlıq Akademiyası",
  "Təfəkkür Universiteti",
  "Texniki Universiteti",
  "Tibb Universiteti",
  "Xəzər Universiteti",
  "Hərbi Hospital",
  "Mərkəzi Neftçilər Xəstəxanası",
  "ASAN Xidmət №1",
  "ASAN Xidmət №2",
  "ASAN Xidmət №3",
  "ASAN Xidmət №4",
  "ASAN Xidmət №5",
  "ASAN Xidmət №6",
  "Dövlət İmtahan Mərkəzi",
  "Dövlət Statistika Komitəsi",
  "Milli Məclis",
  "ANS telekanalı",
  "ATV telekanalı",
  "AZTV telekanalı",
  "İctimai telekanalı",
  "Lider telekanalı",
  "Space TV",
  "AMAY",
  "ABŞ səfirliyi",
  "Çin səfirliyi",
  "İran səfirliyi",
  "Özbəkistan səfirliyi",
  "Rusiya səfirliyi",
  "Türkiyə səfirliyi",
  "Daxili İşlər Nazirliyi",
  "Ədliyyə Nazirliyi",
  "Ekologiya və Təbii Sərvətlər Nazirliyi",
  "Əmək və Əhalinin Sosial Müdafiəsi Nazirliyi",
  "Energetika Nazirliyi",
  "Fövqəladə Hallar Nazirliyi",
  "Gənclər və İdman Nazirliyi",
  "İqtisadiyyat Nazirliyi",
  "Maliyyə Nazirliyi",
  "Milli Təhlükəsizlik Nazirliyi",
  "Müdafiə Sənayesi Nazirliyi",
  "Rəqəmsal İnkişaf və Nəqliyyat Nazirliyi",
  "Səhiyyə Nazirliyi",
  "Elm və Təhsil Nazirliyi",
  "Dövlət Vergi Xidməti",
  "Xarici İşlər Nazirliyi",
];

/**
 * Alternativ yazılışlar: köhnə adlar («Kirov qəsəbəsi»), gündəlik yazılış
 * («Müşfiqabad»), qısaltmalar («8 km»). Axtarış sahəsinə (`searchName`) yazılır,
 * ayrıca yer yaratmır. Açar kanonik addır və eyni adlı bütün yerlərə aiddir.
 */
export const LOCATION_ALIASES: Record<string, string[]> = {
  "1-ci Alatava": ["Alatava 1"],
  "1-ci mikrorayon": ["1 mkr"],
  "2-ci Alatava": ["Alatava", "Alatava 2"],
  "2-ci mikrorayon": ["2 mkr"],
  "3-cü mikrorayon": ["3 mkr"],
  "4-cü mikrorayon": ["4 mkr"],
  "5-ci mikrorayon": ["5 mkr"],
  "6-cı mikrorayon": ["6 mkr"],
  "6-cı parallel": ["6-cı Xrebtovı", "6-cı paralel"],
  "7-ci mikrorayon": ["7 mkr"],
  "8-ci kilometr": ["8 km", "8-ci km"],
  "8-ci mikrorayon": ["8 mkr"],
  "9-cu mikrorayon": ["9 mkr"],
  "A.S.Puşkin parkı": ["Puşkin parkı"],
  "Abşeron Gənclər Şəhərciyi": ["Gənclər şəhərciyi"],
  "ASAN Xidmət №1": ["Asan Xidmət-1"],
  "ASAN Xidmət №2": ["Asan Xidmət-2"],
  "ASAN Xidmət №3": ["Asan Xidmət-3"],
  "ASAN Xidmət №4": ["Asan Xidmət-4"],
  "ASAN Xidmət №5": ["Asan Xidmət-5"],
  "ASAN Xidmət №6": ["Asan Xidmət-6"],
  "Azadlıq prospekti": ["Azadlıq"],
  "Azərbaycan Dövlət Neft və Sənaye Universiteti": ["Neft Akademiyası"],
  "Bakı Dövlət Universiteti": ["BDU"],
  "Bibiheybət": ["Bibi Heybət"],
  "Dövlət İmtahan Mərkəzi": ["DİM", "TQDK"],
  "Dövlət Vergi Xidməti": ["Vergilər Nazirliyi"],
  "Dübəndi": ["Dübəndi bağları"],
  "Dənizkənarı Milli park": ["Bulvar"],
  "Elm və Təhsil Nazirliyi": ["Təhsil Nazirliyi"],
  "Fəvvarələr meydanı": ["Fontanlar bağı"],
  "Görədil": ["Goradil"],
  "Hacı Zeynalabdin": ["Nasosnu", "Nasosnı"],
  "Heydər Əliyev adına İdman Kompleksi": ["İdman kompleksi"],
  "Həzi Aslanov": ["H.Aslanov"],
  "İctimai telekanalı": ["İctimai TV"],
  "İncəsənət və Mədəniyyət Universiteti": ["İncəsənət və Mədəniyyət Un."],
  "İqtisadiyyat Nazirliyi": ["İqtisadi İnkişaf Nazirliyi"],
  "İqtisadiyyat Universiteti": ["UNEC", "İqtisad Universiteti"],
  "İran səfirliyi": ["İran İslam Respublikası səfirliyi"],
  "İçərişəhər": ["İçəri Şəhər"],
  "Lider telekanalı": ["Lider TV"],
  "Ləhic bağları": ["Ləhiş bağları"],
  "M.Ə.Rəsulzadə": ["Kirov qəsəbəsi", "Məhəmməd Əmin Rəsulzadə", "Rəsulzadə"],
  "Maştağa": ["Məştağa"],
  "Memar Əcəmi-2": ["Memar Əcəmi 2"],
  "Memarlıq və İnşaat Universiteti": ["İnşaat Universiteti"],
  "Milli Aviasiya Akademiyası": ["Aviasiya Akademiyası"],
  "Molokan bağı": ["Malokan bağı"],
  "Müşviqabad": ["Müşfiqabad"],
  "Məmmədli": ["Məhəmmədli"],
  "Mərkəzi Nəbatat bağı": ["Botanika bağı"],
  "Mərkəzi Univermaq": ["MUM"],
  "Pirəkəşkül": ["Perekeşkül", "Pereküşkül"],
  "Qubernator parkı": ["Filarmoniya bağı"],
  "Qurtuluş 93": ["Qurtuluş-93"],
  "Rəqəmsal İnkişaf və Nəqliyyat Nazirliyi": ["Nəqliyyat Nazirliyi", "Rabitə və Yüksək Texnologiyalar Nazirliyi"],
  "Sanqaçal": ["Sangaçal", "Səngəçal"],
  "Sevinc kinoteatrı": ["Sevinc k/t"],
  "Tarqovu": ["Nizami küçəsi", "Torqovı"],
  "Türkan": ["Türkən"],
  "Xaqani ticarət mərkəzi": ["Xəqani ticarət mərkəzi"],
  "Xocəsən": ["Xocasən"],
  "Yeni Günəşli": ["Y.Günəşli"],
  "Yeni Günəşli A massivi": ["Massiv A"],
  "Yeni Günəşli B massivi": ["Massiv B"],
  "Yeni Günəşli D massivi": ["Massiv D"],
  "Yeni Günəşli Q massivi": ["Massiv G", "Massiv Q"],
  "Yeni Günəşli V massivi": ["Massiv V"],
  "Yeni Ramana": ["Y.Ramana"],
  "Yeni Suraxanı": ["Y.Suraxanı"],
  "Zabrat 1": ["1-ci Zabrat", "I Zabrat"],
  "Zabrat 2": ["2-ci Zabrat", "II Zabrat"],
  "Zağulba": ["Zaqulba", "Zuğulba"],
  "Çeyildağ": ["Ceyildağ"],
  "Şah İsmayıl Xətai": ["Xətai metrosu"],
  "Şimal DRES": ["Şimal QRES"],
  "Şubanı": ["Şubani"],
  "Şüvəlan Park ticarət mərkəzi": ["Şüvəlan ticarət mərkəzi"],
  "Şıxov": ["Şıx"],
};

/**
 * Respublika tabeli şəhərlər və rayonlar bir siyahıdadır, çünki axtarışda
 * eyni açılan siyahıdan seçilir: əvvəl şəhərlər, sonra rayonlar.
 */
export const PLACES: TopLevelPlace[] = [
  // --- Respublika tabeli şəhərlər ---
  { name: BAKU, tier: "CITY", code: "00000002", districts: BAKU_DISTRICTS },
  {
    name: "Gəncə",
    tier: "CITY",
    code: "20000002",
    districts: [{ name: "Kəpəz", places: [] }, { name: "Nizami", places: [] }],
    places: [s("Cavadxan", "20001016"), s("Göygöl"), s("Hacıkənd", "20002016"), s("Məhsəti", "20003016"), s("Natəvan", "20004016"), s("Sadıllı", "20005016"), s("Şıxzamanlı", "20006016")],
  },
  {
    name: "Sumqayıt",
    tier: "CITY",
    code: "30900002",
    places: [s("Corat", "30902016"), s("Hacı Zeynalabdin", "30903016")],
  },
  { name: "Mingəçevir", tier: "CITY", code: "90200002" },
  {
    name: "Şirvan",
    tier: "CITY",
    code: "91100002",
    places: [s("Bayramlı", "91102016"), s("Hacıqəhrəmanlı", "91103016")],
  },
  {
    name: "Naftalan",
    tier: "CITY",
    code: "51000002",
    places: [v("Qasımbəyli", "51001028"), v("Qaşaltı Qaraqoyunlu", "51001018")],
  },
  {
    name: "Naxçıvan",
    tier: "CITY",
    code: "10400002",
    places: [
      s("Əliabad", "10402016"),
      v("Bulqan", "10403028"),
      v("Hacıniyyət", "10405028"),
      v("Qaraxanbəyli", "10404018"),
      v("Qaraçuq", "10403018"),
      v("Tumbul", "10405018"),
    ],
  },
  { name: "Xankəndi", tier: "CITY", code: "70400002", places: [s("Kərkicahan", "70402016")] },
  {
    name: "Lənkəran",
    tier: "CITY",
    code: "80200002",
    places: [
      s("Aşağı Nüvədi", "80204016"),
      s("Balıqçılar", "80236016"),
      s("Gərmətük", "80206016"),
      s("Haftoni", "80205016"),
      s("Hirkan", "80203016"),
      s("Liman", "80226014"),
      s("Nərimanabad", "80207016"),
      s("İstisu", "80230016"),
      s("Şirinsu", "80226036"),
      v("Aşağı Apu", "80225028"),
      v("Bala Şürük", "80239028"),
      v("Ballabur", "80223028"),
      v("Biləsər", "80208018"),
      v("Boladı", "80227018"),
      v("Bürcəli", "80225058"),
      v("Bəliton", "80243018"),
      v("Cil", "80224028"),
      v("Darquba", "80212038"),
      v("Daşdalıqcar", "80214028"),
      v("Daştatük", "80225038"),
      v("Digah", "80213028"),
      v("Dıryan", "80209028"),
      v("Girdəni", "80228018"),
      v("Göyşaban", "80215018"),
      v("Günəhir", "80211018"),
      v("Gəgiran", "80209018"),
      v("Haftaruon", "80216068"),
      v("Havzova", "80229018"),
      v("Horavenc", "80243028"),
      v("Jidi", "80209058"),
      v("Kosalar", "80239018"),
      v("Köhnə Gəgir", "80244028"),
      v("Küvənil", "80204058"),
      v("Kənarmeşə", "80238018"),
      v("Kərgəlan", "80212018"),
      v("Lüvəsər", "80212028"),
      v("Ləj", "80237018"),
      v("Mamusta", "80214018"),
      v("Mikolan", "80218038"),
      v("Mollakənd", "80217028"),
      v("Moloja", "80216058"),
      v("Moğonojoba", "80219048"),
      v("Narbağı", "80242028"),
      v("Osakücə", "80216018"),
      v("Pambəyi", "80216028"),
      v("Parakənd", "80203058"),
      v("Qodəsə", "80211058"),
      v("Qumbaşı", "80226028"),
      v("Qurumba", "80242018"),
      v("Rvo", "80217018"),
      v("Rəzvan", "80225048"),
      v("Seliqavol", "80208068"),
      v("Separadi", "80220018"),
      v("Seyidəkəran", "80238028"),
      v("Sinovli", "80216048"),
      v("Siyablı", "80241038"),
      v("Siyavar", "80221018"),
      v("Sütəmurdov", "80231018"),
      v("Səbir", "80212048"),
      v("Səpnəkəran", "80218018"),
      v("Sərinbulaq", "80225068"),
      v("Talışlı", "80205038"),
      v("Tatoba", "80216038"),
      v("Tuado", "80244018"),
      v("Tükəvilə", "80220038"),
      v("Türkəkəran", "80219028"),
      v("Türkəncil", "80211038"),
      v("Tütəpeştə", "80219038"),
      v("Təngivan", "80241028"),
      v("Vel", "80221028"),
      v("Velədi", "80206048"),
      v("Vilvan", "80232018"),
      v("Viravul", "80233018"),
      v("Viyən", "80234018"),
      v("Vıy", "80208078"),
      v("Xanbulan", "80225018"),
      v("Xanlıqlı", "80205048"),
      v("Xarxatan", "80224038"),
      v("Xolmili", "80222018"),
      v("Yuxarı Nüvədi", "80218028"),
      v("Zövlə", "80235018"),
      v("Ürgə", "80215028"),
      v("Şağlakücə", "80223018"),
      v("Şağlaser", "80224018"),
      v("Şilim", "80238038"),
      v("Şiləvar", "80213018"),
      v("Şivlik", "80243038"),
      v("Şovu", "80241018"),
      v("Şürük", "80219018"),
      v("Şıxakəran", "80240018"),
      v("Ələzəpin", "80208028"),
      v("Əşlə", "80217058"),
    ],
  },
  {
    name: "Şəki",
    tier: "CITY",
    code: "40400002",
    places: [
      s("Turan", "40402016"),
      s("Çələbixan", "40410036"),
      v("Abbas", "40404048"),
      v("Aran", "40417028"),
      v("Aydınbulaq", "40403018"),
      v("Aşağı Daşağıl", "40403048"),
      v("Aşağı Göynük", "40404018"),
      v("Aşağı Küngüt", "40405018"),
      v("Aşağı Kəldək", "40418028"),
      v("Aşağı Layısqı", "40404038"),
      v("Aşağı Şabalıd", "40415038"),
      v("Babaratma", "40425028"),
      v("Baltalı", "40426018"),
      v("Baqqal", "40419028"),
      v("Baş Göynük", "40406018"),
      v("Baş Küngüt", "40408018"),
      v("Baş Kəldək", "40418018"),
      v("Baş Layısqı", "40409018"),
      v("Baş Zəyzid", "40407018"),
      v("Baş Şabalıd", "40406028"),
      v("Bideyiz", "40408028"),
      v("Birinci Biləcik", "40419018"),
      v("Bolludərə", "40420018"),
      v("Böyük Dəhnə", "40427018"),
      v("Cumakənd", "40428018"),
      v("Cunud", "40409028"),
      v("Cəfərabad", "40411018"),
      v("Cəyirli", "40412018"),
      v("Daşbulaq", "40410028"),
      v("Daşüz", "40410018"),
      v("Dərəcənnət", "40416028"),
      v("Fazıl", "40422028"),
      v("Göybulaq", "40411048"),
      v("Kiçik Dəhnə", "40429018"),
      v("Kiş", "40430018"),
      v("Kosalı", "40423028"),
      v("Köbər Zəyzid", "40414028"),
      v("Köndələn", "40404028"),
      v("Küdürlü", "40423018"),
      v("Kəhrizoba", "40411038"),
      v("Oraban", "40418038"),
      v("Orta Zəyzid", "40414018"),
      v("Oxud", "40432018"),
      v("Qaradağlı", "40425038"),
      v("Qaratorpaq", "40420028"),
      v("Qayabaşı", "40424018"),
      v("Qoxmuq", "40431018"),
      v("Qozlubulaq", "40412028"),
      v("Qudula", "40425018"),
      v("Qumux", "40409048"),
      v("Qırxbulaq", "40414038"),
      v("Qızılarx", "40423038"),
      v("Sarıca", "40424028"),
      v("Suçma", "40416018"),
      v("Təpəcənnət", "40411028"),
      v("Vərəzət", "40407028"),
      v("Zunud", "40415028"),
      v("Çapağan", "40405048"),
      v("Çayqaraqoyunlu", "40402058"),
      v("Çeşməli", "40421018"),
      v("Çolaqlı", "40411058"),
      v("Öryət", "40421028"),
      v("İbrahimkənd", "40422018"),
      v("İkinci Biləcik", "40419038"),
      v("İnçə", "40415018"),
      v("Şin", "40409038"),
      v("Şirinbulaq", "40433018"),
      v("Şorsu", "40434018"),
      v("Əliyar", "40403028"),
    ],
  },
  {
    name: "Yevlax",
    tier: "CITY",
    code: "90100002",
    places: [
      s("Aran", "90118016"),
      s("Duzdağ", "90109036"),
      s("Meyvəli", "90113026"),
      v("Ağqıraqlı", "90116028"),
      v("Aşağı Bucaq", "90102018"),
      v("Aşağı Qarxun", "90114028"),
      v("Aşağı Salamabad", "90103018"),
      v("Balçılı", "90116018"),
      v("Boşçalı", "90110028"),
      v("Bəydili", "90102048"),
      v("Cırdaxan", "90104048"),
      v("Dəlləklər", "90107048"),
      v("Göyük", "90107038"),
      v("Gülövşə", "90102058"),
      v("Hacımahmudlu", "90107058"),
      v("Hacıselli", "90105038"),
      v("Havarlı", "90105018"),
      v("Hürüuşağı", "90110038"),
      v("Kolanı", "90115028"),
      v("Kövər", "90115018"),
      v("Malbinəsi", "90120018"),
      v("Marzılı", "90105048"),
      v("Nemətabad", "90109018"),
      v("Nurallar", "90107068"),
      v("Nəmirli", "90107028"),
      v("Nərimanabad", "90112028"),
      v("Qaramanlı", "90107018"),
      v("Qaraməmmədli", "90106018"),
      v("Qaraoğlan", "90103038"),
      v("Qoyunbinəsi", "90119018"),
      v("Quşçu", "90111028"),
      v("Rüstəmli", "90106028"),
      v("Salahlı", "90121018"),
      v("Səmədabad", "90112018"),
      v("Tanrıqulular", "90110018"),
      v("Varvara", "90104018"),
      v("Xaldan", "90111018"),
      v("Xanabad", "90117028"),
      v("Yaldili", "90109028"),
      v("Yeni Çobankərə", "90112038"),
      v("Yenicə", "90102038"),
      v("Yuxarı Bucaq", "90102028"),
      v("Yuxarı Qarxun", "90114018"),
      v("Yuxarı Salamabad", "90111038"),
      v("İsmayılabad", "90112048"),
      v("Əcəmi", "90103028"),
      v("Ərəbbəsrə", "90117018"),
      v("Ərəş", "90113018"),
      v("Əxşam", "90105028"),
    ],
  },

  // --- Rayonlar ---
  {
    name: "Abşeron",
    tier: "REGION",
    code: "30800001",
    places: [
      s("Aşağı Güzdək", "30803016"),
      s("Ceyranbatan", "30804016"),
      s("Digah", "30805016"),
      s("Güzdək", "30808016"),
      s("Hökməli", "30809016"),
      s("Mehdiabad", "30812016"),
      s("Qobu", "30810016"),
      s("Saray", "30815016"),
      s("Xırdalan", "30801014"),
      s("Şəfəq", "30816016"),
      v("Fatmayı", "30806018"),
      v("Görədil", "30807018"),
      v("Masazır", "30811018"),
      v("Məmmədli", "30813018"),
      v("Novxanı", "30814018"),
      v("Pirəkəşkül", "30802018"),
      v("Qobustan", "30802028"),
      n("Qurtuluş 93"),
      n("Abşeron Gənclər Şəhərciyi"),
      n("Yeni Bakı"),
      n("Atyalı"),
      n("Nübar"),
    ],
  },
  {
    name: "Astara",
    tier: "REGION",
    places: [s("Kijəbə"), s("Ərçivan"), v("Maşxan"), v("Pensər"), v("Sım")],
  },
  { name: "Ağcabədi", tier: "REGION", places: [s("Hindarx")] },
  {
    name: "Ağdam",
    tier: "REGION",
    places: [
      s("Acarlı"),
      s("Birinci Alıbəyli"),
      s("Birinci Baharlı"),
      s("Birinci Dördyol"),
      s("Birinci Quzanlı"),
      s("Bənövşələr"),
      s("Qasımbəyli"),
      s("Quzanlı"),
      s("Səfərli"),
      s("Təzəkənd"),
      s("İkinci Alıbəyli"),
      s("İkinci Baharlı"),
      s("İkinci Dördyol"),
      s("İmamqulubəyli"),
    ],
  },
  { name: "Ağdaş", tier: "REGION", places: [s("Ləki"), s("Türyançay")] },
  { name: "Ağdərə", tier: "REGION", places: [s("Şıxarx")] },
  {
    name: "Ağstafa",
    tier: "REGION",
    places: [
      s("Ceyrançöl"),
      s("Həzi Aslanov"),
      s("Poylu"),
      s("Qarayazı"),
      s("Saloğlu"),
      s("Soyuqbulaq"),
      s("Soyuqbulaqlar"),
      s("Vurğun"),
      s("Şəkərli"),
    ],
  },
  { name: "Ağsu", tier: "REGION" },
  { name: "Babək", tier: "REGION", places: [s("Cəhri"), s("Nehrəm")] },
  {
    name: "Balakən",
    tier: "REGION",
    places: [s("Qabaqçöl"), v("Katex"), v("Mahamalar"), v("Talalar")],
  },
  {
    name: "Beyləqan",
    tier: "REGION",
    places: [
      s("Bahar"),
      s("Baharabad"),
      s("Bolsulu"),
      s("Günəş"),
      s("Mayak"),
      s("Mil"),
      s("Milabad"),
      s("Orconikidze"),
      s("Qəhrəmanlı"),
      s("Sarısu"),
      s("Türklər"),
      s("Yeni Mil"),
      s("Yuxarı Aran"),
      s("Örənqala"),
      s("Şəfəq"),
      s("Şərq"),
    ],
  },
  { name: "Biləsuvar", tier: "REGION" },
  { name: "Bərdə", tier: "REGION" },
  { name: "Culfa", tier: "REGION" },
  {
    name: "Cəbrayıl",
    tier: "REGION",
    places: [s("Mahmudlu"), s("Qumlaq"), s("Xudafərin"), s("Xələfli")],
  },
  { name: "Cəlilabad", tier: "REGION", places: [s("Göytəpə"), s("Novoqolovka")] },
  {
    name: "Daşkəsən",
    tier: "REGION",
    places: [
      s("Alunitdağ"),
      s("Quşçu"),
      s("Quşçu körpüsü"),
      s("Yuxarı Daşkəsən"),
      v("Xoşbulaq"),
      v("Zəylik"),
    ],
  },
  {
    name: "Füzuli",
    tier: "REGION",
    places: [
      s("1 №-li Qayıdış"),
      s("10 №-li Qayıdış"),
      s("11 №-li Qayıdış"),
      s("2 №-li Qayıdış"),
      s("3 №-li Qayıdış"),
      s("4 №-li Qayıdış"),
      s("5 №-li Qayıdış"),
      s("6 №-li Qayıdış"),
      s("7 №-li Qayıdış"),
      s("8 №-li Qayıdış"),
      s("9 №-li Qayıdış"),
      s("Beşinci Zobucuq"),
      s("Birinci Zobucuq"),
      s("Dördüncü Zobucuq"),
      s("Horadiz"),
      s("Üçüncü Zobucuq"),
      s("İkinci Zobucuq"),
    ],
  },
  {
    name: "Goranboy",
    tier: "REGION",
    places: [
      s("Aşağı Ağcakənd"),
      s("Dəliməmmədli"),
      s("Goran"),
      s("Kürəkçay"),
      s("Qazanbulaq"),
      s("Qızılhacılı"),
      s("Yuxarı Ağcakənd"),
    ],
  },
  {
    name: "Göygöl",
    tier: "REGION",
    places: [
      s("Ağdağ"),
      s("Aşağı Zurnabad"),
      s("Bəhrambağ"),
      s("Firuzabad"),
      s("Hacıməlik"),
      s("Qızılqaya"),
      v("Zurnabad"),
      v("Çaykənd"),
    ],
  },
  { name: "Göyçay", tier: "REGION" },
  {
    name: "Gədəbəy",
    tier: "REGION",
    places: [v("Arıqıran"), v("Düzyurd"), v("Slavyanka"), v("Söyüdlü")],
  },
  {
    name: "Hacıqabul",
    tier: "REGION",
    places: [s("Balıqçı"), s("Muğan"), s("Navahı"), s("Padar"), s("Pirsaat")],
  },
  { name: "İmişli", tier: "REGION", places: [s("Bəhrəmtəpə"), s("Vətəgə")] },
  {
    name: "İsmayıllı",
    tier: "REGION",
    places: [
      s("Basqal"),
      s("Lahıc"),
      v("Buynuz"),
      v("Diyallı"),
      v("Mollaisaqlı"),
      v("Talıstan"),
      v("Topçu"),
      v("İvanovka"),
    ],
  },
  { name: "Kürdəmir", tier: "REGION", places: [s("Karrar"), s("Qarabucaq")] },
  { name: "Kəlbəcər", tier: "REGION", places: [s("İstisu")] },
  { name: "Kəngərli", tier: "REGION", places: [s("Qıvraq")] },
  { name: "Laçın", tier: "REGION", places: [s("Qayğı")] },
  { name: "Lerik", tier: "REGION", places: [v("Cəngəmiran"), v("Kəlvəz")] },
  {
    name: "Masallı",
    tier: "REGION",
    places: [s("Boradigah"), s("Ərkivan"), v("Qızılağac"), v("Təzə Alvadı"), v("Xıl")],
  },
  { name: "Neftçala", tier: "REGION", places: [s("Bankə"), s("Həsənabad"), s("Xıllı")] },
  { name: "Ordubad", tier: "REGION", places: [s("Ağdərə"), s("Parağaçay"), s("Şəhriyar")] },
  {
    name: "Oğuz",
    tier: "REGION",
    places: [v("Baş Daşağıl"), v("Calut"), v("Kərimli"), v("Xaçmaz")],
  },
  {
    name: "Qax",
    tier: "REGION",
    places: [v("Ləkit"), v("Qaxbaş"), v("Sarıbaş"), v("Zərnə"), v("İlisu"), v("Əmbərçay")],
  },
  {
    name: "Qazax",
    tier: "REGION",
    places: [v("Aslanbəyli"), v("Daş Salahlı"), v("Kəmərli"), v("Yuxarı Salahlı")],
  },
  {
    name: "Qobustan",
    tier: "REGION",
    places: [
      s("Üzümçü"),
      v("Bədəlli"),
      v("Bəklə"),
      v("Ceyrankeçməz"),
      v("Cəmcəmli"),
      v("Cəngi"),
      v("Cəyirli"),
      v("Damlamaca"),
      v("Dağ Kolanı"),
      v("Dərəkənd"),
      v("Göydərə"),
      v("Nabur"),
      v("Nardaran"),
      v("Poladlı"),
      v("Qaracüzlü"),
      v("Qurbançı"),
      v("Sündü"),
      v("Sədəfli"),
      v("Təklə"),
      v("Təklə Mirzəbaba"),
      v("Təsi"),
      v("Xilmilli"),
      v("Yekəxana"),
      v("Çay Qurbançı"),
      v("Çelov"),
      v("Çuxanlı"),
      v("İlanlı"),
      v("Şıxlar"),
      v("Şıxzahırlı"),
      v("Ərəbqədim"),
      v("Ərəbşahverdi"),
      v("Ərəbşalbaş"),
    ],
  },
  {
    name: "Quba",
    tier: "REGION",
    places: [
      s("Barlı"),
      s("Bağbanlı"),
      s("Gənclər"),
      s("Qaraçay"),
      s("Qonaqkənd"),
      s("Qırmızı Qəsəbə"),
      s("Zərdabi"),
      v("Afurca"),
      v("Alpan"),
      v("Amsar"),
      v("Ağbil"),
      v("Birinci Nügədi"),
      v("Buduq"),
      v("Cek"),
      v("Cimi"),
      v("Küpçal"),
      v("Rustov"),
      v("Təngəaltı"),
      v("Xaşı"),
      v("Xucbala"),
      v("Xınalıq"),
      v("Yerfi"),
      v("İkinci Nügədi"),
    ],
  },
  { name: "Qubadlı", tier: "REGION" },
  {
    name: "Qusar",
    tier: "REGION",
    places: [
      s("Samur"),
      v("Hil"),
      v("Həzrə"),
      v("Kuzun"),
      v("Laza"),
      v("Suvacal"),
      v("Urva"),
      v("Yuxarı Ləgər"),
      v("Əniq"),
    ],
  },
  {
    name: "Qəbələ",
    tier: "REGION",
    places: [
      s("Bum"),
      s("Nic"),
      s("Vəndam"),
      v("Hacıalılı"),
      v("Həzrə"),
      v("Laza"),
      v("Mıxlıqovaq"),
      v("Qəmərvan"),
      v("Savalan"),
      v("Tüntül"),
      v("Yengicə"),
      v("Zarağan"),
      v("Çuxur Qəbələ"),
    ],
  },
  { name: "Saatlı", tier: "REGION" },
  { name: "Sabirabad", tier: "REGION" },
  { name: "Salyan", tier: "REGION", places: [s("Qaraçala"), s("Qırx Çıraq")] },
  {
    name: "Samux",
    tier: "REGION",
    places: [
      s("Alabaşlı"),
      s("Qaraarx"),
      s("Qaraağaclı"),
      s("Qarayeri"),
      s("Yenibağ"),
      s("İnstitut"),
    ],
  },
  {
    name: "Siyəzən",
    tier: "REGION",
    places: [
      s("Gilgilçay"),
      v("Balaca Həmyə"),
      v("Beşdam"),
      v("Böyük Həmyə"),
      v("Cəndəhar"),
      v("Dağ Quşçu"),
      v("Daşlı Çalğan"),
      v("Dərə Zarat"),
      v("Eynibulaq"),
      v("Hacışəkər"),
      v("Kolanı"),
      v("Köhnə Quşçu"),
      v("Künövşə"),
      v("Müşkülqazma"),
      v("Məşrif"),
      v("Nardaran"),
      v("Orta Çalğan"),
      v("Qalaaltı"),
      v("Qalaşıxı"),
      v("Qaragöz"),
      v("Qozağacı"),
      v("Qərəh"),
      v("Sağolcan"),
      v("Sədan"),
      v("Tuğay"),
      v("Yanıq Ələz"),
      v("Yenikənd"),
      v("Yuxarı Ələz"),
      v("Zarat"),
      v("Çarxana"),
      v("Əlməkolu"),
      v("Ərziküş"),
    ],
  },
  { name: "Sədərək", tier: "REGION", places: [s("Heydərabad")] },
  { name: "Tovuz", tier: "REGION", places: [s("Qovlar"), v("Bozalqanlı"), v("Əyyublu")] },
  { name: "Tərtər", tier: "REGION" },
  { name: "Ucar", tier: "REGION" },
  {
    name: "Xaçmaz",
    tier: "REGION",
    places: [
      s("Arzu"),
      s("Aşağı Ləgər"),
      s("Dalğalı"),
      s("Günəşli"),
      s("Meşəli"),
      s("Sahillər"),
      s("Samurçay"),
      s("Turist"),
      s("Xudat"),
      s("Yeni Həyat"),
      s("İstisu"),
      s("Şimal"),
      s("Şollar"),
      v("Bostançı"),
      v("Hülövlü"),
      v("Nabran"),
      v("Nərəcan"),
      v("Qaracik"),
      v("Yalama"),
    ],
  },
  { name: "Xocalı", tier: "REGION", places: [s("Əsgəran")] },
  { name: "Xocavənd", tier: "REGION", places: [s("Hadrut"), s("Qırmızı Bazar")] },
  {
    name: "Xızı",
    tier: "REGION",
    places: [
      s("Altıağac"),
      s("Giləzi"),
      s("Şorabad"),
      v("Ağdərə"),
      v("Baxışlı"),
      v("Bəyəhmədyurd"),
      v("Dizəvər"),
      v("Fındığan"),
      v("Güneyqışlaq"),
      v("Məşədi Həsən"),
      v("Qarabulaq"),
      v("Qars"),
      v("Qasımkənd"),
      v("Qızılqazma"),
      v("Safbulaq"),
      v("Sitalçay"),
      v("Tudar"),
      v("Türkoba"),
      v("Tıxlı"),
      v("Təzəkənd"),
      v("Vərdah"),
      v("Xələnc"),
      v("Yarımca"),
      v("Yaşma"),
      v("Yeni Yaşma"),
      v("Yuxarı Əngilan"),
      v("Əmbizlər"),
      v("Əngilan"),
    ],
  },
  { name: "Yardımlı", tier: "REGION" },
  {
    name: "Zaqatala",
    tier: "REGION",
    places: [s("Əliabad"), v("Car"), v("Mazıx"), v("Muxax"), v("Qandax")],
  },
  {
    name: "Zəngilan",
    tier: "REGION",
    places: [s("Ağ oyuq"), s("Ağbənd"), s("Bartaz"), s("Həkəri"), s("Mincivan")],
  },
  { name: "Zərdab", tier: "REGION", places: [s("Bəyimli")] },
  {
    name: "Şabran",
    tier: "REGION",
    places: [
      v("Aygünlü"),
      v("Ağalıq"),
      v("Ağbaş"),
      v("Bilici Qorğan"),
      v("Borbor"),
      v("Ceyranlı"),
      v("Dağ Bilici"),
      v("Daşlıyataq"),
      v("Düz Bilici"),
      v("Dəhnə"),
      v("Dəvəçi"),
      v("Güləh"),
      v("Günəşli"),
      v("Gəndov"),
      v("Hacıiskəndərli"),
      v("Hacıqaraqaşlı"),
      v("Kilvar"),
      v("Kyünçal"),
      v("Leyti"),
      v("Liman"),
      v("Ləcədi"),
      v("Meytablı"),
      v("Mollakamallı"),
      v("Mumlu"),
      v("Məliklər"),
      v("Nohurlar"),
      v("Padar"),
      v("Pirəbədil"),
      v("Pirəmsən"),
      v("Qaraçaylı"),
      v("Qazbabalı"),
      v("Qorğan"),
      v("Qızılqazma"),
      v("Qələgah"),
      v("Qəriblik"),
      v("Rəhimli"),
      v("Sarvan"),
      v("Sincanboyad"),
      v("Sumağava"),
      v("Sumağava Qazma"),
      v("Surra"),
      v("Söhbətli"),
      v("Taxtalar"),
      v("Təkyə"),
      v("Təzəkənd"),
      v("Udulu"),
      v("Uqah"),
      v("Uzunboyad"),
      v("Vələsli"),
      v("Xırdaoymaq"),
      v("Xəlfələr"),
      v("Xəlilli"),
      v("Yeləkəsən"),
      v("Zağlı"),
      v("Zeyvə"),
      v("Zöhrabkənd"),
      v("Zöhramı"),
      v("Çaraq"),
      v("Çayqaraqaşlı"),
      v("Çinarlar"),
      v("Çovurar"),
      v("Çuxurazəmi"),
      v("Çölquşçu"),
      v("Üzümlü"),
      v("İzmara"),
      v("Şahnəzərli"),
      v("Əmirxanlı"),
      v("Ərəblər"),
    ],
  },
  { name: "Şahbuz", tier: "REGION", places: [s("Badamlı")] },
  {
    name: "Şamaxı",
    tier: "REGION",
    places: [
      s("Aşkar"),
      s("Mədrəsə"),
      s("Sabir"),
      s("Yusif Məmmədəliyev"),
      s("Şəhriyar"),
      v("Cabanı"),
      v("Dəmirçi"),
      v("Meysəri"),
      v("Nağaraxana"),
      v("Çuxuryurd"),
    ],
  },
  { name: "Şuşa", tier: "REGION", places: [s("Turşsu")] },
  {
    name: "Şəmkir",
    tier: "REGION",
    places: [
      s("Barlıbağ"),
      s("Dəllər"),
      s("Füzuli"),
      s("Kür"),
      s("Səməd Vurğun"),
      s("Zəyəm"),
      s("Çinarlı"),
    ],
  },
  { name: "Şərur", tier: "REGION", places: [s("Şəfəq")] },
];

/** Yalnız respublika tabeli şəhərlər — sıralama və etiket üçün. */
export const CITIES: string[] = PLACES.filter((place) => place.tier === "CITY").map(
  (place) => place.name,
);

/** Yalnız rayonlar — sıralama və etiket üçün. */
export const REGIONS: string[] = PLACES.filter((place) => place.tier === "REGION").map(
  (place) => place.name,
);
