/**
 * Azərbaycanın rəsmi inzibati-ərazi bölgüsü.
 *
 * **Bu fayl generasiya olunur — əl ilə redaktə etmə.**
 * Mənbə: `prisma/az-admin-divisions.json`; generator:
 * `python scripts/build-locations-data.py`.
 *
 * Rəsmi mənbə — «İnzibati Ərazi Bölgüsü Təsnifatı, 2024», Azərbaycan
 * Respublikası Dövlət Statistika Komitəsi kollegiyasının 16.02.2024 tarixli
 * 2/2 nömrəli qərarı ilə təsdiq edilib, Milli Məclisin Aparatı ilə
 * razılaşdırılıb (https://e-qanun.az/framework/57325). Təsnifat 11 respublika
 * tabeli şəhər, 64 rayon, 12 şəhər rayonu, 262 qəsəbə və 4 244 kənd sayır.
 *
 * Səviyyələr `Location.kind` ilə verilir:
 * - `CITY` — istifadəçinin birinci seçimi: respublika tabeli şəhərlər və
 *   rayonlar. Rayon burada `DISTRICT` deyil, çünki axtarışda şəhərlərlə eyni
 *   pillədə seçilir (Quba, Qusar, Şəki…). `DISTRICT` yalnız şəhərin
 *   daxilindəki inzibati rayon deməkdir.
 * - `DISTRICT` — şəhərdaxili inzibati rayonlar: Bakının 12, Gəncənin 2 rayonu.
 * - `SETTLEMENT` — rəsmi qəsəbələr və rayon tabeli şəhərlər (Xırdalan, Xudat,
 *   Horadiz, Liman, Göytəpə, Qovlar, Dəliməmmədli).
 * - `VILLAGE` — kəndlər. Rəsmi siyahı 4 244 kənd sayır; burada yalnız əmlak
 *   bazarında elan verilənlər var — Bakıya yaxın rayonlarda tam, turizm və
 *   bağ bölgələrində seçmə. Tam siyahı seçim menyusunu yararsız edərdi.
 * - `NEIGHBORHOOD` — yaşayış massivləri və mikrorayonlar. **Rəsmi inzibati
 *   vahid deyil**, amma elanlarda gündəlik işlənir (Günəşli, Yeni Yasamal,
 *   8-ci km). Rəsmi qəsəbə siyahısının təmiz qalması üçün ayrıca səviyyədədir.
 * - `METRO` — Bakı metrosunun stansiyaları; valideyni Bakıdır.
 *
 * Slug-lar adlardan qurulur (`build-taxonomy-sql.ts`) və valideynin slug-ı ilə
 * prefikslənir, ona görə eyni adlı yerlər toqquşmur — «İstisu» həm Kəlbəcərdə,
 * həm Lənkəranda, həm Xaçmazda var.
 */

export const BAKU = "Bakı";

/** Şəhər/rayonun altındakı yaşayış məntəqəsi. */
export type ChildPlace = {
  name: string;
  kind: "SETTLEMENT" | "VILLAGE" | "NEIGHBORHOOD";
};

/** Şəhərdaxili inzibati rayon — yalnız Bakı və Gəncədə var. */
export type UrbanDistrict = {
  name: string;
  places: ChildPlace[];
};

/**
 * Birinci pillə: respublika tabeli şəhər və ya rayon.
 *
 * `tier` yalnız sıralama üçündür — bazada hər ikisi `kind="CITY"` olur, çünki
 * istifadəçi axtarışda onları eyni açılan siyahıdan seçir. Lənkəran, Şəki və
 * Yevlax rəsmi təsnifatda həm şəhər, həm eyniadlı rayondur; saytda tək qeyddir.
 */
export type TopLevelPlace = {
  name: string;
  tier: "CITY" | "REGION";
  /** Şəhərdaxili inzibati rayonlar. */
  districts?: UrbanDistrict[];
  /** Birbaşa alt yaşayış məntəqələri. */
  places?: ChildPlace[];
};

const s = (name: string): ChildPlace => ({ name, kind: "SETTLEMENT" });
const v = (name: string): ChildPlace => ({ name, kind: "VILLAGE" });
const n = (name: string): ChildPlace => ({ name, kind: "NEIGHBORHOOD" });

/**
 * Bakının 12 inzibati rayonu, 59 rəsmi qəsəbəsi və bazar massivləri.
 *
 * Rəsmi təsnifatda Nərimanov, Nəsimi və Yasamal rayonlarında **qəsəbə yoxdur**
 * — orada yalnız massiv adları işlənir, ona görə onlar `NEIGHBORHOOD`-dur.
 */
export const BAKU_DISTRICTS: UrbanDistrict[] = [
  {
    name: "Binəqədi",
    places: [
      s("28 May"),
      s("Biləcəri"),
      s("M.Ə.Rəsulzadə"),
      s("Sulutəpə"),
      s("Xocəsən"),
      n("8-ci kilometr"),
      n("9-cu mikrorayon"),
      n("Günəşli"),
    ],
  },
  {
    name: "Nərimanov",
    places: [n("Böyükşor"), n("Sovetski")],
  },
  {
    name: "Nəsimi",
    places: [
      n("1-ci mikrorayon"),
      n("2-ci mikrorayon"),
      n("3-cü mikrorayon"),
      n("4-cü mikrorayon"),
      n("5-ci mikrorayon"),
      n("6-cı mikrorayon"),
      n("7-ci mikrorayon"),
      n("8-ci mikrorayon"),
    ],
  },
  {
    name: "Nizami",
    places: [s("Keşlə"), n("Alatava")],
  },
  {
    name: "Qaradağ",
    places: [
      s("Baş Ələt"),
      s("Heybət"),
      s("Korgöz"),
      s("Kotal"),
      s("Lökbatan"),
      s("Müşviqabad"),
      s("Pirsaat"),
      s("Puta"),
      s("Qarakosa"),
      s("Qobustan"),
      s("Qızıldaş"),
      s("Sahil"),
      s("Sanqaçal"),
      s("Yeni Ələt"),
      s("Çeyildağ"),
      s("Ümid"),
      s("Şonqar"),
      s("Şubanı"),
      s("Şıxlar"),
      s("Ələt"),
    ],
  },
  {
    name: "Sabunçu",
    places: [
      s("Bakıxanov"),
      s("Balaxanı"),
      s("Bilgəh"),
      s("Kürdəxanı"),
      s("Maştağa"),
      s("Nardaran"),
      s("Pirşağı"),
      s("Ramana"),
      s("Zabrat"),
      n("Savalan"),
    ],
  },
  {
    name: "Səbail",
    places: [s("Badamdar"), s("Bibiheybət"), n("Bayıl"), n("İçərişəhər"), n("Şıxov")],
  },
  {
    name: "Suraxanı",
    places: [
      s("Bülbülə"),
      s("Hövsan"),
      s("Qaraçuxur"),
      s("Yeni Suraxanı"),
      s("Zığ"),
      s("Əmircan"),
      n("Bahar"),
      n("Yeni Günəşli"),
    ],
  },
  {
    name: "Xəzər",
    places: [
      s("Binə"),
      s("Buzovna"),
      s("Mərdəkan"),
      s("Qala"),
      s("Türkan"),
      s("Zirə"),
      s("Şağan"),
      s("Şüvəlan"),
      n("Dübəndi"),
    ],
  },
  {
    name: "Xətai",
    places: [s("Əhmədli"), n("Ağ şəhər"), n("Qara şəhər")],
  },
  {
    name: "Yasamal",
    places: [n("Yeni Yasamal")],
  },
  {
    name: "Pirallahı",
    places: [s("Gürgən"), s("Neft Daşları"), s("Çilov")],
  },
];

/** Bakı metrosunun stansiyaları — axtarışda ayrıca açar kimi işlənir. */
export const METRO_STATIONS: string[] = [
  "20 Yanvar",
  "28 May",
  "8 Noyabr",
  "Avtovağzal",
  "Azadlıq prospekti",
  "Bakmil",
  "Cəfər Cabbarlı",
  "Dərnəgül",
  "Elmlər Akademiyası",
  "Əhmədli",
  "Gənclik",
  "Həzi Aslanov",
  "İçərişəhər",
  "İnşaatçılar",
  "Koroğlu",
  "Qara Qarayev",
  "Memar Əcəmi",
  "Nəriman Nərimanov",
  "Neftçilər",
  "Nəsimi",
  "Nizami",
  "Sahil",
  "Ulduz",
  "Xalqlar Dostluğu",
  "Xocəsən",
  "Şah İsmayıl Xətai",
];

/**
 * Respublika tabeli şəhərlər və rayonlar bir siyahıdadır, çünki axtarışda
 * eyni açılan siyahıdan seçilir: əvvəl şəhərlər, sonra rayonlar.
 */
export const PLACES: TopLevelPlace[] = [
  // --- Respublika tabeli şəhərlər ---
  { name: BAKU, tier: "CITY", districts: BAKU_DISTRICTS },
  {
    name: "Gəncə",
    tier: "CITY",
    districts: [{ name: "Kəpəz", places: [] }, { name: "Nizami", places: [] }],
    places: [s("Cavadxan"), s("Göygöl"), s("Hacıkənd"), s("Məhsəti"), s("Natəvan"), s("Sadıllı"), s("Şıxzamanlı")],
  },
  { name: "Sumqayıt", tier: "CITY", places: [s("Corat"), s("Hacı Zeynalabdin")] },
  { name: "Mingəçevir", tier: "CITY" },
  { name: "Şirvan", tier: "CITY", places: [s("Bayramlı"), s("Hacıqəhrəmanlı")] },
  { name: "Naftalan", tier: "CITY" },
  { name: "Naxçıvan", tier: "CITY", places: [s("Əliabad")] },
  { name: "Xankəndi", tier: "CITY", places: [s("Kərkicahan")] },
  {
    name: "Lənkəran",
    tier: "CITY",
    places: [
      s("Aşağı Nüvədi"),
      s("Balıqçılar"),
      s("Gərmətük"),
      s("Haftoni"),
      s("Hirkan"),
      s("Liman"),
      s("Nərimanabad"),
      s("İstisu"),
      s("Şirinsu"),
      v("Boladı"),
      v("Girdəni"),
      v("Mamusta"),
      v("Separadi"),
      v("Vilvan"),
    ],
  },
  {
    name: "Şəki",
    tier: "CITY",
    places: [
      s("Turan"),
      s("Çələbixan"),
      v("Baş Göynük"),
      v("Baş Şabalıd"),
      v("Bideyiz"),
      v("Daşüz"),
      v("Kiş"),
      v("Oxud"),
      v("Qayabaşı"),
      v("İnçə"),
    ],
  },
  { name: "Yevlax", tier: "CITY", places: [s("Aran"), s("Duzdağ"), s("Meyvəli")] },

  // --- Rayonlar ---
  {
    name: "Abşeron",
    tier: "REGION",
    places: [
      s("Aşağı Güzdək"),
      s("Ceyranbatan"),
      s("Digah"),
      s("Güzdək"),
      s("Hökməli"),
      s("Mehdiabad"),
      s("Qobu"),
      s("Saray"),
      s("Xırdalan"),
      s("Şəfəq"),
      v("Fatmayı"),
      v("Görədil"),
      v("Masazır"),
      v("Məmmədli"),
      v("Novxanı"),
      v("Pirəkəşkül"),
      v("Qobustan"),
    ],
  },
  {
    name: "Astara",
    tier: "REGION",
    places: [
      s("Kijəbə"),
      s("Ərçivan"),
      v("Maşxan"),
      v("Pensər"),
      v("Sım"),
    ],
  },
  { name: "Ağcabədi", tier: "REGION", places: [s("Hindarx")] },
  {
    name: "Ağdam",
    tier: "REGION",
    places: [
      s("Acarlı"),
      s("Birinci Alıbəyli"),
      s("Birinci Baharlı"),
      s("Birinci Dördyol"),
      s("Birinci Quzanlı"),
      s("Bənövşələr"),
      s("Qasımbəyli"),
      s("Quzanlı"),
      s("Səfərli"),
      s("Təzəkənd"),
      s("İkinci Alıbəyli"),
      s("İkinci Baharlı"),
      s("İkinci Dördyol"),
      s("İmamqulubəyli"),
    ],
  },
  { name: "Ağdaş", tier: "REGION", places: [s("Ləki"), s("Türyançay")] },
  { name: "Ağdərə", tier: "REGION", places: [s("Şıxarx")] },
  {
    name: "Ağstafa",
    tier: "REGION",
    places: [
      s("Ceyrançöl"),
      s("Həzi Aslanov"),
      s("Poylu"),
      s("Qarayazı"),
      s("Saloğlu"),
      s("Soyuqbulaq"),
      s("Soyuqbulaqlar"),
      s("Vurğun"),
      s("Şəkərli"),
    ],
  },
  { name: "Ağsu", tier: "REGION" },
  { name: "Babək", tier: "REGION", places: [s("Cəhri"), s("Nehrəm")] },
  {
    name: "Balakən",
    tier: "REGION",
    places: [
      s("Qabaqçöl"),
      v("Katex"),
      v("Mahamalar"),
      v("Talalar"),
    ],
  },
  {
    name: "Beyləqan",
    tier: "REGION",
    places: [
      s("Bahar"),
      s("Baharabad"),
      s("Bolsulu"),
      s("Günəş"),
      s("Mayak"),
      s("Mil"),
      s("Milabad"),
      s("Orconikidze"),
      s("Qəhrəmanlı"),
      s("Sarısu"),
      s("Türklər"),
      s("Yeni Mil"),
      s("Yuxarı Aran"),
      s("Örənqala"),
      s("Şəfəq"),
      s("Şərq"),
    ],
  },
  { name: "Biləsuvar", tier: "REGION" },
  { name: "Bərdə", tier: "REGION" },
  { name: "Culfa", tier: "REGION" },
  {
    name: "Cəbrayıl",
    tier: "REGION",
    places: [
      s("Mahmudlu"),
      s("Qumlaq"),
      s("Xudafərin"),
      s("Xələfli"),
    ],
  },
  { name: "Cəlilabad", tier: "REGION", places: [s("Göytəpə"), s("Novoqolovka")] },
  {
    name: "Daşkəsən",
    tier: "REGION",
    places: [
      s("Alunitdağ"),
      s("Quşçu"),
      s("Quşçu körpüsü"),
      s("Yuxarı Daşkəsən"),
      v("Xoşbulaq"),
      v("Zəylik"),
    ],
  },
  {
    name: "Füzuli",
    tier: "REGION",
    places: [
      s("1 №-li Qayıdış"),
      s("10 №-li Qayıdış"),
      s("11 №-li Qayıdış"),
      s("2 №-li Qayıdış"),
      s("3 №-li Qayıdış"),
      s("4 №-li Qayıdış"),
      s("5 №-li Qayıdış"),
      s("6 №-li Qayıdış"),
      s("7 №-li Qayıdış"),
      s("8 №-li Qayıdış"),
      s("9 №-li Qayıdış"),
      s("Beşinci Zobucuq"),
      s("Birinci Zobucuq"),
      s("Dördüncü Zobucuq"),
      s("Horadiz"),
      s("Üçüncü Zobucuq"),
      s("İkinci Zobucuq"),
    ],
  },
  {
    name: "Goranboy",
    tier: "REGION",
    places: [
      s("Aşağı Ağcakənd"),
      s("Dəliməmmədli"),
      s("Goran"),
      s("Kürəkçay"),
      s("Qazanbulaq"),
      s("Qızılhacılı"),
      s("Yuxarı Ağcakənd"),
    ],
  },
  {
    name: "Göygöl",
    tier: "REGION",
    places: [
      s("Ağdağ"),
      s("Aşağı Zurnabad"),
      s("Bəhrambağ"),
      s("Firuzabad"),
      s("Hacıməlik"),
      s("Qızılqaya"),
      v("Zurnabad"),
      v("Çaykənd"),
    ],
  },
  { name: "Göyçay", tier: "REGION" },
  {
    name: "Gədəbəy",
    tier: "REGION",
    places: [
      v("Arıqıran"),
      v("Düzyurd"),
      v("Slavyanka"),
      v("Söyüdlü"),
    ],
  },
  {
    name: "Hacıqabul",
    tier: "REGION",
    places: [
      s("Balıqçı"),
      s("Muğan"),
      s("Navahı"),
      s("Padar"),
      s("Pirsaat"),
    ],
  },
  { name: "İmişli", tier: "REGION", places: [s("Bəhrəmtəpə"), s("Vətəgə")] },
  {
    name: "İsmayıllı",
    tier: "REGION",
    places: [
      s("Basqal"),
      s("Lahıc"),
      v("Buynuz"),
      v("Diyallı"),
      v("Mollaisaqlı"),
      v("Talıstan"),
      v("Topçu"),
      v("İvanovka"),
    ],
  },
  { name: "Kürdəmir", tier: "REGION", places: [s("Karrar"), s("Qarabucaq")] },
  { name: "Kəlbəcər", tier: "REGION", places: [s("İstisu")] },
  { name: "Kəngərli", tier: "REGION", places: [s("Qıvraq")] },
  { name: "Laçın", tier: "REGION", places: [s("Qayğı")] },
  { name: "Lerik", tier: "REGION", places: [v("Cəngəmiran"), v("Kəlvəz")] },
  {
    name: "Masallı",
    tier: "REGION",
    places: [
      s("Boradigah"),
      s("Ərkivan"),
      v("Qızılağac"),
      v("Təzə Alvadı"),
      v("Xıl"),
    ],
  },
  { name: "Neftçala", tier: "REGION", places: [s("Bankə"), s("Həsənabad"), s("Xıllı")] },
  { name: "Ordubad", tier: "REGION", places: [s("Ağdərə"), s("Parağaçay"), s("Şəhriyar")] },
  {
    name: "Oğuz",
    tier: "REGION",
    places: [
      v("Baş Daşağıl"),
      v("Calut"),
      v("Kərimli"),
      v("Xaçmaz"),
    ],
  },
  {
    name: "Qax",
    tier: "REGION",
    places: [
      v("Ləkit"),
      v("Qaxbaş"),
      v("Sarıbaş"),
      v("Zərnə"),
      v("İlisu"),
      v("Əmbərçay"),
    ],
  },
  {
    name: "Qazax",
    tier: "REGION",
    places: [
      v("Aslanbəyli"),
      v("Daş Salahlı"),
      v("Kəmərli"),
      v("Yuxarı Salahlı"),
    ],
  },
  {
    name: "Qobustan",
    tier: "REGION",
    places: [
      s("Üzümçü"),
      v("Bədəlli"),
      v("Bəklə"),
      v("Ceyrankeçməz"),
      v("Cəmcəmli"),
      v("Cəngi"),
      v("Cəyirli"),
      v("Damlamaca"),
      v("Dağ Kolanı"),
      v("Dərəkənd"),
      v("Göydərə"),
      v("Nabur"),
      v("Nardaran"),
      v("Poladlı"),
      v("Qaracüzlü"),
      v("Qurbançı"),
      v("Sündü"),
      v("Sədəfli"),
      v("Təklə"),
      v("Təklə Mirzəbaba"),
      v("Təsi"),
      v("Xilmilli"),
      v("Yekəxana"),
      v("Çay Qurbançı"),
      v("Çelov"),
      v("Çuxanlı"),
      v("İlanlı"),
      v("Şıxlar"),
      v("Şıxzahırlı"),
      v("Ərəbqədim"),
      v("Ərəbşahverdi"),
      v("Ərəbşalbaş"),
    ],
  },
  {
    name: "Quba",
    tier: "REGION",
    places: [
      s("Barlı"),
      s("Bağbanlı"),
      s("Gənclər"),
      s("Qaraçay"),
      s("Qonaqkənd"),
      s("Qırmızı Qəsəbə"),
      s("Zərdabi"),
      v("Afurca"),
      v("Alpan"),
      v("Amsar"),
      v("Ağbil"),
      v("Birinci Nügədi"),
      v("Buduq"),
      v("Cek"),
      v("Cimi"),
      v("Küpçal"),
      v("Rustov"),
      v("Təngəaltı"),
      v("Xaşı"),
      v("Xucbala"),
      v("Xınalıq"),
      v("Yerfi"),
      v("İkinci Nügədi"),
    ],
  },
  { name: "Qubadlı", tier: "REGION" },
  {
    name: "Qusar",
    tier: "REGION",
    places: [
      s("Samur"),
      v("Hil"),
      v("Həzrə"),
      v("Kuzun"),
      v("Laza"),
      v("Suvacal"),
      v("Urva"),
      v("Yuxarı Ləgər"),
      v("Əniq"),
    ],
  },
  {
    name: "Qəbələ",
    tier: "REGION",
    places: [
      s("Bum"),
      s("Nic"),
      s("Vəndam"),
      v("Hacıalılı"),
      v("Həzrə"),
      v("Laza"),
      v("Mıxlıqovaq"),
      v("Qəmərvan"),
      v("Savalan"),
      v("Tüntül"),
      v("Yengicə"),
      v("Zarağan"),
      v("Çuxur Qəbələ"),
    ],
  },
  { name: "Saatlı", tier: "REGION" },
  { name: "Sabirabad", tier: "REGION" },
  { name: "Salyan", tier: "REGION", places: [s("Qaraçala"), s("Qırx Çıraq")] },
  {
    name: "Samux",
    tier: "REGION",
    places: [
      s("Alabaşlı"),
      s("Qaraarx"),
      s("Qaraağaclı"),
      s("Qarayeri"),
      s("Yenibağ"),
      s("İnstitut"),
    ],
  },
  {
    name: "Siyəzən",
    tier: "REGION",
    places: [
      s("Gilgilçay"),
      v("Balaca Həmyə"),
      v("Beşdam"),
      v("Böyük Həmyə"),
      v("Cəndəhar"),
      v("Dağ Quşçu"),
      v("Daşlı Çalğan"),
      v("Dərə Zarat"),
      v("Eynibulaq"),
      v("Hacışəkər"),
      v("Kolanı"),
      v("Köhnə Quşçu"),
      v("Künövşə"),
      v("Müşkülqazma"),
      v("Məşrif"),
      v("Nardaran"),
      v("Orta Çalğan"),
      v("Qalaaltı"),
      v("Qalaşıxı"),
      v("Qaragöz"),
      v("Qozağacı"),
      v("Qərəh"),
      v("Sağolcan"),
      v("Sədan"),
      v("Tuğay"),
      v("Yanıq Ələz"),
      v("Yenikənd"),
      v("Yuxarı Ələz"),
      v("Zarat"),
      v("Çarxana"),
      v("Əlməkolu"),
      v("Ərziküş"),
    ],
  },
  { name: "Sədərək", tier: "REGION", places: [s("Heydərabad")] },
  { name: "Tovuz", tier: "REGION", places: [s("Qovlar"), v("Bozalqanlı"), v("Əyyublu")] },
  { name: "Tərtər", tier: "REGION" },
  { name: "Ucar", tier: "REGION" },
  {
    name: "Xaçmaz",
    tier: "REGION",
    places: [
      s("Arzu"),
      s("Aşağı Ləgər"),
      s("Dalğalı"),
      s("Günəşli"),
      s("Meşəli"),
      s("Sahillər"),
      s("Samurçay"),
      s("Turist"),
      s("Xudat"),
      s("Yeni Həyat"),
      s("İstisu"),
      s("Şimal"),
      s("Şollar"),
      v("Bostançı"),
      v("Hülövlü"),
      v("Nabran"),
      v("Nərəcan"),
      v("Qaracik"),
      v("Yalama"),
    ],
  },
  { name: "Xocalı", tier: "REGION", places: [s("Əsgəran")] },
  { name: "Xocavənd", tier: "REGION", places: [s("Hadrut"), s("Qırmızı Bazar")] },
  {
    name: "Xızı",
    tier: "REGION",
    places: [
      s("Altıağac"),
      s("Giləzi"),
      s("Şorabad"),
      v("Ağdərə"),
      v("Baxışlı"),
      v("Bəyəhmədyurd"),
      v("Dizəvər"),
      v("Fındığan"),
      v("Güneyqışlaq"),
      v("Məşədi Həsən"),
      v("Qarabulaq"),
      v("Qars"),
      v("Qasımkənd"),
      v("Qızılqazma"),
      v("Safbulaq"),
      v("Sitalçay"),
      v("Tudar"),
      v("Türkoba"),
      v("Tıxlı"),
      v("Təzəkənd"),
      v("Vərdah"),
      v("Xələnc"),
      v("Yarımca"),
      v("Yaşma"),
      v("Yeni Yaşma"),
      v("Yuxarı Əngilan"),
      v("Əmbizlər"),
      v("Əngilan"),
    ],
  },
  { name: "Yardımlı", tier: "REGION" },
  {
    name: "Zaqatala",
    tier: "REGION",
    places: [
      s("Əliabad"),
      v("Car"),
      v("Mazıx"),
      v("Muxax"),
      v("Qandax"),
    ],
  },
  {
    name: "Zəngilan",
    tier: "REGION",
    places: [
      s("Ağ oyuq"),
      s("Ağbənd"),
      s("Bartaz"),
      s("Həkəri"),
      s("Mincivan"),
    ],
  },
  { name: "Zərdab", tier: "REGION", places: [s("Bəyimli")] },
  {
    name: "Şabran",
    tier: "REGION",
    places: [
      v("Aygünlü"),
      v("Ağalıq"),
      v("Ağbaş"),
      v("Bilici Qorğan"),
      v("Borbor"),
      v("Ceyranlı"),
      v("Dağ Bilici"),
      v("Daşlıyataq"),
      v("Düz Bilici"),
      v("Dəhnə"),
      v("Dəvəçi"),
      v("Güləh"),
      v("Günəşli"),
      v("Gəndov"),
      v("Hacıiskəndərli"),
      v("Hacıqaraqaşlı"),
      v("Kilvar"),
      v("Kyünçal"),
      v("Leyti"),
      v("Liman"),
      v("Ləcədi"),
      v("Meytablı"),
      v("Mollakamallı"),
      v("Mumlu"),
      v("Məliklər"),
      v("Nohurlar"),
      v("Padar"),
      v("Pirəbədil"),
      v("Pirəmsən"),
      v("Qaraçaylı"),
      v("Qazbabalı"),
      v("Qorğan"),
      v("Qızılqazma"),
      v("Qələgah"),
      v("Qəriblik"),
      v("Rəhimli"),
      v("Sarvan"),
      v("Sincanboyad"),
      v("Sumağava"),
      v("Sumağava Qazma"),
      v("Surra"),
      v("Söhbətli"),
      v("Taxtalar"),
      v("Təkyə"),
      v("Təzəkənd"),
      v("Udulu"),
      v("Uqah"),
      v("Uzunboyad"),
      v("Vələsli"),
      v("Xırdaoymaq"),
      v("Xəlfələr"),
      v("Xəlilli"),
      v("Yeləkəsən"),
      v("Zağlı"),
      v("Zeyvə"),
      v("Zöhrabkənd"),
      v("Zöhramı"),
      v("Çaraq"),
      v("Çayqaraqaşlı"),
      v("Çinarlar"),
      v("Çovurar"),
      v("Çuxurazəmi"),
      v("Çölquşçu"),
      v("Üzümlü"),
      v("İzmara"),
      v("Şahnəzərli"),
      v("Əmirxanlı"),
      v("Ərəblər"),
    ],
  },
  { name: "Şahbuz", tier: "REGION", places: [s("Badamlı")] },
  {
    name: "Şamaxı",
    tier: "REGION",
    places: [
      s("Aşkar"),
      s("Mədrəsə"),
      s("Sabir"),
      s("Yusif Məmmədəliyev"),
      s("Şəhriyar"),
      v("Cabanı"),
      v("Dəmirçi"),
      v("Meysəri"),
      v("Nağaraxana"),
      v("Çuxuryurd"),
    ],
  },
  { name: "Şuşa", tier: "REGION", places: [s("Turşsu")] },
  {
    name: "Şəmkir",
    tier: "REGION",
    places: [
      s("Barlıbağ"),
      s("Dəllər"),
      s("Füzuli"),
      s("Kür"),
      s("Səməd Vurğun"),
      s("Zəyəm"),
      s("Çinarlı"),
    ],
  },
  { name: "Şərur", tier: "REGION", places: [s("Şəfəq")] },
];

/** Yalnız respublika tabeli şəhərlər — sıralama və etiket üçün. */
export const CITIES: string[] = PLACES.filter((place) => place.tier === "CITY").map(
  (place) => place.name,
);

/** Yalnız rayonlar — sıralama və etiket üçün. */
export const REGIONS: string[] = PLACES.filter((place) => place.tier === "REGION").map(
  (place) => place.name,
);
