-- Avtomatik yaradılıb: npm run db:taxonomy:build
-- Mövcud sətirlərə toxunmur; yalnız çatışmayanları əlavə edir və adları sinxronlaşdırır.

PRAGMA foreign_keys = ON;

-- Əmlak növləri
INSERT OR IGNORE INTO "PropertyType" ("id","name","slug","description","icon","order","isActive") VALUES ('type_menziller','Mənzillər','menziller',NULL,'Building2',10,1);
UPDATE "PropertyType" SET "name"='Mənzillər', "order"=10 WHERE "slug"='menziller';
INSERT OR IGNORE INTO "PropertyType" ("id","name","slug","description","icon","order","isActive") VALUES ('type_yeni-tikili','Yeni tikili','yeni-tikili',NULL,'Building',20,1);
UPDATE "PropertyType" SET "name"='Yeni tikili', "order"=20 WHERE "slug"='yeni-tikili';
INSERT OR IGNORE INTO "PropertyType" ("id","name","slug","description","icon","order","isActive") VALUES ('type_kohne-tikili','Köhnə tikili','kohne-tikili',NULL,'Building',30,1);
UPDATE "PropertyType" SET "name"='Köhnə tikili', "order"=30 WHERE "slug"='kohne-tikili';
INSERT OR IGNORE INTO "PropertyType" ("id","name","slug","description","icon","order","isActive") VALUES ('type_heyet-evleri','Həyət evi / Villa','heyet-evleri',NULL,'Home',40,1);
UPDATE "PropertyType" SET "name"='Həyət evi / Villa', "order"=40 WHERE "slug"='heyet-evleri';
INSERT OR IGNORE INTO "PropertyType" ("id","name","slug","description","icon","order","isActive") VALUES ('type_villalar','Villalar','villalar',NULL,'Home',50,1);
UPDATE "PropertyType" SET "name"='Villalar', "order"=50 WHERE "slug"='villalar';
INSERT OR IGNORE INTO "PropertyType" ("id","name","slug","description","icon","order","isActive") VALUES ('type_bag-evleri','Bağ evləri','bag-evleri',NULL,'TreePine',60,1);
UPDATE "PropertyType" SET "name"='Bağ evləri', "order"=60 WHERE "slug"='bag-evleri';
INSERT OR IGNORE INTO "PropertyType" ("id","name","slug","description","icon","order","isActive") VALUES ('type_torpaq','Torpaq sahəsi','torpaq',NULL,'LandPlot',70,1);
UPDATE "PropertyType" SET "name"='Torpaq sahəsi', "order"=70 WHERE "slug"='torpaq';
INSERT OR IGNORE INTO "PropertyType" ("id","name","slug","description","icon","order","isActive") VALUES ('type_obyektler','Obyekt','obyektler',NULL,'Store',80,1);
UPDATE "PropertyType" SET "name"='Obyekt', "order"=80 WHERE "slug"='obyektler';
INSERT OR IGNORE INTO "PropertyType" ("id","name","slug","description","icon","order","isActive") VALUES ('type_ofisler','Ofis','ofisler',NULL,'Briefcase',90,1);
UPDATE "PropertyType" SET "name"='Ofis', "order"=90 WHERE "slug"='ofisler';
INSERT OR IGNORE INTO "PropertyType" ("id","name","slug","description","icon","order","isActive") VALUES ('type_qarajlar','Qaraj','qarajlar',NULL,'Car',100,1);
UPDATE "PropertyType" SET "name"='Qaraj', "order"=100 WHERE "slug"='qarajlar';
INSERT OR IGNORE INTO "PropertyType" ("id","name","slug","description","icon","order","isActive") VALUES ('type_mini-otel','Mini otel / Xostel','mini-otel',NULL,'Hotel',110,1);
UPDATE "PropertyType" SET "name"='Mini otel / Xostel', "order"=110 WHERE "slug"='mini-otel';
INSERT OR IGNORE INTO "PropertyType" ("id","name","slug","description","icon","order","isActive") VALUES ('type_istirahet-merkezleri','İstirahət mərkəzi','istirahet-merkezleri',NULL,'Palmtree',120,1);
UPDATE "PropertyType" SET "name"='İstirahət mərkəzi', "order"=120 WHERE "slug"='istirahet-merkezleri';
INSERT OR IGNORE INTO "PropertyType" ("id","name","slug","description","icon","order","isActive") VALUES ('type_konteyner-evler','Konteyner ev','konteyner-evler',NULL,'Container',130,1);
UPDATE "PropertyType" SET "name"='Konteyner ev', "order"=130 WHERE "slug"='konteyner-evler';
INSERT OR IGNORE INTO "PropertyType" ("id","name","slug","description","icon","order","isActive") VALUES ('type_a-frame-evler','A-frame ev','a-frame-evler',NULL,'Triangle',140,1);
UPDATE "PropertyType" SET "name"='A-frame ev', "order"=140 WHERE "slug"='a-frame-evler';
INSERT OR IGNORE INTO "PropertyType" ("id","name","slug","description","icon","order","isActive") VALUES ('type_xarici-emlak','Xarici əmlak','xarici-emlak',NULL,'Globe',150,1);
UPDATE "PropertyType" SET "name"='Xarici əmlak', "order"=150 WHERE "slug"='xarici-emlak';

-- Xüsusiyyətlər və ödəniş şərtləri
INSERT OR IGNORE INTO "Feature" ("id","name","slug","icon","group","order") VALUES ('feat_qaz','Qaz','qaz',NULL,'UTILITY',10);
UPDATE "Feature" SET "name"='Qaz', "group"='UTILITY', "order"=10 WHERE "slug"='qaz';
INSERT OR IGNORE INTO "Feature" ("id","name","slug","icon","group","order") VALUES ('feat_su','Su','su',NULL,'UTILITY',20);
UPDATE "Feature" SET "name"='Su', "group"='UTILITY', "order"=20 WHERE "slug"='su';
INSERT OR IGNORE INTO "Feature" ("id","name","slug","icon","group","order") VALUES ('feat_isiq','İşıq','isiq',NULL,'UTILITY',30);
UPDATE "Feature" SET "name"='İşıq', "group"='UTILITY', "order"=30 WHERE "slug"='isiq';
INSERT OR IGNORE INTO "Feature" ("id","name","slug","icon","group","order") VALUES ('feat_telefon','Telefon','telefon',NULL,'UTILITY',40);
UPDATE "Feature" SET "name"='Telefon', "group"='UTILITY', "order"=40 WHERE "slug"='telefon';
INSERT OR IGNORE INTO "Feature" ("id","name","slug","icon","group","order") VALUES ('feat_internet','İnternet','internet',NULL,'UTILITY',50);
UPDATE "Feature" SET "name"='İnternet', "group"='UTILITY', "order"=50 WHERE "slug"='internet';
INSERT OR IGNORE INTO "Feature" ("id","name","slug","icon","group","order") VALUES ('feat_kabel-tv','Kabel TV','kabel-tv',NULL,'UTILITY',60);
UPDATE "Feature" SET "name"='Kabel TV', "group"='UTILITY', "order"=60 WHERE "slug"='kabel-tv';
INSERT OR IGNORE INTO "Feature" ("id","name","slug","icon","group","order") VALUES ('feat_kanalizasiya','Kanalizasiya','kanalizasiya',NULL,'UTILITY',70);
UPDATE "Feature" SET "name"='Kanalizasiya', "group"='UTILITY', "order"=70 WHERE "slug"='kanalizasiya';
INSERT OR IGNORE INTO "Feature" ("id","name","slug","icon","group","order") VALUES ('feat_lift','Lift','lift',NULL,'INDOOR',10);
UPDATE "Feature" SET "name"='Lift', "group"='INDOOR', "order"=10 WHERE "slug"='lift';
INSERT OR IGNORE INTO "Feature" ("id","name","slug","icon","group","order") VALUES ('feat_pvc-pencere','PVC pəncərə','pvc-pencere',NULL,'INDOOR',20);
UPDATE "Feature" SET "name"='PVC pəncərə', "group"='INDOOR', "order"=20 WHERE "slug"='pvc-pencere';
INSERT OR IGNORE INTO "Feature" ("id","name","slug","icon","group","order") VALUES ('feat_balkon','Balkon','balkon',NULL,'INDOOR',30);
UPDATE "Feature" SET "name"='Balkon', "group"='INDOOR', "order"=30 WHERE "slug"='balkon';
INSERT OR IGNORE INTO "Feature" ("id","name","slug","icon","group","order") VALUES ('feat_kombi','Kombi','kombi',NULL,'INDOOR',40);
UPDATE "Feature" SET "name"='Kombi', "group"='INDOOR', "order"=40 WHERE "slug"='kombi';
INSERT OR IGNORE INTO "Feature" ("id","name","slug","icon","group","order") VALUES ('feat_merkezi-isitme','Mərkəzi qızdırıcı sistem','merkezi-isitme',NULL,'INDOOR',50);
UPDATE "Feature" SET "name"='Mərkəzi qızdırıcı sistem', "group"='INDOOR', "order"=50 WHERE "slug"='merkezi-isitme';
INSERT OR IGNORE INTO "Feature" ("id","name","slug","icon","group","order") VALUES ('feat_kondisioner','Kondisioner','kondisioner',NULL,'INDOOR',60);
UPDATE "Feature" SET "name"='Kondisioner', "group"='INDOOR', "order"=60 WHERE "slug"='kondisioner';
INSERT OR IGNORE INTO "Feature" ("id","name","slug","icon","group","order") VALUES ('feat_metbex-mebeli','Mətbəx mebeli','metbex-mebeli',NULL,'INDOOR',70);
UPDATE "Feature" SET "name"='Mətbəx mebeli', "group"='INDOOR', "order"=70 WHERE "slug"='metbex-mebeli';
INSERT OR IGNORE INTO "Feature" ("id","name","slug","icon","group","order") VALUES ('feat_esyali','Əşyalı','esyali',NULL,'INDOOR',80);
UPDATE "Feature" SET "name"='Əşyalı', "group"='INDOOR', "order"=80 WHERE "slug"='esyali';
INSERT OR IGNORE INTO "Feature" ("id","name","slug","icon","group","order") VALUES ('feat_duzelme','Düzəlmə','duzelme',NULL,'INDOOR',90);
UPDATE "Feature" SET "name"='Düzəlmə', "group"='INDOOR', "order"=90 WHERE "slug"='duzelme';
INSERT OR IGNORE INTO "Feature" ("id","name","slug","icon","group","order") VALUES ('feat_kamin','Kamin','kamin',NULL,'INDOOR',100);
UPDATE "Feature" SET "name"='Kamin', "group"='INDOOR', "order"=100 WHERE "slug"='kamin';
INSERT OR IGNORE INTO "Feature" ("id","name","slug","icon","group","order") VALUES ('feat_hovuz','Hovuz','hovuz',NULL,'OUTDOOR',10);
UPDATE "Feature" SET "name"='Hovuz', "group"='OUTDOOR', "order"=10 WHERE "slug"='hovuz';
INSERT OR IGNORE INTO "Feature" ("id","name","slug","icon","group","order") VALUES ('feat_avtodayanacaq','Avtodayanacaq','avtodayanacaq',NULL,'OUTDOOR',20);
UPDATE "Feature" SET "name"='Avtodayanacaq', "group"='OUTDOOR', "order"=20 WHERE "slug"='avtodayanacaq';
INSERT OR IGNORE INTO "Feature" ("id","name","slug","icon","group","order") VALUES ('feat_qaraj','Qaraj','qaraj',NULL,'OUTDOOR',30);
UPDATE "Feature" SET "name"='Qaraj', "group"='OUTDOOR', "order"=30 WHERE "slug"='qaraj';
INSERT OR IGNORE INTO "Feature" ("id","name","slug","icon","group","order") VALUES ('feat_heyet','Həyət','heyet',NULL,'OUTDOOR',40);
UPDATE "Feature" SET "name"='Həyət', "group"='OUTDOOR', "order"=40 WHERE "slug"='heyet';
INSERT OR IGNORE INTO "Feature" ("id","name","slug","icon","group","order") VALUES ('feat_bag-sahesi','Bağ sahəsi','bag-sahesi',NULL,'OUTDOOR',50);
UPDATE "Feature" SET "name"='Bağ sahəsi', "group"='OUTDOOR', "order"=50 WHERE "slug"='bag-sahesi';
INSERT OR IGNORE INTO "Feature" ("id","name","slug","icon","group","order") VALUES ('feat_hamam','Hamam / sauna','hamam',NULL,'OUTDOOR',60);
UPDATE "Feature" SET "name"='Hamam / sauna', "group"='OUTDOOR', "order"=60 WHERE "slug"='hamam';
INSERT OR IGNORE INTO "Feature" ("id","name","slug","icon","group","order") VALUES ('feat_mangal','Mangal yeri','mangal',NULL,'OUTDOOR',70);
UPDATE "Feature" SET "name"='Mangal yeri', "group"='OUTDOOR', "order"=70 WHERE "slug"='mangal';
INSERT OR IGNORE INTO "Feature" ("id","name","slug","icon","group","order") VALUES ('feat_deniz-menzeresi','Dəniz mənzərəsi','deniz-menzeresi',NULL,'OUTDOOR',80);
UPDATE "Feature" SET "name"='Dəniz mənzərəsi', "group"='OUTDOOR', "order"=80 WHERE "slug"='deniz-menzeresi';
INSERT OR IGNORE INTO "Feature" ("id","name","slug","icon","group","order") VALUES ('feat_muhafize','Mühafizə','muhafize',NULL,'SECURITY',10);
UPDATE "Feature" SET "name"='Mühafizə', "group"='SECURITY', "order"=10 WHERE "slug"='muhafize';
INSERT OR IGNORE INTO "Feature" ("id","name","slug","icon","group","order") VALUES ('feat_kamera','Video müşahidə','kamera',NULL,'SECURITY',20);
UPDATE "Feature" SET "name"='Video müşahidə', "group"='SECURITY', "order"=20 WHERE "slug"='kamera';
INSERT OR IGNORE INTO "Feature" ("id","name","slug","icon","group","order") VALUES ('feat_domofon','Domofon','domofon',NULL,'SECURITY',30);
UPDATE "Feature" SET "name"='Domofon', "group"='SECURITY', "order"=30 WHERE "slug"='domofon';
INSERT OR IGNORE INTO "Feature" ("id","name","slug","icon","group","order") VALUES ('feat_siqnalizasiya','Siqnalizasiya','siqnalizasiya',NULL,'SECURITY',40);
UPDATE "Feature" SET "name"='Siqnalizasiya', "group"='SECURITY', "order"=40 WHERE "slug"='siqnalizasiya';
INSERT OR IGNORE INTO "Feature" ("id","name","slug","icon","group","order") VALUES ('feat_bagli-erazi','Bağlı ərazi','bagli-erazi',NULL,'SECURITY',50);
UPDATE "Feature" SET "name"='Bağlı ərazi', "group"='SECURITY', "order"=50 WHERE "slug"='bagli-erazi';
INSERT OR IGNORE INTO "Feature" ("id","name","slug","icon","group","order") VALUES ('feat_ipoteka','İpoteka','ipoteka',NULL,'PAYMENT',10);
UPDATE "Feature" SET "name"='İpoteka', "group"='PAYMENT', "order"=10 WHERE "slug"='ipoteka';
INSERT OR IGNORE INTO "Feature" ("id","name","slug","icon","group","order") VALUES ('feat_hazir-ipoteka','Hazır ipoteka','hazir-ipoteka',NULL,'PAYMENT',20);
UPDATE "Feature" SET "name"='Hazır ipoteka', "group"='PAYMENT', "order"=20 WHERE "slug"='hazir-ipoteka';
INSERT OR IGNORE INTO "Feature" ("id","name","slug","icon","group","order") VALUES ('feat_kredit','Kredit','kredit',NULL,'PAYMENT',30);
UPDATE "Feature" SET "name"='Kredit', "group"='PAYMENT', "order"=30 WHERE "slug"='kredit';
INSERT OR IGNORE INTO "Feature" ("id","name","slug","icon","group","order") VALUES ('feat_faizsiz-kredit','Faizsiz kredit','faizsiz-kredit',NULL,'PAYMENT',40);
UPDATE "Feature" SET "name"='Faizsiz kredit', "group"='PAYMENT', "order"=40 WHERE "slug"='faizsiz-kredit';
INSERT OR IGNORE INTO "Feature" ("id","name","slug","icon","group","order") VALUES ('feat_taksit','Taksit','taksit',NULL,'PAYMENT',50);
UPDATE "Feature" SET "name"='Taksit', "group"='PAYMENT', "order"=50 WHERE "slug"='taksit';
INSERT OR IGNORE INTO "Feature" ("id","name","slug","icon","group","order") VALUES ('feat_barter','Barter','barter',NULL,'PAYMENT',60);
UPDATE "Feature" SET "name"='Barter', "group"='PAYMENT', "order"=60 WHERE "slug"='barter';

-- Şəhərlər
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_baki','Bakı','baki','CITY',NULL,0);
UPDATE "Location" SET "name"='Bakı', "kind"='CITY', "order"=0 WHERE "slug"='baki';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_gence','Gəncə','gence','CITY',NULL,10);
UPDATE "Location" SET "name"='Gəncə', "kind"='CITY', "order"=10 WHERE "slug"='gence';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_sumqayit','Sumqayıt','sumqayit','CITY',NULL,20);
UPDATE "Location" SET "name"='Sumqayıt', "kind"='CITY', "order"=20 WHERE "slug"='sumqayit';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_xirdalan','Xırdalan','xirdalan','CITY',NULL,30);
UPDATE "Location" SET "name"='Xırdalan', "kind"='CITY', "order"=30 WHERE "slug"='xirdalan';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_mingecevir','Mingəçevir','mingecevir','CITY',NULL,40);
UPDATE "Location" SET "name"='Mingəçevir', "kind"='CITY', "order"=40 WHERE "slug"='mingecevir';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_sirvan','Şirvan','sirvan','CITY',NULL,50);
UPDATE "Location" SET "name"='Şirvan', "kind"='CITY', "order"=50 WHERE "slug"='sirvan';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_naftalan','Naftalan','naftalan','CITY',NULL,60);
UPDATE "Location" SET "name"='Naftalan', "kind"='CITY', "order"=60 WHERE "slug"='naftalan';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_naxcivan','Naxçıvan','naxcivan','CITY',NULL,70);
UPDATE "Location" SET "name"='Naxçıvan', "kind"='CITY', "order"=70 WHERE "slug"='naxcivan';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_xankendi','Xankəndi','xankendi','CITY',NULL,80);
UPDATE "Location" SET "name"='Xankəndi', "kind"='CITY', "order"=80 WHERE "slug"='xankendi';

-- Rayonlar (şəhərlərlə eyni pillədə seçilir)
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_abseron','Abşeron','abseron','CITY',NULL,1000);
UPDATE "Location" SET "name"='Abşeron', "kind"='CITY', "order"=1000 WHERE "slug"='abseron';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_agcabedi','Ağcabədi','agcabedi','CITY',NULL,1010);
UPDATE "Location" SET "name"='Ağcabədi', "kind"='CITY', "order"=1010 WHERE "slug"='agcabedi';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_agdam','Ağdam','agdam','CITY',NULL,1020);
UPDATE "Location" SET "name"='Ağdam', "kind"='CITY', "order"=1020 WHERE "slug"='agdam';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_agdas','Ağdaş','agdas','CITY',NULL,1030);
UPDATE "Location" SET "name"='Ağdaş', "kind"='CITY', "order"=1030 WHERE "slug"='agdas';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_agstafa','Ağstafa','agstafa','CITY',NULL,1040);
UPDATE "Location" SET "name"='Ağstafa', "kind"='CITY', "order"=1040 WHERE "slug"='agstafa';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_agsu','Ağsu','agsu','CITY',NULL,1050);
UPDATE "Location" SET "name"='Ağsu', "kind"='CITY', "order"=1050 WHERE "slug"='agsu';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_astara','Astara','astara','CITY',NULL,1060);
UPDATE "Location" SET "name"='Astara', "kind"='CITY', "order"=1060 WHERE "slug"='astara';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_babek','Babək','babek','CITY',NULL,1070);
UPDATE "Location" SET "name"='Babək', "kind"='CITY', "order"=1070 WHERE "slug"='babek';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_balaken','Balakən','balaken','CITY',NULL,1080);
UPDATE "Location" SET "name"='Balakən', "kind"='CITY', "order"=1080 WHERE "slug"='balaken';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_beyleqan','Beyləqan','beyleqan','CITY',NULL,1090);
UPDATE "Location" SET "name"='Beyləqan', "kind"='CITY', "order"=1090 WHERE "slug"='beyleqan';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_berde','Bərdə','berde','CITY',NULL,1100);
UPDATE "Location" SET "name"='Bərdə', "kind"='CITY', "order"=1100 WHERE "slug"='berde';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_bilesuvar','Biləsuvar','bilesuvar','CITY',NULL,1110);
UPDATE "Location" SET "name"='Biləsuvar', "kind"='CITY', "order"=1110 WHERE "slug"='bilesuvar';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_cebrayil','Cəbrayıl','cebrayil','CITY',NULL,1120);
UPDATE "Location" SET "name"='Cəbrayıl', "kind"='CITY', "order"=1120 WHERE "slug"='cebrayil';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_celilabad','Cəlilabad','celilabad','CITY',NULL,1130);
UPDATE "Location" SET "name"='Cəlilabad', "kind"='CITY', "order"=1130 WHERE "slug"='celilabad';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_culfa','Culfa','culfa','CITY',NULL,1140);
UPDATE "Location" SET "name"='Culfa', "kind"='CITY', "order"=1140 WHERE "slug"='culfa';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_daskesen','Daşkəsən','daskesen','CITY',NULL,1150);
UPDATE "Location" SET "name"='Daşkəsən', "kind"='CITY', "order"=1150 WHERE "slug"='daskesen';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_fuzuli','Füzuli','fuzuli','CITY',NULL,1160);
UPDATE "Location" SET "name"='Füzuli', "kind"='CITY', "order"=1160 WHERE "slug"='fuzuli';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_gedebey','Gədəbəy','gedebey','CITY',NULL,1170);
UPDATE "Location" SET "name"='Gədəbəy', "kind"='CITY', "order"=1170 WHERE "slug"='gedebey';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_goranboy','Goranboy','goranboy','CITY',NULL,1180);
UPDATE "Location" SET "name"='Goranboy', "kind"='CITY', "order"=1180 WHERE "slug"='goranboy';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_goycay','Göyçay','goycay','CITY',NULL,1190);
UPDATE "Location" SET "name"='Göyçay', "kind"='CITY', "order"=1190 WHERE "slug"='goycay';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_goygol','Göygöl','goygol','CITY',NULL,1200);
UPDATE "Location" SET "name"='Göygöl', "kind"='CITY', "order"=1200 WHERE "slug"='goygol';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_haciqabul','Hacıqabul','haciqabul','CITY',NULL,1210);
UPDATE "Location" SET "name"='Hacıqabul', "kind"='CITY', "order"=1210 WHERE "slug"='haciqabul';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_imisli','İmişli','imisli','CITY',NULL,1220);
UPDATE "Location" SET "name"='İmişli', "kind"='CITY', "order"=1220 WHERE "slug"='imisli';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_ismayilli','İsmayıllı','ismayilli','CITY',NULL,1230);
UPDATE "Location" SET "name"='İsmayıllı', "kind"='CITY', "order"=1230 WHERE "slug"='ismayilli';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_kelbecer','Kəlbəcər','kelbecer','CITY',NULL,1240);
UPDATE "Location" SET "name"='Kəlbəcər', "kind"='CITY', "order"=1240 WHERE "slug"='kelbecer';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_kengerli','Kəngərli','kengerli','CITY',NULL,1250);
UPDATE "Location" SET "name"='Kəngərli', "kind"='CITY', "order"=1250 WHERE "slug"='kengerli';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_kurdemir','Kürdəmir','kurdemir','CITY',NULL,1260);
UPDATE "Location" SET "name"='Kürdəmir', "kind"='CITY', "order"=1260 WHERE "slug"='kurdemir';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_qax','Qax','qax','CITY',NULL,1270);
UPDATE "Location" SET "name"='Qax', "kind"='CITY', "order"=1270 WHERE "slug"='qax';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_qazax','Qazax','qazax','CITY',NULL,1280);
UPDATE "Location" SET "name"='Qazax', "kind"='CITY', "order"=1280 WHERE "slug"='qazax';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_qobustan','Qobustan','qobustan','CITY',NULL,1290);
UPDATE "Location" SET "name"='Qobustan', "kind"='CITY', "order"=1290 WHERE "slug"='qobustan';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_quba','Quba','quba','CITY',NULL,1300);
UPDATE "Location" SET "name"='Quba', "kind"='CITY', "order"=1300 WHERE "slug"='quba';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_qubadli','Qubadlı','qubadli','CITY',NULL,1310);
UPDATE "Location" SET "name"='Qubadlı', "kind"='CITY', "order"=1310 WHERE "slug"='qubadli';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_qusar','Qusar','qusar','CITY',NULL,1320);
UPDATE "Location" SET "name"='Qusar', "kind"='CITY', "order"=1320 WHERE "slug"='qusar';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_lacin','Laçın','lacin','CITY',NULL,1330);
UPDATE "Location" SET "name"='Laçın', "kind"='CITY', "order"=1330 WHERE "slug"='lacin';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_lerik','Lerik','lerik','CITY',NULL,1340);
UPDATE "Location" SET "name"='Lerik', "kind"='CITY', "order"=1340 WHERE "slug"='lerik';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_lenkeran','Lənkəran','lenkeran','CITY',NULL,1350);
UPDATE "Location" SET "name"='Lənkəran', "kind"='CITY', "order"=1350 WHERE "slug"='lenkeran';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_masalli','Masallı','masalli','CITY',NULL,1360);
UPDATE "Location" SET "name"='Masallı', "kind"='CITY', "order"=1360 WHERE "slug"='masalli';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_neftcala','Neftçala','neftcala','CITY',NULL,1370);
UPDATE "Location" SET "name"='Neftçala', "kind"='CITY', "order"=1370 WHERE "slug"='neftcala';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_oguz','Oğuz','oguz','CITY',NULL,1380);
UPDATE "Location" SET "name"='Oğuz', "kind"='CITY', "order"=1380 WHERE "slug"='oguz';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_ordubad','Ordubad','ordubad','CITY',NULL,1390);
UPDATE "Location" SET "name"='Ordubad', "kind"='CITY', "order"=1390 WHERE "slug"='ordubad';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_saatli','Saatlı','saatli','CITY',NULL,1400);
UPDATE "Location" SET "name"='Saatlı', "kind"='CITY', "order"=1400 WHERE "slug"='saatli';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_sabirabad','Sabirabad','sabirabad','CITY',NULL,1410);
UPDATE "Location" SET "name"='Sabirabad', "kind"='CITY', "order"=1410 WHERE "slug"='sabirabad';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_salyan','Salyan','salyan','CITY',NULL,1420);
UPDATE "Location" SET "name"='Salyan', "kind"='CITY', "order"=1420 WHERE "slug"='salyan';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_samux','Samux','samux','CITY',NULL,1430);
UPDATE "Location" SET "name"='Samux', "kind"='CITY', "order"=1430 WHERE "slug"='samux';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_sederek','Sədərək','sederek','CITY',NULL,1440);
UPDATE "Location" SET "name"='Sədərək', "kind"='CITY', "order"=1440 WHERE "slug"='sederek';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_siyezen','Siyəzən','siyezen','CITY',NULL,1450);
UPDATE "Location" SET "name"='Siyəzən', "kind"='CITY', "order"=1450 WHERE "slug"='siyezen';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_sabran','Şabran','sabran','CITY',NULL,1460);
UPDATE "Location" SET "name"='Şabran', "kind"='CITY', "order"=1460 WHERE "slug"='sabran';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_sahbuz','Şahbuz','sahbuz','CITY',NULL,1470);
UPDATE "Location" SET "name"='Şahbuz', "kind"='CITY', "order"=1470 WHERE "slug"='sahbuz';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_samaxi','Şamaxı','samaxi','CITY',NULL,1480);
UPDATE "Location" SET "name"='Şamaxı', "kind"='CITY', "order"=1480 WHERE "slug"='samaxi';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_seki','Şəki','seki','CITY',NULL,1490);
UPDATE "Location" SET "name"='Şəki', "kind"='CITY', "order"=1490 WHERE "slug"='seki';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_semkir','Şəmkir','semkir','CITY',NULL,1500);
UPDATE "Location" SET "name"='Şəmkir', "kind"='CITY', "order"=1500 WHERE "slug"='semkir';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_serur','Şərur','serur','CITY',NULL,1510);
UPDATE "Location" SET "name"='Şərur', "kind"='CITY', "order"=1510 WHERE "slug"='serur';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_susa','Şuşa','susa','CITY',NULL,1520);
UPDATE "Location" SET "name"='Şuşa', "kind"='CITY', "order"=1520 WHERE "slug"='susa';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_terter','Tərtər','terter','CITY',NULL,1530);
UPDATE "Location" SET "name"='Tərtər', "kind"='CITY', "order"=1530 WHERE "slug"='terter';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_tovuz','Tovuz','tovuz','CITY',NULL,1540);
UPDATE "Location" SET "name"='Tovuz', "kind"='CITY', "order"=1540 WHERE "slug"='tovuz';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_ucar','Ucar','ucar','CITY',NULL,1550);
UPDATE "Location" SET "name"='Ucar', "kind"='CITY', "order"=1550 WHERE "slug"='ucar';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_xacmaz','Xaçmaz','xacmaz','CITY',NULL,1560);
UPDATE "Location" SET "name"='Xaçmaz', "kind"='CITY', "order"=1560 WHERE "slug"='xacmaz';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_xizi','Xızı','xizi','CITY',NULL,1570);
UPDATE "Location" SET "name"='Xızı', "kind"='CITY', "order"=1570 WHERE "slug"='xizi';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_xocali','Xocalı','xocali','CITY',NULL,1580);
UPDATE "Location" SET "name"='Xocalı', "kind"='CITY', "order"=1580 WHERE "slug"='xocali';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_xocavend','Xocavənd','xocavend','CITY',NULL,1590);
UPDATE "Location" SET "name"='Xocavənd', "kind"='CITY', "order"=1590 WHERE "slug"='xocavend';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_yardimli','Yardımlı','yardimli','CITY',NULL,1600);
UPDATE "Location" SET "name"='Yardımlı', "kind"='CITY', "order"=1600 WHERE "slug"='yardimli';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_yevlax','Yevlax','yevlax','CITY',NULL,1610);
UPDATE "Location" SET "name"='Yevlax', "kind"='CITY', "order"=1610 WHERE "slug"='yevlax';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_zaqatala','Zaqatala','zaqatala','CITY',NULL,1620);
UPDATE "Location" SET "name"='Zaqatala', "kind"='CITY', "order"=1620 WHERE "slug"='zaqatala';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_zengilan','Zəngilan','zengilan','CITY',NULL,1630);
UPDATE "Location" SET "name"='Zəngilan', "kind"='CITY', "order"=1630 WHERE "slug"='zengilan';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_zerdab','Zərdab','zerdab','CITY',NULL,1640);
UPDATE "Location" SET "name"='Zərdab', "kind"='CITY', "order"=1640 WHERE "slug"='zerdab';

-- Bakının inzibati rayonları
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_baki-bineqedi','Binəqədi','baki-bineqedi','DISTRICT',(SELECT "id" FROM "Location" WHERE "slug"='baki'),0);
UPDATE "Location" SET "name"='Binəqədi', "kind"='DISTRICT', "order"=0, "parentId"=(SELECT "id" FROM "Location" WHERE "slug"='baki') WHERE "slug"='baki-bineqedi';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_baki-nerimanov','Nərimanov','baki-nerimanov','DISTRICT',(SELECT "id" FROM "Location" WHERE "slug"='baki'),10);
UPDATE "Location" SET "name"='Nərimanov', "kind"='DISTRICT', "order"=10, "parentId"=(SELECT "id" FROM "Location" WHERE "slug"='baki') WHERE "slug"='baki-nerimanov';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_baki-nesimi','Nəsimi','baki-nesimi','DISTRICT',(SELECT "id" FROM "Location" WHERE "slug"='baki'),20);
UPDATE "Location" SET "name"='Nəsimi', "kind"='DISTRICT', "order"=20, "parentId"=(SELECT "id" FROM "Location" WHERE "slug"='baki') WHERE "slug"='baki-nesimi';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_baki-nizami','Nizami','baki-nizami','DISTRICT',(SELECT "id" FROM "Location" WHERE "slug"='baki'),30);
UPDATE "Location" SET "name"='Nizami', "kind"='DISTRICT', "order"=30, "parentId"=(SELECT "id" FROM "Location" WHERE "slug"='baki') WHERE "slug"='baki-nizami';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_baki-qaradag','Qaradağ','baki-qaradag','DISTRICT',(SELECT "id" FROM "Location" WHERE "slug"='baki'),40);
UPDATE "Location" SET "name"='Qaradağ', "kind"='DISTRICT', "order"=40, "parentId"=(SELECT "id" FROM "Location" WHERE "slug"='baki') WHERE "slug"='baki-qaradag';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_baki-sabuncu','Sabunçu','baki-sabuncu','DISTRICT',(SELECT "id" FROM "Location" WHERE "slug"='baki'),50);
UPDATE "Location" SET "name"='Sabunçu', "kind"='DISTRICT', "order"=50, "parentId"=(SELECT "id" FROM "Location" WHERE "slug"='baki') WHERE "slug"='baki-sabuncu';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_baki-sebail','Səbail','baki-sebail','DISTRICT',(SELECT "id" FROM "Location" WHERE "slug"='baki'),60);
UPDATE "Location" SET "name"='Səbail', "kind"='DISTRICT', "order"=60, "parentId"=(SELECT "id" FROM "Location" WHERE "slug"='baki') WHERE "slug"='baki-sebail';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_baki-suraxani','Suraxanı','baki-suraxani','DISTRICT',(SELECT "id" FROM "Location" WHERE "slug"='baki'),70);
UPDATE "Location" SET "name"='Suraxanı', "kind"='DISTRICT', "order"=70, "parentId"=(SELECT "id" FROM "Location" WHERE "slug"='baki') WHERE "slug"='baki-suraxani';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_baki-xezer','Xəzər','baki-xezer','DISTRICT',(SELECT "id" FROM "Location" WHERE "slug"='baki'),80);
UPDATE "Location" SET "name"='Xəzər', "kind"='DISTRICT', "order"=80, "parentId"=(SELECT "id" FROM "Location" WHERE "slug"='baki') WHERE "slug"='baki-xezer';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_baki-xetai','Xətai','baki-xetai','DISTRICT',(SELECT "id" FROM "Location" WHERE "slug"='baki'),90);
UPDATE "Location" SET "name"='Xətai', "kind"='DISTRICT', "order"=90, "parentId"=(SELECT "id" FROM "Location" WHERE "slug"='baki') WHERE "slug"='baki-xetai';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_baki-yasamal','Yasamal','baki-yasamal','DISTRICT',(SELECT "id" FROM "Location" WHERE "slug"='baki'),100);
UPDATE "Location" SET "name"='Yasamal', "kind"='DISTRICT', "order"=100, "parentId"=(SELECT "id" FROM "Location" WHERE "slug"='baki') WHERE "slug"='baki-yasamal';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_baki-pirallahi','Pirallahı','baki-pirallahi','DISTRICT',(SELECT "id" FROM "Location" WHERE "slug"='baki'),110);
UPDATE "Location" SET "name"='Pirallahı', "kind"='DISTRICT', "order"=110, "parentId"=(SELECT "id" FROM "Location" WHERE "slug"='baki') WHERE "slug"='baki-pirallahi';

-- Bakı qəsəbələri
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_baki-8-ci-kilometr','8-ci kilometr','baki-8-ci-kilometr','SETTLEMENT',(SELECT "id" FROM "Location" WHERE "slug"='baki-bineqedi'),0);
UPDATE "Location" SET "name"='8-ci kilometr', "kind"='SETTLEMENT', "order"=0, "parentId"=(SELECT "id" FROM "Location" WHERE "slug"='baki-bineqedi') WHERE "slug"='baki-8-ci-kilometr';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_baki-9-cu-mikrorayon','9-cu mikrorayon','baki-9-cu-mikrorayon','SETTLEMENT',(SELECT "id" FROM "Location" WHERE "slug"='baki-bineqedi'),10);
UPDATE "Location" SET "name"='9-cu mikrorayon', "kind"='SETTLEMENT', "order"=10, "parentId"=(SELECT "id" FROM "Location" WHERE "slug"='baki-bineqedi') WHERE "slug"='baki-9-cu-mikrorayon';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_baki-bileceri','Biləcəri','baki-bileceri','SETTLEMENT',(SELECT "id" FROM "Location" WHERE "slug"='baki-bineqedi'),20);
UPDATE "Location" SET "name"='Biləcəri', "kind"='SETTLEMENT', "order"=20, "parentId"=(SELECT "id" FROM "Location" WHERE "slug"='baki-bineqedi') WHERE "slug"='baki-bileceri';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_baki-bineqedi-qesebesi','Binəqədi qəsəbəsi','baki-bineqedi-qesebesi','SETTLEMENT',(SELECT "id" FROM "Location" WHERE "slug"='baki-bineqedi'),30);
UPDATE "Location" SET "name"='Binəqədi qəsəbəsi', "kind"='SETTLEMENT', "order"=30, "parentId"=(SELECT "id" FROM "Location" WHERE "slug"='baki-bineqedi') WHERE "slug"='baki-bineqedi-qesebesi';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_baki-m-e-resulzade','M.Ə.Rəsulzadə','baki-m-e-resulzade','SETTLEMENT',(SELECT "id" FROM "Location" WHERE "slug"='baki-bineqedi'),40);
UPDATE "Location" SET "name"='M.Ə.Rəsulzadə', "kind"='SETTLEMENT', "order"=40, "parentId"=(SELECT "id" FROM "Location" WHERE "slug"='baki-bineqedi') WHERE "slug"='baki-m-e-resulzade';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_baki-xocesen','Xocəsən','baki-xocesen','SETTLEMENT',(SELECT "id" FROM "Location" WHERE "slug"='baki-bineqedi'),50);
UPDATE "Location" SET "name"='Xocəsən', "kind"='SETTLEMENT', "order"=50, "parentId"=(SELECT "id" FROM "Location" WHERE "slug"='baki-bineqedi') WHERE "slug"='baki-xocesen';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_baki-boyuksor','Böyükşor','baki-boyuksor','SETTLEMENT',(SELECT "id" FROM "Location" WHERE "slug"='baki-nerimanov'),0);
UPDATE "Location" SET "name"='Böyükşor', "kind"='SETTLEMENT', "order"=0, "parentId"=(SELECT "id" FROM "Location" WHERE "slug"='baki-nerimanov') WHERE "slug"='baki-boyuksor';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_baki-kesle','Keşlə','baki-kesle','SETTLEMENT',(SELECT "id" FROM "Location" WHERE "slug"='baki-nerimanov'),10);
UPDATE "Location" SET "name"='Keşlə', "kind"='SETTLEMENT', "order"=10, "parentId"=(SELECT "id" FROM "Location" WHERE "slug"='baki-nerimanov') WHERE "slug"='baki-kesle';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_baki-sovetski','Sovetski','baki-sovetski','SETTLEMENT',(SELECT "id" FROM "Location" WHERE "slug"='baki-nerimanov'),20);
UPDATE "Location" SET "name"='Sovetski', "kind"='SETTLEMENT', "order"=20, "parentId"=(SELECT "id" FROM "Location" WHERE "slug"='baki-nerimanov') WHERE "slug"='baki-sovetski';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_baki-1-ci-mikrorayon','1-ci mikrorayon','baki-1-ci-mikrorayon','SETTLEMENT',(SELECT "id" FROM "Location" WHERE "slug"='baki-nesimi'),0);
UPDATE "Location" SET "name"='1-ci mikrorayon', "kind"='SETTLEMENT', "order"=0, "parentId"=(SELECT "id" FROM "Location" WHERE "slug"='baki-nesimi') WHERE "slug"='baki-1-ci-mikrorayon';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_baki-2-ci-mikrorayon','2-ci mikrorayon','baki-2-ci-mikrorayon','SETTLEMENT',(SELECT "id" FROM "Location" WHERE "slug"='baki-nesimi'),10);
UPDATE "Location" SET "name"='2-ci mikrorayon', "kind"='SETTLEMENT', "order"=10, "parentId"=(SELECT "id" FROM "Location" WHERE "slug"='baki-nesimi') WHERE "slug"='baki-2-ci-mikrorayon';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_baki-3-cu-mikrorayon','3-cü mikrorayon','baki-3-cu-mikrorayon','SETTLEMENT',(SELECT "id" FROM "Location" WHERE "slug"='baki-nesimi'),20);
UPDATE "Location" SET "name"='3-cü mikrorayon', "kind"='SETTLEMENT', "order"=20, "parentId"=(SELECT "id" FROM "Location" WHERE "slug"='baki-nesimi') WHERE "slug"='baki-3-cu-mikrorayon';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_baki-4-cu-mikrorayon','4-cü mikrorayon','baki-4-cu-mikrorayon','SETTLEMENT',(SELECT "id" FROM "Location" WHERE "slug"='baki-nesimi'),30);
UPDATE "Location" SET "name"='4-cü mikrorayon', "kind"='SETTLEMENT', "order"=30, "parentId"=(SELECT "id" FROM "Location" WHERE "slug"='baki-nesimi') WHERE "slug"='baki-4-cu-mikrorayon';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_baki-kesle-qesebesi','Keşlə qəsəbəsi','baki-kesle-qesebesi','SETTLEMENT',(SELECT "id" FROM "Location" WHERE "slug"='baki-nizami'),10);
UPDATE "Location" SET "name"='Keşlə qəsəbəsi', "kind"='SETTLEMENT', "order"=10, "parentId"=(SELECT "id" FROM "Location" WHERE "slug"='baki-nizami') WHERE "slug"='baki-kesle-qesebesi';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_baki-elet','Ələt','baki-elet','SETTLEMENT',(SELECT "id" FROM "Location" WHERE "slug"='baki-qaradag'),0);
UPDATE "Location" SET "name"='Ələt', "kind"='SETTLEMENT', "order"=0, "parentId"=(SELECT "id" FROM "Location" WHERE "slug"='baki-qaradag') WHERE "slug"='baki-elet';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_baki-lokbatan','Lökbatan','baki-lokbatan','SETTLEMENT',(SELECT "id" FROM "Location" WHERE "slug"='baki-qaradag'),10);
UPDATE "Location" SET "name"='Lökbatan', "kind"='SETTLEMENT', "order"=10, "parentId"=(SELECT "id" FROM "Location" WHERE "slug"='baki-qaradag') WHERE "slug"='baki-lokbatan';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_baki-puta','Puta','baki-puta','SETTLEMENT',(SELECT "id" FROM "Location" WHERE "slug"='baki-qaradag'),20);
UPDATE "Location" SET "name"='Puta', "kind"='SETTLEMENT', "order"=20, "parentId"=(SELECT "id" FROM "Location" WHERE "slug"='baki-qaradag') WHERE "slug"='baki-puta';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_baki-qizildas','Qızıldaş','baki-qizildas','SETTLEMENT',(SELECT "id" FROM "Location" WHERE "slug"='baki-qaradag'),30);
UPDATE "Location" SET "name"='Qızıldaş', "kind"='SETTLEMENT', "order"=30, "parentId"=(SELECT "id" FROM "Location" WHERE "slug"='baki-qaradag') WHERE "slug"='baki-qizildas';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_baki-qobustan-qesebesi','Qobustan qəsəbəsi','baki-qobustan-qesebesi','SETTLEMENT',(SELECT "id" FROM "Location" WHERE "slug"='baki-qaradag'),40);
UPDATE "Location" SET "name"='Qobustan qəsəbəsi', "kind"='SETTLEMENT', "order"=40, "parentId"=(SELECT "id" FROM "Location" WHERE "slug"='baki-qaradag') WHERE "slug"='baki-qobustan-qesebesi';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_baki-sahil','Sahil','baki-sahil','SETTLEMENT',(SELECT "id" FROM "Location" WHERE "slug"='baki-qaradag'),50);
UPDATE "Location" SET "name"='Sahil', "kind"='SETTLEMENT', "order"=50, "parentId"=(SELECT "id" FROM "Location" WHERE "slug"='baki-qaradag') WHERE "slug"='baki-sahil';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_baki-sengecal','Səngəçal','baki-sengecal','SETTLEMENT',(SELECT "id" FROM "Location" WHERE "slug"='baki-qaradag'),60);
UPDATE "Location" SET "name"='Səngəçal', "kind"='SETTLEMENT', "order"=60, "parentId"=(SELECT "id" FROM "Location" WHERE "slug"='baki-qaradag') WHERE "slug"='baki-sengecal';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_baki-bakixanov','Bakıxanov','baki-bakixanov','SETTLEMENT',(SELECT "id" FROM "Location" WHERE "slug"='baki-sabuncu'),0);
UPDATE "Location" SET "name"='Bakıxanov', "kind"='SETTLEMENT', "order"=0, "parentId"=(SELECT "id" FROM "Location" WHERE "slug"='baki-sabuncu') WHERE "slug"='baki-bakixanov';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_baki-balaxani','Balaxanı','baki-balaxani','SETTLEMENT',(SELECT "id" FROM "Location" WHERE "slug"='baki-sabuncu'),10);
UPDATE "Location" SET "name"='Balaxanı', "kind"='SETTLEMENT', "order"=10, "parentId"=(SELECT "id" FROM "Location" WHERE "slug"='baki-sabuncu') WHERE "slug"='baki-balaxani';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_baki-bilgeh','Bilgəh','baki-bilgeh','SETTLEMENT',(SELECT "id" FROM "Location" WHERE "slug"='baki-sabuncu'),20);
UPDATE "Location" SET "name"='Bilgəh', "kind"='SETTLEMENT', "order"=20, "parentId"=(SELECT "id" FROM "Location" WHERE "slug"='baki-sabuncu') WHERE "slug"='baki-bilgeh';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_baki-kurdexani','Kürdəxanı','baki-kurdexani','SETTLEMENT',(SELECT "id" FROM "Location" WHERE "slug"='baki-sabuncu'),30);
UPDATE "Location" SET "name"='Kürdəxanı', "kind"='SETTLEMENT', "order"=30, "parentId"=(SELECT "id" FROM "Location" WHERE "slug"='baki-sabuncu') WHERE "slug"='baki-kurdexani';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_baki-mastaga','Maştağa','baki-mastaga','SETTLEMENT',(SELECT "id" FROM "Location" WHERE "slug"='baki-sabuncu'),40);
UPDATE "Location" SET "name"='Maştağa', "kind"='SETTLEMENT', "order"=40, "parentId"=(SELECT "id" FROM "Location" WHERE "slug"='baki-sabuncu') WHERE "slug"='baki-mastaga';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_baki-nardaran','Nardaran','baki-nardaran','SETTLEMENT',(SELECT "id" FROM "Location" WHERE "slug"='baki-sabuncu'),50);
UPDATE "Location" SET "name"='Nardaran', "kind"='SETTLEMENT', "order"=50, "parentId"=(SELECT "id" FROM "Location" WHERE "slug"='baki-sabuncu') WHERE "slug"='baki-nardaran';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_baki-pirsagi','Pirşağı','baki-pirsagi','SETTLEMENT',(SELECT "id" FROM "Location" WHERE "slug"='baki-sabuncu'),60);
UPDATE "Location" SET "name"='Pirşağı', "kind"='SETTLEMENT', "order"=60, "parentId"=(SELECT "id" FROM "Location" WHERE "slug"='baki-sabuncu') WHERE "slug"='baki-pirsagi';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_baki-ramana','Ramana','baki-ramana','SETTLEMENT',(SELECT "id" FROM "Location" WHERE "slug"='baki-sabuncu'),70);
UPDATE "Location" SET "name"='Ramana', "kind"='SETTLEMENT', "order"=70, "parentId"=(SELECT "id" FROM "Location" WHERE "slug"='baki-sabuncu') WHERE "slug"='baki-ramana';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_baki-savalan','Savalan','baki-savalan','SETTLEMENT',(SELECT "id" FROM "Location" WHERE "slug"='baki-sabuncu'),80);
UPDATE "Location" SET "name"='Savalan', "kind"='SETTLEMENT', "order"=80, "parentId"=(SELECT "id" FROM "Location" WHERE "slug"='baki-sabuncu') WHERE "slug"='baki-savalan';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_baki-zabrat','Zabrat','baki-zabrat','SETTLEMENT',(SELECT "id" FROM "Location" WHERE "slug"='baki-sabuncu'),90);
UPDATE "Location" SET "name"='Zabrat', "kind"='SETTLEMENT', "order"=90, "parentId"=(SELECT "id" FROM "Location" WHERE "slug"='baki-sabuncu') WHERE "slug"='baki-zabrat';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_baki-badamdar','Badamdar','baki-badamdar','SETTLEMENT',(SELECT "id" FROM "Location" WHERE "slug"='baki-sebail'),0);
UPDATE "Location" SET "name"='Badamdar', "kind"='SETTLEMENT', "order"=0, "parentId"=(SELECT "id" FROM "Location" WHERE "slug"='baki-sebail') WHERE "slug"='baki-badamdar';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_baki-bayil','Bayıl','baki-bayil','SETTLEMENT',(SELECT "id" FROM "Location" WHERE "slug"='baki-sebail'),10);
UPDATE "Location" SET "name"='Bayıl', "kind"='SETTLEMENT', "order"=10, "parentId"=(SELECT "id" FROM "Location" WHERE "slug"='baki-sebail') WHERE "slug"='baki-bayil';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_baki-bibiheybet','Bibiheybət','baki-bibiheybet','SETTLEMENT',(SELECT "id" FROM "Location" WHERE "slug"='baki-sebail'),20);
UPDATE "Location" SET "name"='Bibiheybət', "kind"='SETTLEMENT', "order"=20, "parentId"=(SELECT "id" FROM "Location" WHERE "slug"='baki-sebail') WHERE "slug"='baki-bibiheybet';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_baki-iceriseher','İçərişəhər','baki-iceriseher','SETTLEMENT',(SELECT "id" FROM "Location" WHERE "slug"='baki-sebail'),30);
UPDATE "Location" SET "name"='İçərişəhər', "kind"='SETTLEMENT', "order"=30, "parentId"=(SELECT "id" FROM "Location" WHERE "slug"='baki-sebail') WHERE "slug"='baki-iceriseher';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_baki-sixov','Şıxov','baki-sixov','SETTLEMENT',(SELECT "id" FROM "Location" WHERE "slug"='baki-sebail'),40);
UPDATE "Location" SET "name"='Şıxov', "kind"='SETTLEMENT', "order"=40, "parentId"=(SELECT "id" FROM "Location" WHERE "slug"='baki-sebail') WHERE "slug"='baki-sixov';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_baki-bahar','Bahar','baki-bahar','SETTLEMENT',(SELECT "id" FROM "Location" WHERE "slug"='baki-suraxani'),0);
UPDATE "Location" SET "name"='Bahar', "kind"='SETTLEMENT', "order"=0, "parentId"=(SELECT "id" FROM "Location" WHERE "slug"='baki-suraxani') WHERE "slug"='baki-bahar';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_baki-bulbule','Bülbülə','baki-bulbule','SETTLEMENT',(SELECT "id" FROM "Location" WHERE "slug"='baki-suraxani'),10);
UPDATE "Location" SET "name"='Bülbülə', "kind"='SETTLEMENT', "order"=10, "parentId"=(SELECT "id" FROM "Location" WHERE "slug"='baki-suraxani') WHERE "slug"='baki-bulbule';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_baki-hovsan','Hövsan','baki-hovsan','SETTLEMENT',(SELECT "id" FROM "Location" WHERE "slug"='baki-suraxani'),20);
UPDATE "Location" SET "name"='Hövsan', "kind"='SETTLEMENT', "order"=20, "parentId"=(SELECT "id" FROM "Location" WHERE "slug"='baki-suraxani') WHERE "slug"='baki-hovsan';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_baki-qaracuxur','Qaraçuxur','baki-qaracuxur','SETTLEMENT',(SELECT "id" FROM "Location" WHERE "slug"='baki-suraxani'),30);
UPDATE "Location" SET "name"='Qaraçuxur', "kind"='SETTLEMENT', "order"=30, "parentId"=(SELECT "id" FROM "Location" WHERE "slug"='baki-suraxani') WHERE "slug"='baki-qaracuxur';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_baki-yeni-gunesli','Yeni Günəşli','baki-yeni-gunesli','SETTLEMENT',(SELECT "id" FROM "Location" WHERE "slug"='baki-suraxani'),40);
UPDATE "Location" SET "name"='Yeni Günəşli', "kind"='SETTLEMENT', "order"=40, "parentId"=(SELECT "id" FROM "Location" WHERE "slug"='baki-suraxani') WHERE "slug"='baki-yeni-gunesli';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_baki-zig','Zığ','baki-zig','SETTLEMENT',(SELECT "id" FROM "Location" WHERE "slug"='baki-suraxani'),50);
UPDATE "Location" SET "name"='Zığ', "kind"='SETTLEMENT', "order"=50, "parentId"=(SELECT "id" FROM "Location" WHERE "slug"='baki-suraxani') WHERE "slug"='baki-zig';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_baki-buzovna','Buzovna','baki-buzovna','SETTLEMENT',(SELECT "id" FROM "Location" WHERE "slug"='baki-xezer'),0);
UPDATE "Location" SET "name"='Buzovna', "kind"='SETTLEMENT', "order"=0, "parentId"=(SELECT "id" FROM "Location" WHERE "slug"='baki-xezer') WHERE "slug"='baki-buzovna';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_baki-dubendi','Dübəndi','baki-dubendi','SETTLEMENT',(SELECT "id" FROM "Location" WHERE "slug"='baki-xezer'),10);
UPDATE "Location" SET "name"='Dübəndi', "kind"='SETTLEMENT', "order"=10, "parentId"=(SELECT "id" FROM "Location" WHERE "slug"='baki-xezer') WHERE "slug"='baki-dubendi';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_baki-goredil','Görədil','baki-goredil','SETTLEMENT',(SELECT "id" FROM "Location" WHERE "slug"='baki-xezer'),20);
UPDATE "Location" SET "name"='Görədil', "kind"='SETTLEMENT', "order"=20, "parentId"=(SELECT "id" FROM "Location" WHERE "slug"='baki-xezer') WHERE "slug"='baki-goredil';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_baki-merdekan','Mərdəkan','baki-merdekan','SETTLEMENT',(SELECT "id" FROM "Location" WHERE "slug"='baki-xezer'),30);
UPDATE "Location" SET "name"='Mərdəkan', "kind"='SETTLEMENT', "order"=30, "parentId"=(SELECT "id" FROM "Location" WHERE "slug"='baki-xezer') WHERE "slug"='baki-merdekan';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_baki-qala','Qala','baki-qala','SETTLEMENT',(SELECT "id" FROM "Location" WHERE "slug"='baki-xezer'),40);
UPDATE "Location" SET "name"='Qala', "kind"='SETTLEMENT', "order"=40, "parentId"=(SELECT "id" FROM "Location" WHERE "slug"='baki-xezer') WHERE "slug"='baki-qala';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_baki-sagan','Şağan','baki-sagan','SETTLEMENT',(SELECT "id" FROM "Location" WHERE "slug"='baki-xezer'),50);
UPDATE "Location" SET "name"='Şağan', "kind"='SETTLEMENT', "order"=50, "parentId"=(SELECT "id" FROM "Location" WHERE "slug"='baki-xezer') WHERE "slug"='baki-sagan';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_baki-suvelan','Şüvəlan','baki-suvelan','SETTLEMENT',(SELECT "id" FROM "Location" WHERE "slug"='baki-xezer'),60);
UPDATE "Location" SET "name"='Şüvəlan', "kind"='SETTLEMENT', "order"=60, "parentId"=(SELECT "id" FROM "Location" WHERE "slug"='baki-xezer') WHERE "slug"='baki-suvelan';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_baki-turkan','Türkan','baki-turkan','SETTLEMENT',(SELECT "id" FROM "Location" WHERE "slug"='baki-xezer'),70);
UPDATE "Location" SET "name"='Türkan', "kind"='SETTLEMENT', "order"=70, "parentId"=(SELECT "id" FROM "Location" WHERE "slug"='baki-xezer') WHERE "slug"='baki-turkan';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_baki-zire','Zirə','baki-zire','SETTLEMENT',(SELECT "id" FROM "Location" WHERE "slug"='baki-xezer'),80);
UPDATE "Location" SET "name"='Zirə', "kind"='SETTLEMENT', "order"=80, "parentId"=(SELECT "id" FROM "Location" WHERE "slug"='baki-xezer') WHERE "slug"='baki-zire';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_baki-ag-seher','Ağ şəhər','baki-ag-seher','SETTLEMENT',(SELECT "id" FROM "Location" WHERE "slug"='baki-xetai'),0);
UPDATE "Location" SET "name"='Ağ şəhər', "kind"='SETTLEMENT', "order"=0, "parentId"=(SELECT "id" FROM "Location" WHERE "slug"='baki-xetai') WHERE "slug"='baki-ag-seher';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_baki-ehmedli','Əhmədli','baki-ehmedli','SETTLEMENT',(SELECT "id" FROM "Location" WHERE "slug"='baki-xetai'),10);
UPDATE "Location" SET "name"='Əhmədli', "kind"='SETTLEMENT', "order"=10, "parentId"=(SELECT "id" FROM "Location" WHERE "slug"='baki-xetai') WHERE "slug"='baki-ehmedli';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_baki-gunesli','Günəşli','baki-gunesli','SETTLEMENT',(SELECT "id" FROM "Location" WHERE "slug"='baki-xetai'),20);
UPDATE "Location" SET "name"='Günəşli', "kind"='SETTLEMENT', "order"=20, "parentId"=(SELECT "id" FROM "Location" WHERE "slug"='baki-xetai') WHERE "slug"='baki-gunesli';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_baki-qara-seher','Qara şəhər','baki-qara-seher','SETTLEMENT',(SELECT "id" FROM "Location" WHERE "slug"='baki-xetai'),30);
UPDATE "Location" SET "name"='Qara şəhər', "kind"='SETTLEMENT', "order"=30, "parentId"=(SELECT "id" FROM "Location" WHERE "slug"='baki-xetai') WHERE "slug"='baki-qara-seher';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_baki-yasamal-qesebesi','Yasamal qəsəbəsi','baki-yasamal-qesebesi','SETTLEMENT',(SELECT "id" FROM "Location" WHERE "slug"='baki-yasamal'),0);
UPDATE "Location" SET "name"='Yasamal qəsəbəsi', "kind"='SETTLEMENT', "order"=0, "parentId"=(SELECT "id" FROM "Location" WHERE "slug"='baki-yasamal') WHERE "slug"='baki-yasamal-qesebesi';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_baki-yeni-yasamal','Yeni Yasamal','baki-yeni-yasamal','SETTLEMENT',(SELECT "id" FROM "Location" WHERE "slug"='baki-yasamal'),10);
UPDATE "Location" SET "name"='Yeni Yasamal', "kind"='SETTLEMENT', "order"=10, "parentId"=(SELECT "id" FROM "Location" WHERE "slug"='baki-yasamal') WHERE "slug"='baki-yeni-yasamal';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_baki-gurgen','Gürgən','baki-gurgen','SETTLEMENT',(SELECT "id" FROM "Location" WHERE "slug"='baki-pirallahi'),0);
UPDATE "Location" SET "name"='Gürgən', "kind"='SETTLEMENT', "order"=0, "parentId"=(SELECT "id" FROM "Location" WHERE "slug"='baki-pirallahi') WHERE "slug"='baki-gurgen';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_baki-pirallahi-qesebesi','Pirallahı qəsəbəsi','baki-pirallahi-qesebesi','SETTLEMENT',(SELECT "id" FROM "Location" WHERE "slug"='baki-pirallahi'),10);
UPDATE "Location" SET "name"='Pirallahı qəsəbəsi', "kind"='SETTLEMENT', "order"=10, "parentId"=(SELECT "id" FROM "Location" WHERE "slug"='baki-pirallahi') WHERE "slug"='baki-pirallahi-qesebesi';

-- Metro stansiyaları
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_metro-20-yanvar','20 Yanvar','metro-20-yanvar','METRO',(SELECT "id" FROM "Location" WHERE "slug"='baki'),0);
UPDATE "Location" SET "name"='20 Yanvar', "kind"='METRO', "order"=0, "parentId"=(SELECT "id" FROM "Location" WHERE "slug"='baki') WHERE "slug"='metro-20-yanvar';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_metro-28-may','28 May','metro-28-may','METRO',(SELECT "id" FROM "Location" WHERE "slug"='baki'),10);
UPDATE "Location" SET "name"='28 May', "kind"='METRO', "order"=10, "parentId"=(SELECT "id" FROM "Location" WHERE "slug"='baki') WHERE "slug"='metro-28-may';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_metro-8-noyabr','8 Noyabr','metro-8-noyabr','METRO',(SELECT "id" FROM "Location" WHERE "slug"='baki'),20);
UPDATE "Location" SET "name"='8 Noyabr', "kind"='METRO', "order"=20, "parentId"=(SELECT "id" FROM "Location" WHERE "slug"='baki') WHERE "slug"='metro-8-noyabr';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_metro-avtovagzal','Avtovağzal','metro-avtovagzal','METRO',(SELECT "id" FROM "Location" WHERE "slug"='baki'),30);
UPDATE "Location" SET "name"='Avtovağzal', "kind"='METRO', "order"=30, "parentId"=(SELECT "id" FROM "Location" WHERE "slug"='baki') WHERE "slug"='metro-avtovagzal';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_metro-azadliq-prospekti','Azadlıq prospekti','metro-azadliq-prospekti','METRO',(SELECT "id" FROM "Location" WHERE "slug"='baki'),40);
UPDATE "Location" SET "name"='Azadlıq prospekti', "kind"='METRO', "order"=40, "parentId"=(SELECT "id" FROM "Location" WHERE "slug"='baki') WHERE "slug"='metro-azadliq-prospekti';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_metro-bakmil','Bakmil','metro-bakmil','METRO',(SELECT "id" FROM "Location" WHERE "slug"='baki'),50);
UPDATE "Location" SET "name"='Bakmil', "kind"='METRO', "order"=50, "parentId"=(SELECT "id" FROM "Location" WHERE "slug"='baki') WHERE "slug"='metro-bakmil';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_metro-cefer-cabbarli','Cəfər Cabbarlı','metro-cefer-cabbarli','METRO',(SELECT "id" FROM "Location" WHERE "slug"='baki'),60);
UPDATE "Location" SET "name"='Cəfər Cabbarlı', "kind"='METRO', "order"=60, "parentId"=(SELECT "id" FROM "Location" WHERE "slug"='baki') WHERE "slug"='metro-cefer-cabbarli';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_metro-dernegul','Dərnəgül','metro-dernegul','METRO',(SELECT "id" FROM "Location" WHERE "slug"='baki'),70);
UPDATE "Location" SET "name"='Dərnəgül', "kind"='METRO', "order"=70, "parentId"=(SELECT "id" FROM "Location" WHERE "slug"='baki') WHERE "slug"='metro-dernegul';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_metro-elmler-akademiyasi','Elmlər Akademiyası','metro-elmler-akademiyasi','METRO',(SELECT "id" FROM "Location" WHERE "slug"='baki'),80);
UPDATE "Location" SET "name"='Elmlər Akademiyası', "kind"='METRO', "order"=80, "parentId"=(SELECT "id" FROM "Location" WHERE "slug"='baki') WHERE "slug"='metro-elmler-akademiyasi';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_metro-ehmedli','Əhmədli','metro-ehmedli','METRO',(SELECT "id" FROM "Location" WHERE "slug"='baki'),90);
UPDATE "Location" SET "name"='Əhmədli', "kind"='METRO', "order"=90, "parentId"=(SELECT "id" FROM "Location" WHERE "slug"='baki') WHERE "slug"='metro-ehmedli';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_metro-genclik','Gənclik','metro-genclik','METRO',(SELECT "id" FROM "Location" WHERE "slug"='baki'),100);
UPDATE "Location" SET "name"='Gənclik', "kind"='METRO', "order"=100, "parentId"=(SELECT "id" FROM "Location" WHERE "slug"='baki') WHERE "slug"='metro-genclik';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_metro-hezi-aslanov','Həzi Aslanov','metro-hezi-aslanov','METRO',(SELECT "id" FROM "Location" WHERE "slug"='baki'),110);
UPDATE "Location" SET "name"='Həzi Aslanov', "kind"='METRO', "order"=110, "parentId"=(SELECT "id" FROM "Location" WHERE "slug"='baki') WHERE "slug"='metro-hezi-aslanov';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_metro-iceriseher','İçərişəhər','metro-iceriseher','METRO',(SELECT "id" FROM "Location" WHERE "slug"='baki'),120);
UPDATE "Location" SET "name"='İçərişəhər', "kind"='METRO', "order"=120, "parentId"=(SELECT "id" FROM "Location" WHERE "slug"='baki') WHERE "slug"='metro-iceriseher';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_metro-insaatcilar','İnşaatçılar','metro-insaatcilar','METRO',(SELECT "id" FROM "Location" WHERE "slug"='baki'),130);
UPDATE "Location" SET "name"='İnşaatçılar', "kind"='METRO', "order"=130, "parentId"=(SELECT "id" FROM "Location" WHERE "slug"='baki') WHERE "slug"='metro-insaatcilar';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_metro-koroglu','Koroğlu','metro-koroglu','METRO',(SELECT "id" FROM "Location" WHERE "slug"='baki'),140);
UPDATE "Location" SET "name"='Koroğlu', "kind"='METRO', "order"=140, "parentId"=(SELECT "id" FROM "Location" WHERE "slug"='baki') WHERE "slug"='metro-koroglu';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_metro-qara-qarayev','Qara Qarayev','metro-qara-qarayev','METRO',(SELECT "id" FROM "Location" WHERE "slug"='baki'),150);
UPDATE "Location" SET "name"='Qara Qarayev', "kind"='METRO', "order"=150, "parentId"=(SELECT "id" FROM "Location" WHERE "slug"='baki') WHERE "slug"='metro-qara-qarayev';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_metro-memar-ecemi','Memar Əcəmi','metro-memar-ecemi','METRO',(SELECT "id" FROM "Location" WHERE "slug"='baki'),160);
UPDATE "Location" SET "name"='Memar Əcəmi', "kind"='METRO', "order"=160, "parentId"=(SELECT "id" FROM "Location" WHERE "slug"='baki') WHERE "slug"='metro-memar-ecemi';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_metro-nariman-nerimanov','Nariman Nərimanov','metro-nariman-nerimanov','METRO',(SELECT "id" FROM "Location" WHERE "slug"='baki'),170);
UPDATE "Location" SET "name"='Nariman Nərimanov', "kind"='METRO', "order"=170, "parentId"=(SELECT "id" FROM "Location" WHERE "slug"='baki') WHERE "slug"='metro-nariman-nerimanov';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_metro-neftciler','Neftçilər','metro-neftciler','METRO',(SELECT "id" FROM "Location" WHERE "slug"='baki'),180);
UPDATE "Location" SET "name"='Neftçilər', "kind"='METRO', "order"=180, "parentId"=(SELECT "id" FROM "Location" WHERE "slug"='baki') WHERE "slug"='metro-neftciler';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_metro-nesimi','Nəsimi','metro-nesimi','METRO',(SELECT "id" FROM "Location" WHERE "slug"='baki'),190);
UPDATE "Location" SET "name"='Nəsimi', "kind"='METRO', "order"=190, "parentId"=(SELECT "id" FROM "Location" WHERE "slug"='baki') WHERE "slug"='metro-nesimi';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_metro-nizami','Nizami','metro-nizami','METRO',(SELECT "id" FROM "Location" WHERE "slug"='baki'),200);
UPDATE "Location" SET "name"='Nizami', "kind"='METRO', "order"=200, "parentId"=(SELECT "id" FROM "Location" WHERE "slug"='baki') WHERE "slug"='metro-nizami';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_metro-sahil','Sahil','metro-sahil','METRO',(SELECT "id" FROM "Location" WHERE "slug"='baki'),210);
UPDATE "Location" SET "name"='Sahil', "kind"='METRO', "order"=210, "parentId"=(SELECT "id" FROM "Location" WHERE "slug"='baki') WHERE "slug"='metro-sahil';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_metro-ulduz','Ulduz','metro-ulduz','METRO',(SELECT "id" FROM "Location" WHERE "slug"='baki'),220);
UPDATE "Location" SET "name"='Ulduz', "kind"='METRO', "order"=220, "parentId"=(SELECT "id" FROM "Location" WHERE "slug"='baki') WHERE "slug"='metro-ulduz';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_metro-xalqlar-dostlugu','Xalqlar Dostluğu','metro-xalqlar-dostlugu','METRO',(SELECT "id" FROM "Location" WHERE "slug"='baki'),230);
UPDATE "Location" SET "name"='Xalqlar Dostluğu', "kind"='METRO', "order"=230, "parentId"=(SELECT "id" FROM "Location" WHERE "slug"='baki') WHERE "slug"='metro-xalqlar-dostlugu';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_metro-xocesen','Xocəsən','metro-xocesen','METRO',(SELECT "id" FROM "Location" WHERE "slug"='baki'),240);
UPDATE "Location" SET "name"='Xocəsən', "kind"='METRO', "order"=240, "parentId"=(SELECT "id" FROM "Location" WHERE "slug"='baki') WHERE "slug"='metro-xocesen';
INSERT OR IGNORE INTO "Location" ("id","name","slug","kind","parentId","order") VALUES ('loc_metro-sah-ismayil-xetai','Şah İsmayıl Xətai','metro-sah-ismayil-xetai','METRO',(SELECT "id" FROM "Location" WHERE "slug"='baki'),250);
UPDATE "Location" SET "name"='Şah İsmayıl Xətai', "kind"='METRO', "order"=250, "parentId"=(SELECT "id" FROM "Location" WHERE "slug"='baki') WHERE "slug"='metro-sah-ismayil-xetai';

