import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { Link } from "@/i18n/navigation";
import { getMarketReport } from "@/lib/market-intelligence";
import { buildManagedMetadata, breadcrumbSchema, jsonLd } from "@/lib/seo";
import { siteUrl } from "@/config/site";
import type { Locale } from "@/lib/constants";
import { formatPrice } from "@/lib/utils";
import { PageHeader } from "@/components/ui/page-header";
import { Container, Section } from "@/components/ui/container";

export const dynamic = "force-dynamic";
type Props = { params: Promise<{ locale: string; slug: string }> };
const copy = { az: { market: "Bazar analitikası", home: "Ana səhifə", title: "daşınmaz əmlak bazarı", description: "Cari qiymət, inventar və əmlak növü bölgüsü", average: "Orta qiymət", median: "Median qiymət", sqm: "Orta m² qiyməti", inventory: "Aktiv inventar", change: "İllik dəyişmə", distribution: "Əmlak növlərinin bölgüsü", source: "Mənbə", measured: "Ölçmə tarixi", method: "Metodologiya", listings: "Cari elanlara bax" }, en: { market: "Market intelligence", home: "Home", title: "real estate market", description: "Current prices, inventory and property type distribution", average: "Average price", median: "Median price", sqm: "Average price per m²", inventory: "Active inventory", change: "Annual change", distribution: "Property type distribution", source: "Source", measured: "Measured at", method: "Methodology", listings: "View current listings" }, ru: { market: "Аналитика рынка", home: "Главная", title: "рынок недвижимости", description: "Текущие цены, предложение и распределение типов недвижимости", average: "Средняя цена", median: "Медианная цена", sqm: "Средняя цена за м²", inventory: "Активное предложение", change: "Годовое изменение", distribution: "Распределение типов", source: "Источник", measured: "Дата измерения", method: "Методология", listings: "Смотреть объявления" } } as const;
export async function generateMetadata({ params }: Props): Promise<Metadata> { const { locale, slug } = await params; const report = await getMarketReport(slug); if (!report) notFound(); const t = copy[locale as Locale] ?? copy.az; return buildManagedMetadata({ title: `${report.name} ${t.title}`, description: `${report.name}: ${t.description.toLocaleLowerCase(locale)}.`, path: `/bazar-analitikasi/${slug}`, locale: locale as Locale, managedEntity: { type: "LOCATION", id: slug } }); }
export default async function MarketReportPage({ params }: Props) {
  const { locale, slug } = await params; const localeValue = locale as Locale; const t = copy[localeValue] ?? copy.az; const report = await getMarketReport(slug); if (!report) notFound();
  const schema = { "@context": "https://schema.org", "@type": "Dataset", name: `${report.name} ${t.title}`, description: report.methodology, url: siteUrl(`/${localeValue}/bazar-analitikasi/${slug}`), dateModified: report.measuredAt.toISOString(), creator: { "@id": `${siteUrl()}/#organization` }, measurementTechnique: report.methodology, isBasedOn: report.dataSource, variableMeasured: [t.average, t.median, t.sqm, t.inventory, t.change] };
  const metrics = [[t.average, report.averagePrice != null ? formatPrice(report.averagePrice) : "—"], [t.median, report.medianPrice != null ? formatPrice(report.medianPrice) : "—"], [t.sqm, report.averagePricePerSqm != null ? `${formatPrice(report.averagePricePerSqm)}/m²` : "—"], [t.inventory, String(report.inventory)], [t.change, report.annualChangePercent != null ? `${report.annualChangePercent > 0 ? "+" : ""}${report.annualChangePercent}%` : "—"]];
  return <><script {...jsonLd(schema)} /><script {...jsonLd(breadcrumbSchema([{ name: t.home, path: "/" }, { name: t.market, path: "/bazar-analitikasi" }, { name: report.name, path: `/bazar-analitikasi/${slug}` }], localeValue))} />
    <PageHeader eyebrow="Luxe Home Estate Data" title={`${report.name} ${t.title}`} description={report.description || `${report.name}: ${t.description}.`} breadcrumbs={[{ label: t.home, href: "/" }, { label: t.market, href: "/bazar-analitikasi" }, { label: report.name }]} />
    <Section tone="ivory" spacing="cozy"><Container><dl className="grid gap-px overflow-hidden rounded-md border border-line bg-line sm:grid-cols-2 xl:grid-cols-5">{metrics.map(([label, value]) => <div key={label} className="bg-paper p-5"><dt className="text-xs tracking-wide text-ink-muted uppercase">{label}</dt><dd className="tabular mt-2 font-display text-2xl text-ink">{value}</dd></div>)}</dl>
      <div className="mt-8 grid gap-8 lg:grid-cols-[1fr_380px]"><article className="rounded-md border border-line bg-paper p-6"><h2 className="font-display text-2xl text-ink">{t.distribution}</h2><ul className="mt-5 space-y-4">{report.typeDistribution.map((item) => <li key={item.name}><div className="flex justify-between text-sm"><span className="text-ink">{item.name}</span><span className="tabular text-ink-soft">{item.count} · {item.percent}%</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-beige"><div className="h-full bg-gold" style={{ width: `${item.percent}%` }} /></div></li>)}</ul></article>
        <aside className="rounded-md border border-line bg-paper p-6"><h2 className="font-display text-xl text-ink">{t.method}</h2><p className="mt-3 text-sm leading-6 text-ink-soft">{report.methodology}</p><dl className="mt-5 space-y-3 text-sm"><div><dt className="text-ink-muted">{t.source}</dt><dd className="text-ink">{report.dataSource}</dd></div><div><dt className="text-ink-muted">{t.measured}</dt><dd className="text-ink">{report.measuredAt.toLocaleDateString(localeValue)}</dd></div></dl><Link href={slug === "baki" ? "/emlaklar" : `/rayon/${slug}`} className="mt-6 inline-flex min-h-11 items-center rounded-xs bg-gold px-4 text-sm font-medium text-on-gold">{t.listings}</Link></aside></div>
    </Container></Section>
  </>;
}
